### ISSUE TITLE
Glossary display + use

### ISSUE THREAD

**Issue by plaindocs** [asciidoctor/asciidoctor-pdf#100]
What is the (intended) advantage of using the `[glossary]` tag over a normal definition list? And can I also use `[glossary, horizontal]` for example?

**Comment by mojavelinux** [comment]
The glossary tag is purely semantic (no visual difference) for generating DocBook. It provides the hint for the DocBook output to use the `glossary` tag instead of a normal definition list. In the HTML and Asciidoctor PDF backends, I don't believe it does anything special. It's just a normal definition list. Of course, in the future, we might take it further and open the doors to a specialized layout...so it's worth adding.

At the moment, you can't use both glossary and horizonal together. Though, to be honest, horizontal should be an option (or a role), not a style. That would solve this issue. horizontal is a bit of a strange legacy piece from AsciiDoc Python that isn't exactly semantic. We might need to rethink the meaning / approach of it in core....such as by making it a role or option as I suggested.

**Comment by fwilhe** [comment]
It would be neat if Asciidoctor PDF provided features like LaTeX-glossary packages do, e.g. printing the page where a term occurs like

> _My Term_ Has some long description 7, 9

[cf](https://en.wikibooks.org/wiki/LaTeX/Glossary#Changing_Glossary_Entry_Presentation_Using_Glossary_Styles)

But this minor issue aside, once more I'm happy with the features that asciidoc does provide which markdown does not.

**Comment by graphitefriction** [comment]
> horizontal should be an option (or a role), not a style.

We will bring this suggestion to the AsciiDoc language project.

When using Asciidoctor PDF, if you want a horizontal dlist, add the style `horizontal`.
