### ISSUE TITLE
Include docinfo in PDF output

### ISSUE THREAD

**Issue by vthib** [asciidoctor/asciidoctor-pdf#1015]
I apologize if this already has been mentioned, I could not find details about this anywhere.

We have started using asciidoctor-pdf to generate PDF from our adoc files and it works really well. The only difference that we now have between the output of asciidoctor-pdf and the previous generation using (asciidoc => XML + dblatex => PDF) is the inclusion of the docinfo file.

We use it to include licence information and versioning. We could probably do away with versioning, but we need to have the licence in every documentation generated. It is static, so I can generate it once and splice it in every PDF output if needed, but the best solution would be to support the docinfo file natively of course.

Is there a plan to include the support of the docinfo file in the (near) future? If not, do you fathom it to be a rather simple feature to implement? I don't have much experience with asciidoctor or prawn, but if it is simple, I could try to do a PR for it

**Comment by mojavelinux** [comment]
docinfo is designed for text-based output formats like HTML and XML. It's simply not going to work for Asciidoctor PDF since it has to construct PDF objects as the document is converted. It would be very difficult to implement.

One possible solution for your case is to use a TreeProcessor to add additional elements to the top of the document tree. Those nodes would then get converted to PDF.

Here's how you can add a simple paragraph to the top of the content for demonstration:

```
Asciidoctor::Extensions.register do
  tree_processor do
    process do |doc|
      doc.blocks.insert 0, (create_paragraph doc, 'inserted paragraph', {})
      nil
    end
  end
end
```

For more details about extensions, see https://asciidoctor.org/docs/user-manual/#tree-processor-example.

**Comment by mojavelinux** [comment]
Having thought about this a little bit more, I could see the possibility of supporting docinfo extensions in the PDF converter. The contract would be slightly different, and they would only work for PDF, but we could at least expose the hook. The return value from the docinfo processor would be ignored since the assumption would be that the converter would be manipulated by the processor (effectively writing directly to the PDF document).

**Comment by vthib** [comment]
Thank you for the wrap-up. I actually did end up writing an extension to include the licence in its own page:

```ruby
module AsciidoctorPdfExtensions
    @@licence_contents = [..., ...]

    def layout_title_page doc
        super

        start_new_page

        theme_font :heading, level: 2 do
            layout_heading 'Licence'
        end

        indent 30 do
            @@licence_contents.each do |c|
                layout_prose c
            end
        end
    end
end
```

It is very crude but it works fine in our docs afaict. I can see how an extension could be written to handle the docinfo file and directly write in the PDF document. However, the main issue was for us the legal notice, which a simple extension handles; as for the rest of the docinfo, we do not necessarily need it.

For me, you can close the ticket if you want to, although it is still to the best of my knowledge a feature that could be expected by people used to have a docinfo file with each adoc file, but you know this best :)

**Comment by mojavelinux** [comment]
Thanks for sharing. You definitely could have written that extension as a TreeProcessor, which would make it more stable (and themeable) since it doesn't use low-level APIs. I would recommend going in that direction.

**Comment by vthib** [comment]
I had written this before your comment about tree processors, but I'll definitely look into rewriting this, thanks!

**Comment by mojavelinux** [comment]
If you need assistance, don't hesitate to ask. You also might find gitter.im/asciidoctor/asciidoctor a helpful resource.

**Comment by mojavelinux** [comment]
I have added an example to the docs that shows how to do this.
