### ISSUE TITLE
Wrong footnotes generated

### ISSUE THREAD

**Issue by nhanngo** [asciidoctor/asciidoctor-pdf#1047]
When I use footnote in [quote], I got footnotes generated twice at the end of chapter and the index started from [2] , not [1].  This should be considered as bug. 

Here is sample code:
~~~~
= Love story
Mr.Bean
v1.0, November 1, 1980

== The old man
=== Dog named Boo

[quote]
I do not want to say anything here until I got fixed
footnote:[some book to be refered to, pp. 217-218]
~~~~ 
[test.pdf](https://github.com/asciidoctor/asciidoctor-pdf/files/3125941/test.pdf)

**Comment by mojavelinux** [comment]
This happens because the footnotes get recorded during the dry run and again during the print run. The solution, however, turns out to be rather complex. We have to know when we enter and leave the dry run so the document state can be restored. I'm still trying to work out how to do that in the existing design.

**Comment by mojavelinux** [comment]
...I think I have a solution.
