### ISSUE TITLE
Fillable PDF input fields?

### ISSUE THREAD

**Issue by gkroon** [asciidoctor/asciidoctor-pdf#1062]
Hi all,

I think t would be great to define (asciidoctor-pdf specific) input fields.

We all probably know we can add input fields to PDFs using Adobe software, and it's very convenient to provide people a fillable PDF form in which they can only fill in the input fields. Is this an accepted standard which is understood by most PDF viewers? It would be great to add this feature if so. :-)

**Comment by mojavelinux** [comment]
This is not something that's within the scope of Asciidoctor PDF (and, to be honest, not really in the scope of AsciiDoc either). If you'd like to do something like this, you could either create a custom inline macro or try to extend the converter.

**Comment by gkroon** [comment]
Thanks for your quick response, @mojavelinux. I'm working on getting prawn-forms to work with asciidoctor-pdf, but I'm stuck at expressing the inline macro. The following works by just using Ruby:
```ruby
require 'prawn'
require 'prawn/forms'

Prawn::Document.generate "form.pdf" do |pdf|
  pdf.text_field("fname", 100, 560, 200, 16)
end
```

The above generates a plain PDF file, with only a simple input field, which is what I want to pass in my AsciiDoc file . I have added `pass:[pdf.text_field("fname", 100, 560, 200, 16)]` in my AsciiDoc file, but when using `asciidoctor-pdf -r prawn/forms -o form.pdf form.adoc`, it just echo's the line as-is. How can I pass this through?

**Comment by mojavelinux** [comment]
You're understanding of the pass macro is incorrect. It does not execute code. It passes text through unprocessed (i.e., raw).

To integrate Prawn Forms, you need to use a proper extension. You can execute custom code in an extension.

Here's an example of a block text field macro.

```rb
require 'prawn/forms'
Prawn::Core = PDF::Core

Asciidoctor::Extensions.register do
  block_macro :text_field do
    resolve_attributes 'width=200', 'height=16'
    process do |parent, target, attrs|
      block_attrs = {
        'width' => attrs['width'].to_f,
        'height' => attrs['height'].to_f
      }
      block = create_open_block parent, [], block_attrs
      block.define_singleton_method :convert do
        pdf = self.document.converter
        theme = pdf.instance_variable_get :@theme
        pdf.text_field target, 0, pdf.cursor, (attr 'width'), (attr 'height')
        pdf.move_down (attr 'height') + theme.block_margin_bottom
        nil
      end
      block
    end
  end
end
```

(The reason we have to override the `convert` method is so the code executes in the conversion phase, when the PDF is being built).

Here's a sample document this extension would process:

```
before

text_field::fname[200,16]

after
```

Making an inline field would be trickier since inline elements are first converted to pseudo-HTML, which is then parsed and laid out by Prawn's text formatter. So you'll have to get a lot more low-level and into the internals of Asciidoctor PDF to make that work.

**Comment by gkroon** [comment]
@mojavelinux, many thanks! Your solution works perfectly, and thanks for explaining my misunderstanding. Should I submit a pull request to https://github.com/asciidoctor/asciidoctor-extensions-lab with your example?

**Comment by mojavelinux** [comment]
Glad to assist. And sure thing, that would be a nice addition to the lab!

**Comment by gkroon** [comment]
I'll close this one, but feel free to reopen if needed.
