### ISSUE TITLE
Possibility to change pagenumber-style within a document

### ISSUE THREAD

**Issue by fschanz** [asciidoctor/asciidoctor-pdf#1069]
Hello, iam trying to get in my printed pdf  (appendix-)pages without pagenumbering or with roman numerals. 
Like this:
Front matters: get roman numerals
Content1..5 pages: get arabic numerals
content6 or appendix: get no pagenumbers or also roman numerals 

Or is there a possibility to uncheck the :pagenums: attribute for some chapters/apppendixes ??

Thanks a lot for develop and supporting  asciidoc/ asciidoc-pdf!

**Comment by mojavelinux** [comment]
Thanks!

As of the last release of Asciidoctor PDF, the front matter pages will automatically be labeled with roman numeral page numbers if the running content is configured to start on those pages. See running_content_start_at in the theming guide.

It's not possible to turn on and off page numbers as the document goes on. However, there is a discussion about disabling the running content on certain pages. See #232.

**Comment by mojavelinux** [comment]
We're not going to change how page numbering is done because it's already incredibly complicated. If you need that control, you can extend the converter and hack it to do what you want it to do. https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#extending-the-converter
