### ISSUE TITLE
Display Footnotes at bottom of page instead of end of chapter or document

### ISSUE THREAD

**Issue by NokiDev** [asciidoctor/asciidoctor-pdf#1086]
Hi, I re-create a quite old issue, but still seems unfixed, or at least not handled correctly.
and it seems that there is no actual open issue pointing that out.

Actually : 
if doctype is a book footnotes are rendered, at the end of the chapter
if doctype is an article footnotes are rendered at the end of the document

But footnotes in a book, or an article with pdf format should be displayed at the bottom of the page, or should be configurable.

I tried to, modify the code, but I lack ruby xp, + I have no idea how the 3k + converter works.
And don't really have time to put into ... 

That said, I'll try to explain what I wanted to do, to make them work correctly with a probably naive approach since I don't how it really work.

So, my idea was to have another cursor (or the same that move), that write from the bottom of the page the footnotes when encountering one in text. 
When the footnote is rendered, we know it's size, and are able to go back to writing the text, or start a new page. 

The 'only' problem I see with this approach, is when the footnote is so long that the text with the actual footnote, gets overlapped. But that shouldn't happen, it more like an extreme case (checking how the fopub project handle this might be useful).
+ We can probably limit the size footnotes block can take on a page, like max 30 - 40%

**Comment by mojavelinux** [comment]
I implemented it the way I did for a reason. I thought about this problem for years and I cannot figure out a way to put the footnote at the bottom of the page using Prawn. The problem is that Prawn just doesn't provide the introspection necessary to compute where content will fall on the page without a lot of trials. 

I will not put time into implementing footnotes any other way in Asciidoctor PDF. If someone comes forward with a PR that successfully implements putting footnotes at the bottom of the page, and it doesn't add an unreasonable amount of overhead, I will consider merging it in.

**Comment by NokiDev** [comment]
I'm sure about that. I was so disappointed not to see an issue, pointing it anymore... 
Thanks for the highlights @mojavelinux ! 
So the problem seems to be in the Prawn library. Might be useful to look into it so but you probably already did, and it didn't end well. 

Use browser for pdf rendering might be the appropriate solution for this use case.
I know that [Relaxed project](https://github.com/RelaxedJS/ReLaXed) use this to render a pdf and it works pretty well.

Hoping you'll achieve this in the future Asciidoctor-pdf version with browser rendering. 

Thanks for your fast response.

**Comment by mojavelinux** [comment]
In Prawn, you can't move text once it is rendered. That's the main issue. This is not true of HTML, which is why I'm hopeful that platform will give us the ability to solve more advanced layout problems such as this one.

One workaround we've used with Prawn is to render an element to a scratch document to determine how much space it takes up. However, even that requires rendering an element (or several) multiple times, which has side effects. And doing footnotes this way would cause an immense amount of side effects.

**Comment by jimisola** [comment]
Just want to confirm that this issue has not been resolved later on as I'm experiencing the end-of-pdf  style footnotes.

**Comment by wallabra** [comment]
Would it be possible to use the HTML to render the PDF instead?
