### ISSUE TITLE
Header string font color not applied

### ISSUE THREAD

**Issue by andraz-kozelj** [asciidoctor/asciidoctor-pdf#1147]
I have a title page and TOC. On second body page instead of "header-font-color" for header string, a different color is used - #939393, than back to correct one, and again the other. Seems like random pattern, but always the same for same document.

Using 1.5.0.beta.1

**Comment by mojavelinux** [comment]
Please provide a reproducible example, either as a git repository, a test case, or the repository where this is happening.

**Comment by mojavelinux** [comment]
One thing you could do is explain how to reproduce it on the chronicles example.

**Comment by andraz-kozelj** [comment]
Download content from this link: http://k00.fr/1ipsoaob
It also contains the PDF generated. Run build.sh, to see the parameters used.

Could not reproduce it using the chronicles example.

**Comment by mojavelinux** [comment]
Thanks! I'll have a look.

**Comment by mojavelinux** [comment]
Is the background supposed to be applying on every other page? If not, that could be the same issue as #1144.

**Comment by andraz-kozelj** [comment]
It is not supposed to do that, it's only a title page background. Yes, #1144 is the correct one, I've seen it so I did not report it again.

It seems to me that the header string font color is wrong on the recto pages following the TOC, but are correct again once a couple of pages - no idea what is the actual pattern.

**Comment by mojavelinux** [comment]
Okay, I see what's going on. It actually doesn't have to do with the running content, at least not directly. The colors in your theme are not being parsed correctly (which I need to look into), so you are ending up with a base font color that is nil. This leads to a corrupt PDF. So the fact that the font is randomly the wrong color has more to do with a broken stream than an actual application of the font. The font color just isn't taking on certain pages depending on what else was written and in what order.

You can quickly fix this problem by switching from the `darkblue: #035693` style to the `darkblue: '035693'` style. I would also rename better_color_font to better_color_base since "font" has special meaning.

**Comment by mojavelinux** [comment]
I'll follow-up once I figure out why the colors are ending up as nil as your theme is currently written. (It could come down to a docs issue, but we'll see).

**Comment by mojavelinux** [comment]
Aha! The color parsing is case sensitive. It's only looking for lowercase letters in the hex value. Doh! I'll get that fixed for beta.2. That should solve your problem.

I also think Asciidoctor PDF should set a default font color if the theme doesn't set it for some reason to avoid creating a corrupt PDF file. I'll fix that as well.

**Comment by mojavelinux** [comment]
I think I found yet another cause. When the font-color is set on the dot-leader in the toc, it's resetting the font color somehow. This only happens when the base font color is nil, which still seems to be the root issue.
