### ISSUE TITLE
include:: drops h1 content after first two includes

### ISSUE THREAD

**Issue by rosieyohannan** [asciidoctor/asciidoctor-pdf#1156]
Example repo here: https://github.com/rosieyohannan/circleci-docs/tree/server/tranfer-content
`ops-guide.adoc` contains several `include::` statements to create a master PDF doc containing many topics written in other `.adoc` files.

When I generate the PDF using this command: `asciidoctor-pdf -a pdf-style=release-pdf/circle-theme.yml -a pdf-fontsdir=release-pdf/fonts ops-guide.adoc` the h1 level content is being dropped for all files after the first two includes.

e.g. the 3rd include is `jekyll/_cci2/monitoring.adoc` and only the content after the first h2 level heading is being included. 
The first part (below) is being skipped:

```
= Monitoring Your Installation
:page-layout: classic-docs
:icons: font

This section includes information for System Administrators on the following:

* Scaling your cluster
* Gathering metrics for monitoring your CircleCI installation
```

 

Any ideas what's going on?

I've tried testing this by moving the order of the sections around but it's always the h1 heading plus content before the first h2 heading that gets chopped out for whichever topics I put in 3rd place and below in the list of `include::` statements...

**Comment by rosieyohannan** [comment]
Just to update, it seems the h1 level content is being rendered to PDF for *some* of the `include::` asciidoc files, not just the first two. At my last commit I have 7 files included and files 1,2 and 5 are rendered fully, and the rest are missing their first sections.

**Comment by mojavelinux** [comment]
I'll try to have a look at this to see what's going on in the next day or so.

**Comment by rosieyohannan** [comment]
I have solved this problem at my end by inserting a line break between each `include::` Not sure if this still counts as a bug though? Its working though so woooop!

<img width="552" alt="Screenshot 2019-07-23 at 11 08 28" src="https://user-images.githubusercontent.com/24589403/61703824-522e8680-ad3a-11e9-8fe3-a12475603a77.png">

**Comment by mojavelinux** [comment]
That's exactly the right solution. The include directive combines files together without considering the document structure. If the file you're including ends with a paragraph and the next one starts with a section title, the section title will become part of that paragraph (since there is no leading blank line). (Just like it would if you entered it that way in a single document).

Therefore, it's always safe to put blank lines between your includes unless you are intentionally trying to make the lines touch (like in a source listing).

You can read more about this here: https://github.com/asciidoctor/asciidoctor/issues/318

**Comment by mojavelinux** [comment]
I've made this point more clear in the documentation. See https://asciidoctor.org/docs/user-manual/#include-partitioning
