### ISSUE TITLE
Numbered steps alignment off

### ISSUE THREAD

**Issue by rosieyohannan** [asciidoctor/asciidoctor-pdf#1179]
This is a weird one, but sometimes I'm finding numbered steps are out of alignment and appear too high. Just wondering if this is a known problem or something to do with my setup. Screenshot as example:

<img width="721" alt="Screenshot 2019-07-30 at 14 48 42" src="https://user-images.githubusercontent.com/24589403/62135006-5d088e80-b2d9-11e9-81c8-6d73f6d6f29f.png">

**Comment by mojavelinux** [comment]
Are you using a custom PDF theme or the default one? If you're using a custom one, could you share a link to the theme file?

**Comment by rosieyohannan** [comment]
Ah yes I'm using a custom theme, here's a link: release-pdf/circle-theme.yml Thanks!

**Comment by mojavelinux** [comment]
In that case, it could have to do with how you are setting the line height / line height length.

I'd test it out, except that's not a link ;)

**Comment by rosieyohannan** [comment]
haha oh no! Sorry! here: https://github.com/rosieyohannan/circleci-docs/blob/server/tranfer-content/release-pdf/circle-theme.yml

**Comment by mojavelinux** [comment]
Excellent. I'll investigate.

**Comment by mojavelinux** [comment]
Roboto Mono has a larger implicit line height than Lato. That means you need to reduce the font size of Roboto Mono (used for inline code) so that it doesn't impact the height of the line.

You can do this by adding the following property to your theme:

```
literal:
  font_size: 0.8em
```

I suppose a case could be made that an inline element such as a monospaced phrase should not affect the height of the line. However, I'm not sure if Prawn supports that option.

**Comment by rosieyohannan** [comment]
@mojavelinux Thank you so much for your help, that makes total sense :-)

**Comment by rosieyohannan** [comment]
Works perfectly now, thanks again!
