### ISSUE TITLE
How to generate small caps?

### ISSUE THREAD

**Issue by aggsol** [asciidoctor/asciidoctor-pdf#1192]
How can I get small caps into the PDF? For HTML I just added ` font-variant: small-caps;` to the css and I use a custom attribute `[.smallcaps]#In small caps#`. How can I get small caps in PDF.

**Comment by mojavelinux** [comment]
Small caps are not possible. You can use text-transform to get uppercase, but that's the extent of the font variant that Asciidoctor PDF supports.

**Comment by mojavelinux** [comment]
I would imagine this would require reading information from the font library (ttfunk), which would require support from Prawn.

**Comment by mojavelinux** [comment]
I now understand that the small caps variant / transformation is actually a glyph replacement. While this can be handled by the font, most text processors do this by replacing lowercase latin letter with the small capital equivalent. For example, `a` becomes `ᴀ`, and so forth. We can easily handle this transformation using the existing text transform mechanism.

Part of this change includes adding all the small capital glyphs we need to the built-in fonts. That way, this transformation can be used out of the box. In doing so, I  had to make a few substitutions.

* use more widely-supported ғ instead of ꜰ as replacement for F
* use more widely-supported ǫ instead of ꞯ as replacement for Q
* use more widely-supported s (lowercase latin "s") instead of ꜱ as replacement for S
* in small caps, x (lowercase latin "x") remains unchanged

Aside from those exceptions, this works as expected by setting the `text-transform` key to `smallcaps` somewhere in the theme.

```yml
role:
  smallcaps:
    text-transform: smallcaps
```

**Comment by mcp292** [comment]
Happy to see this was added! Has the mainsite documentation been updated to demonstrate use?

Based on this thread, I have added this to my theme:
```yml
role:
  smallcaps:
    text-transform: smallcaps
```

and try to use it with:
```
[.smallcaps]#This is a test.#
```

It does not work.

**Comment by mojavelinux** [comment]
Yes, it was implemented. If you are having difficulty using the feature, please ask follow-up questions in the project chat at https://chat.asciidoctor.org. Thanks!
