### ISSUE TITLE
Add TOC entry when image::[] macro targets a PDF

### ISSUE THREAD

**Issue by nuket** [asciidoctor/asciidoctor-pdf#1213]
Similar to what I've mentioned in https://github.com/asciidoctor/asciidoctor/issues/3388, the idea would be to have a way to add a TOC entry and jump target to the top of the newly-included PDF page. 

As these single-page includes often will be full-bleed Chapter titles or other custom cover pages for sections of a document, this would be a very useful addition...

**Comment by mojavelinux** [comment]
That's a cool idea. I would suggest that if the image macro has an ID and reftext (or title?), then it could become an entry in the toc. We would essentially be treating it like a section. It's going to be a little difficult because of how sections are discovered, but I think using the AbstractNode#find method instead, we may be able to find a way to make it work.

This would only apply to the image macro when the target is a PDF. I suggest updating the subject of the issue to reflect that.

**Comment by nuket** [comment]
That makes sense to me, id + reftext. 

I'm not sure about title... I use that a ton w/normal images, but those get turned into figure captions. I'm not sure that quite conveys the explicit intent of wanting a TOC entry.

**Comment by mojavelinux** [comment]
I wasn't suggesting that the title be used for a figure caption. Instead, it would be repurposed. But while thinking that, I realized that it would still throw off the figure numbering, since the assignment happens during parsing. Thus, I think reftext is the best approach here.

**Comment by mojavelinux** [comment]
I gave this some more thought and I realized that there's a flaw in my proposal. The issue is that the only way to control the level of blocks in an AsciiDoc document is by using sections. In other words, an image macro is always a child of a section, and therefore so is the imported PDF page. It would then show up as a child entry in the TOC. That's probably not the desired behavior. It also means change *a lot* of logic to support non-section blocks in the TOC, which I'd like to avoid right now (as it only opens a slew of other questions).

Fortunately, there's a better solution available. Starting in Asciidoctor PDF 2, you can mark the title of a section as hidden using the `notitle` option. For example:

```
[%notitle]
== Reference Text Only

Content of section.
```

The section is still referenceable and it still shows up in the TOC. The title is just hidden in the document (meaning it does not take up space). We can leverage this capability to insert a PDF page at this location. If the imported page replaces the current page, the anchor of the hidden section title will be restored on that page.

```
[%notitle]
== Reference Card

image::reference-card.pdf[]
```

(If the hidden section title is not a part or a chapter, you may want to add a manual page break above it to ensure the anchor points to the imported page).

Using this approach, you can insert an entry for an imported PDF page anywhere in the TOC hierarchy.
