### ISSUE TITLE
text background color for custom inline roles

### ISSUE THREAD

**Issue by voulgarakis** [asciidoctor/asciidoctor-pdf#1223]
Is it possible to change text background color in asciidoctor-pdf?

**Comment by mojavelinux** [comment]
Not to arbitrary text. The inline role doesn't yet support applying background color or border. You can define a background color for known elements such as inline code (literal), button, and kbd.

**Comment by voulgarakis** [comment]
this works fine for text color
+++<span style="color: #FF0000">test font color</span>+++ 
but this one doesn't change background color in pdf
+++<span style="background-color: #00FF00">test backcolor </span>+++ 
both work fine in HTML

**Comment by mojavelinux** [comment]
That's because the technology for styling in Asciidoctor PDF is very different than HTML and also very complex. Painting a background requires a callback function to run before the text is inked.

I do believe in a limited capacity, we can support this in the same way that we support the background color for literal, button, and kbd. There will likely be edge cases, but it should work for typical usage.

**Comment by mojavelinux** [comment]
> this one doesn't change background color in pdf `+++<span style="background-color: #00FF00">test backcolor </span>+++`

I don't want to support that approach because I do not want to encourage using raw HTML in AsciiDoc.

How we would support is is through the use of roles. See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#keys-role
