### ISSUE TITLE
Formatting of section titles not applied in toc

### ISSUE THREAD

**Issue by weph** [asciidoctor/asciidoctor-pdf#1247]
I noticed that formatted section titles are also formatted in the toc with asciidoctor but are not with asciidoctor-pdf. I guess it's debatable whether this is a good or a bad thing but for my purposes it really comes in handy having a colored toc.

*test.adoc*
```
= Test
:toc:
:pdf-theme: test
:pdf-themesdir: ./

== [.red]#Red Title#

[.red]#Red text#
```

*test-theme.yml*
```
role:
    red:
        font-color: #ff0000
```

*test.html*
![Bildschirmfoto 2019-09-01 um 18 15 02](https://user-images.githubusercontent.com/1123079/64079305-56a97000-cce6-11e9-85a9-dc3f3ac9ff13.png)

*test.pdf*
![Bildschirmfoto 2019-09-01 um 18 15 09](https://user-images.githubusercontent.com/1123079/64079310-632dc880-cce6-11e9-9cc6-dfb226780e22.png)

**Comment by mojavelinux** [comment]
This is already the case. The reason it doesn't work, however, is because of #1219. Custom styles are being passed in the wrong direction. Since a default color is assigned to the table of contents entries, it ends up overwritingn the color of the title.

I may be able to get it to work, though. I'm going to try something.

**Comment by mojavelinux** [comment]
Actually, it looks like there was a bug after all.

**Comment by weph** [comment]
It's my pleasure. There's more to come ^^
