### ISSUE TITLE
:front-cover-image: scaling changed dramatically between alpha18 and beta4/beta5

### ISSUE THREAD

**Issue by heckj** [asciidoctor/asciidoctor-pdf#1275]
I have a pre-scaled PNG image for the PDF (and ePub) rendering, and upon testing an update to using asciidoctor-pdf beta4 (was previously on alpha.18), the image is either isn't scaled and now I'm seeing a small subsection, or the scaling logic changed significantly.

The PNG I created is 2560x1920 pixels and worked perfectly with alpha.18 - is there a different expected size that's recommended with beta.4 and later?

alpha.18 rendered image:

<img width="337" alt="Screen Shot 2019-09-16 at 11 33 41 AM" src="https://user-images.githubusercontent.com/43388/64983683-e79b5200-d875-11e9-823a-77273e6f0c21.png">

beta.4 rendered image:

<img width="326" alt="Screen Shot 2019-09-16 at 11 32 41 AM" src="https://user-images.githubusercontent.com/43388/64983689-ec600600-d875-11e9-8ad9-28067ecbf29b.png">

The configuration is in https://raw.githubusercontent.com/heckj/swiftui-notes/master/docs/using-combine-book.adoc:

```
:imagesdir: images
:front-cover-image: image:UsingCombineWithSwiftCoverArt_2560x1920.png[Using Combine,2560,1920]
```

should I instead be using something like:

```
:front-cover-image: image:UsingCombineWithSwiftCoverArt_2560x1920.png[fit=cover]
```

**Comment by mojavelinux** [comment]
You're correct that the behavior changed (rather drastically) after the last alpha release. The processing of all images was normalized, because before it was very inconsistent.

In particular, you're looking for change introduced to resolve #1134. The front cover image is no longer scaled by default. It will use the size you specify (or the intrinsic size if no size is specified). In your case, it's trying to make the image 1920 pixels wide, which is much wider than your page.

To restore the previous behavior, you'll want to add `fit=cover` to the image declaration. Technically, that's not *exactly* the same since the previous logic was stretching the image. But very likely you don't want to distort the image, so `fit=cover` will give you the best result.

A case could be made, I suppose, that fit=cover should be the default for a cover image if the fit attribute is not specified. wdyt?

**Comment by heckj** [comment]
I switched the description to explicitly use `fit=cover`, and I think that's a useful default. It would be hugely beneficial to have this nugget in the docs for how to provide a cover image as well - I think I got my original setup from prowling forums - so at least some anecdotal information is falling a bit out of date.

I'd be happy to take a stab at adding this detail into relevant documentation - would it be in this repository (which seems to be primarily a theming guide), or better placed into github.com/asciidoctor/asciidoctor?

**Comment by mojavelinux** [comment]
Let's go ahead and make `fit=cover` the default for cover page images. It's logical since they are called "cover images" after all ;) This can be reverted by setting `fit=none`. This will need to be documented. Since I need to make a code change, I'll make an update to the docs, which I'll have you then review.

**Comment by mojavelinux** [comment]
As it turns out, the previous behavior was `fit=fill`, which wasn't even implemented yet. So I opened an issue (#1276). However, I don't think that makes a good default since it distorts the image.

If fit is not specified, here are the possible defaults we could use:

* none - use the specified width, otherwise the intrinsic width
* contain - scale the image up or down to fit within the boundaries of the page
* cover - scale the image up or down until it covers the page completely (overlapping the boundary if necessary)
* scale-down - scale down the image to fit within the boundaries of the page if it were to exceed the boundaries of the page (like contain, but only scale down)

I think we should make it `contain` as a sane default and to match closest with what was implemented in earlier versions. You can always specify the `fit` value if you want something else.
