### ISSUE TITLE
support doc.attr/@theme fallback

### ISSUE THREAD

**Issue by rmannibucau** [asciidoctor/asciidoctor-pdf#131]
Would be great to support overriding all @theme config through doc attribute or the opposite.

A simple conversion would be attribute_name.replace('-', '_') to get the theme key.

Then is attributes are read before theme it allows to override a theme config pretty easily.

**Comment by mojavelinux** [comment]
I like this idea.

However, before we solve this issue, I think we need to address the real underlying problem in the theme system, which is the fact that we don't load a base theme. I've opened issue #132 to address that problem.

As for this issue, I think we should namespace the attribute keys by prefixing the name with something like `theme-` (or `pdf-theme-`).

For instance, lets say we are changing the primary color. You'd set something like:

```
:theme-brand_primary_color: #F00000
```

I'm open to running the attribute name through `.tr('-', '_')` so you can write it either with underscore (as above) or hyphen (`theme-brand-primary-color`).

It's important to note that this is not the preferred way to set theme settings. It would be something that you use for a short-term or isolated change. We really want to encourage use of the theme system...and of course make it easier as planned in #132.

**Comment by rmannibucau** [comment]
well why I ask: I have a custom theme but I want to change for all documents - ie by document - 2 things (let say the cover and a text somewhere). Creating a new theme for it doesnt make much sense since these configs really belongs to the doc and avoid to have a new file for finally 2 lines - but needingatlest the double cause of the additional config.

That said I agree a real theming is better. That said I wouldnt continue with the yaml way but I'd rather propose a ruby DSL the converter would call. Nice thing with this solution is it could also be considered as an extension also and simply override some parts if needed after having done the config - but that's another topic ;).

**Comment by mojavelinux** [comment]
> Creating a new theme for it doesnt make much sense since these configs really belongs to the doc

You've nailed it. It's important to think about what is content and what is styling. Content, such as the cover image, definitely belongs in the document.

> That said I wouldnt continue with the yaml way but I'd rather propose a ruby DSL the converter would call. 

The YAML way is important for non-developers (or even less adventurous developers used to a different language). With that said, I like the idea of having the choice to use a DSL-based approach to theming. In other words, we want to make sure the theming is pluggable.

**Comment by rmannibucau** [comment]
well if the dsl is nice enough, dsl or yaml is 1-1 but most of customizers (ie not only few colors) will need hook. Merging yml and extension "place" is a key to make it adoptable IMO.

**Comment by mojavelinux** [comment]
> most of customizers (ie not only few colors) will need hook

I want to first emphasize that I'm not opposed to hooks. I'm all about hooks & extensions. But a lot of the reasons you need a hook now is because the theme engine needs to be fixed / improved. You shouldn't need a lot of hooks (just like what CSS gives us). We should think about the DSL like we think about JavaScript in HTML. We use it when CSS doesn't provide a way of expressing something...or it is very dependent on the content or context.

**Comment by mojavelinux** [comment]
>  You shouldn't need a lot of hooks 

That's my goal at least :)

**Comment by rmannibucau** [comment]
Then the only way is to generate for each item an "id", some "classes" (h, h1, title,  text) and a "hook". Item being a text/block or a whole page (positions/alignment on the cover is something anybody will want to customize) - in this last case we'd just plug the hook and relpace existing code.

Then yml is useless and we can use css avoiding to introduce a new format.

**Comment by mojavelinux** [comment]
On a tangential note, I wanted to clarify that I think it should be possible to pass a theme provider to the API so that you can define the keys however you want. Inside of Asciidoctor PDF, it just needs this theme map. How it gets that theme map it shouldn't care about.

**Comment by mojavelinux** [comment]
...and if it doesn't get a theme map, it will load one.

**Comment by DavidGamba** [comment]
> I'd rather propose a ruby DSL the converter would call.
Lots of people use asciidoctor from java and one of the things asciidoctor did was to remove the ability to eval python code from the `ifeval` condition. That disconnects the asciidoc markup spec from the underlying implementation language. When building using the API it is ok to call ruby specific stuff but the user facing implementation, i.e. the asciidoctor command, should use something generic like yaml, css, json, etc.

**Comment by rmannibucau** [comment]
well that's really a good question. Even if I get the comment I'm nto yet sure having a complete config is better than having just simple hooks in main languages (I also use java rather than ruby). Typically for my needs coding the theme is far easier and faster than configuring it (cause it needs a lot of knowledge of the default generation + a *new* language which is the proposed configuration). Making the configuration some code is very nice in practise and possible today in most languages (including java).

**Comment by mojavelinux** [comment]
@DavidGamba I'm pretty sure Romain is talking about code for handling the PDF layout, not something that goes in the AsciiDoc source. Basically, hooks into the converter itself.

I see two things here:

1. A custom theme provider / loader that allows a developer to feed the converter with a theme map using an alternative mechanism
2. Hooks into the layout handlers themselves

The converter doesn't really care how it gets the theme map, so long as it can invoke `@theme.base_font_size`, for instance, and get a value. So that's where I see (1) coming into play.

For (2), this is already possible to some degree. You can override any method in the converter using monkeypatching and you can control the layout in your own Ruby code. (See https://github.com/opendevise/editions/blob/master/lib/editions/pdf_extensions.rb). But that's an ugly extension mechanism atm.

What we should do instead is make it something more formal, similar to how we provide a custom handler for the outline in the html5 backend. (See https://github.com/asciidoctor/asciidoctor-backends/blob/master/slim/html5/block_toc.html.slim#L8). That way, changes to converter implementation don't break the extensions. In other words, we need more well-defined extension points...and that means settling on an API. A great place to start is `layout_title_page`.

**Comment by rmannibucau** [comment]
trying to summarize the open points  I have:

- which format for themes, think we could reuse css really - why not using https://github.com/premailer/css_parser?
- how to have a theme chain? typically 1) base theme, 2) sub theme, 3) some overrides for the documents (can be attributes)
- how to handle resources, typically an image defined in the theme should be resolved to a different imagesdir than the images of the doc (I'm thinking to the theme = theme config + resources) as a bundle you can share
- do we want to simply normalize parts of the documents (title = h1, subtitle = h2, section title = h3?...) or do we want to make it customizable (not yet sure it is needed, a theme post processor could avoid the need of this NameStrategy API)?
- what do we define as extension API. Simple start can be to define blocks (title page, section, paragraph, code block, ..., last page) and all extension points should get the tree context (a paragrah needs the section and the document). Hard part is when you are no more linear. For that a adoc (not adoc-pdf) document pre-processor (pre compared to rendering) could be useful. Its goal would be to make the doc linear if it is not in the source.


wdyt?

**Comment by mojavelinux** [comment]
> which format for themes, think we could reuse css really - why not using https://github.com/premailer/css_parser?

I want to clarify that while we're shooting for something that is CSS-like, we are definitely not trying to mimic CSS directly. There are several reasons:

* It would be misleading since we can only support a very limited set of things
* CSS has no support for variables, so it's very un-DRY
* We need properties that CSS doesn't have

What we're creating is something more like Sass. I took inspiration from the Bootstrap and Foundation Sass files for some of the current design.

...having said that, it's not completely unreasonable to be able to use the Sass syntax instead of YAML. But we'd have to be very clear that we are cherry-picking information out of it and not just applying it to the canvas (as that would be impossible).

**Comment by mojavelinux** [comment]
> how to have a theme chain?

First, we definitely want to solve #132 before anything else. That at least makes themes much simpler as they only have to specify the delta from the base theme.

We could then parse the `pdf-style` as a comma-separated list and load the themes in sequence. We're also considering overriding theme values from AsciiDoc attributes in the header (perhaps prefixed with `theme-` or `pdf-theme-`).

**Comment by mojavelinux** [comment]
> how to handle resources

When we resolve images, esp in the theme, we should resolve them on the LOAD_PATH. This is similar to the classpath in Java. We could also look inside the `pdf-stylesdir` I suppose.

**Comment by mojavelinux** [comment]
> what do we define as extension API. 

I think the key here is a delegation chain for well-defined callbacks such as `layout_title_page`. It's similar to how the CompositeConverter works in Asciidoctor core.

Of course, we could already use the TemplateConverter today if we changed how we delegate to the `layout_` methods (and maybe some tweaks to core).

**Comment by mojavelinux** [comment]
I tried out the idea of using templates to override methods in the PDF converter. As it turns out, Asciidoctor core doesn't use the template converter when a non-built-in converter is used. See https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/converter/factory.rb#L186. This should be an option of the converter because this would be useful. I'll fill an issue.

It's still possible to create a composite converter manually that loads the template converter. I tried that and it works. However, it's a bit tricky how we get access to the PDF object, so I'll need to think more about that. Anyway, it would be an interesting way to allow overrides of the PDF layout.

**Comment by mojavelinux** [comment]
Since Asciidoctor 2, my previous comment is obsolete.

**Comment by mojavelinux** [comment]
Now that it's easy to extend themes, I think that's the right solution. Putting theme information directly in the AsciiDoc file mixes content and presentation. Plus, not all theme keys can be expressed that way (as they require the structure that the YAML file provides). Therefore, I don't think I'm going to pursue this.
