### ISSUE TITLE
Spanning table columns can extend beyond the edge of the page

### ISSUE THREAD

**Issue by myii** [asciidoctor/asciidoctor-pdf#1368]
#### Related issue

May be a duplicate of #900.

#### Asciidoctor file

```adoc
= Bug: Spanning table columns

.Without spanning
[format="psv", cols="25d,25d,25d,25d"]
|===
|a |b |c |d
|===

.Using equal column sizes appears to work
[format="psv", cols="25d,25d,25d,25d"]
|===
// |a |b |c |d
|e 3+|f
2+|g |h |i
|===


.Adjusting column sizes slightly results in a larger table width
[format="psv", cols="24d,24d,24d,28d"]
|===
// |a |b |c |d
|e 3+|f
2+|g |h |i
|===

.Adjusting column sizes further results in the table extending to the edge of the page
[format="psv", cols="20d,20d,20d,40d"]
|===
// |a |b |c |d
|e 3+|f
2+|g |h |i
|===
```

* Note, if the commented row in each table is uncommented, this bug isn't triggered.
  - It doesn't have to be the first row; it works for any of the rows.

#### Theme

Using the default theme.

#### Command

```bash
$ asciidoctor-pdf bug_spanning-table-columns.adoc
```

#### Result

![screenshot102](https://user-images.githubusercontent.com/10231489/68221101-cf77c180-ffe0-11e9-864e-5cee8b679a5a.png)

**Comment by mojavelinux** [comment]
The problem here is when there isn't at least one row that has cells without colspans. That seems to throw off the calculation for the individual column widths.

**Comment by mojavelinux** [comment]
Keep in mind that the column widths are ratios. So they don't have to add up to 100. Though, clearly the computed widths do need to add up to the available space.

**Comment by mojavelinux** [comment]
Here's the most minimal case:

```
[cols=20;20;20;40]
|===
|e 3+|f
2+|g |h |i
|===
```

**Comment by mojavelinux** [comment]
It turns out, prawn-table is computing the width of the columns even when we pass it the precomputed column widths. (I have no idea why). And since there's clearly a bug in the column width calculation in certain scenarios when colspan is used, the table ends up with incorrect column widths that overrun the width of the page.

I'll update the converter to force prawn-table to use the column widths that we give it. While that doesn't fix the computation in prawn-table, it does sidestep it. What that means is that this could still happen if you set the `autowidth` option on the table. But the obvious workaround when this happens is to take away the `autowidth` option (since we can't rely on the prawn-table's calculations).

**Comment by mojavelinux** [comment]
It turns out that prawn-table does make this mistake when the `autowidth` option is specified. So this still works:

```
[.stretch%autowidth]
|===
|a 3+|b
2+|c |d >|e
|===
```

For all the cases I can come up with so far, this patch fixes the problem.
