### ISSUE TITLE
When toc::[] is used, the TOC gets a footer

### ISSUE THREAD

**Issue by Hextremist** [asciidoctor/asciidoctor-pdf#1378]
Not sure if this is intentional, but a footer with page numbers is used in the toc when custom placement is used.  I have not tocuhed   start_at key, so I guess it is body.  I would prefer for the page numbering to start after the TOC, even if the pages before can be defined as body.

**Comment by mojavelinux** [comment]
When the toc is placed manually, it is treated as a normal content page. That's unlikely to change.

We are talking about being able to control the offset of the page numbering within the body in #560. That would allow you to start the page numbering after the toc. (And we might do the same for the running content as well, if it works out).

**Comment by Hextremist** [comment]
Maybe, but whenever the TOC start using an extra page, the number has to be updated.  Maybe a better approach would be to handle it the ame way as toc::[], i.e. let you insert the page numbering start in the text somewhere, for instance using pagenumbers::[] or even pagenumbers::[start], pagenumbers::[stop], pagenumbers[start,roman] ...

**Comment by mojavelinux** [comment]
> Maybe, but whenever the TOC start using an extra page, the number has to be updated.

Good point. The problem is, we don't know where the toc will be until after we need to know the starting page number. So it's a chicken-egg problem. Thanks to the fix for #560, you at least have the ability to get the behavior you want, even if it means converting the document, then updating the setting in the theme and converting it again. (As you may know, most toolchains do it that way, albeit automatically, to handle situations like this).

**Comment by mojavelinux** [comment]
Here's what I propose. For a book that uses the toc macro, you can disable the running content (header and/or footer) on that page by setting the noheader and/or nofooter option on the toc macro.

```
[%noheader%nofooter]
toc::[]
```

This builds on the document-wide noheader and nofooter attributes, but only applies to the toc page.
