### ISSUE TITLE
Prawn::Errors::CannotFit on tables

### ISSUE THREAD

**Issue by DarkTrick** [asciidoctor/asciidoctor-pdf#1452]
The following code returns `Prawn::Errors::CannotFit`:

    [cols="1d,99"]
    |===

    | aaa
    | First one

    | bbbb
    | Second one

    |===

**Expected: **
The code above gets rendered properly, just like in html.

**Comment by mojavelinux** [comment]
This is a limitation of prawn-table which Asciidoctor PDF inherits. The resolved width of a column cannot be less than the width of a single character. If that happens, this error will be thrown. prawn-table will not resize the cell like in HTML. And since the error originates from Prawn::Table, there's really nothing we can do to prevent it. That's just the way Asciidoctor PDF works. This scenario is documented as a known limitation in the README.

**Comment by DarkTrick** [comment]
I didn't find this information on the internet. It would be very nice to have it within the error message. Maybe asciidoctor-pdf could sense the problem and print a understandable error message?

**Comment by mojavelinux** [comment]
The information can be found here: https://github.com/asciidoctor/asciidoctor-pdf#known-limitations

The error comes deep from within prawn-table and, unfortunately, we can't anticipate it. It's basically a bug in prawn-table. So no, there's nothing we can do other than document it.

**Comment by ghilainm** [comment]
@mojavelinux Is it possible to get the information on which table generated the issue?

**Comment by mojavelinux** [comment]
As I said in my previous comment, there is not.

In the future, please direct follow-up questions to the project chat at https://asciidoctor.zulipchat.com. Thanks!

**Comment by mojavelinux** [comment]
I'll update the README to call attention to this specific problem. I'll also follow-up in a separate issue to see if we can catch this exception and at least add what context we can add.

**Comment by ksperling-apple** [comment]
At least for the case of column percentage widths adding up to > 100%, asciidoctor could simply detect this itself, issue a warning (with a file / line number), and rescale the numbers to add to 100.

**Comment by mojavelinux** [comment]
Asciidoctor already does that. The issue is not the relative widths, it's when the content simply won't fit. And there's nothing Asciidoctor can do about that. The content has to be fixed.

In the future, please do not comment on long closed issues. If you want to provide feedback or discuss a topic, you can do so in the project chat at https://chat.asciidoctor.org.
