### ISSUE TITLE
Anchor links in plantuml diagram not working after PDF conversion

### ISSUE THREAD

**Issue by stephenwhittle** [asciidoctor/asciidoctor-pdf#1521]
> Asciidoctor PDF 1.5.0.rc.2 using Asciidoctor 2.0.10 [https://asciidoctor.org]
> 
> Runtime Environment (ruby 2.6.5p114 (2019-10-01 revision 67812) [x64-mingw32]) (lc:IBM437 fs:Windows-1252 in:IBM437 ex:IBM437)

So I have some auto-generated PlantUML class diagrams containing snippets like the following:
`class SettingsManager [[#_settingsmanager]]`

This plantuml file is added to my document like so:
`plantuml::../ClassDiagrams/Settings.puml[format=svg,opts=inline]`

When I export to html via the following command:
`asciidoctor -r asciidoctor-diagram -r rouge Documentation/Settings/SettingsSystem.adoc`

the links are clickable and take me to the relevant anchor defined in my adoc (I have the 'sectanchors' attribute applied). So far so good. 

However, if I export the same document to PDF with the the following command:
`asciidoctor-pdf -r asciidoctor-diagram -r rouge -b pdf Documentation/Settings/SettingsSystem.adoc`

then the diagram isn't clickable at all (but my section headings in my TOC still are). 

Is this something I'm not setting correctly in my adoc, or something upstream in prawn, or ?

**Comment by mojavelinux** [comment]
You're correct. This converter does not support anchors inside of images. If it were to be supported, it would have to be added to prawn-svg. That library would need to process the ID in the SVG and register a destination for it. That's not something this converter can do because it doesn't have access to that low-level information about the SVG.

**Comment by mojavelinux** [comment]
> [[#_settingsmanager]]

Is this a PlantUML syntax?

**Comment by stephenwhittle** [comment]
`class SomeClass [[ some-link ]]` is plantuml syntax for making the class clickable in the svg output (by embedding xlink:href tags, as you specify it would need to do in https://github.com/asciidoctor/asciidoctor-pdf/issues/1105 ). 
I figured, seeing as it was possible to refer to an external URL, that referring to an anchor in the local file would be possible as well - `#_settingsmanager` is an attempt to reference the autogenerated anchor created by asciidoctor with the `sectanchors` attribute.

**Comment by mojavelinux** [comment]
Oh, I see. It's a link from the SVG. Let me look closer.

**Comment by mojavelinux** [comment]
> is an attempt to reference the autogenerated anchor created by asciidoctor with the sectanchors attribute.

`sectanchors` isn't what makes the ID. That's `sectids`. `sectanchor` just adds a visual, interactive indicator of where the ID is. But that's just a side note.

**Comment by mojavelinux** [comment]
Okay, this is possible, but again, it needs to happen in prawn-svg. In PDF, a local reference is a different type of PDF object than an external reference. The local reference must be defined as an anchor, whereas the external reference is defined as a link. A subtle, but important difference. prawn-svg should be able to detect the leading `#` and make an anchor object. So I would file the issue there.

Also, pay attention to the commit message for the fix: https://github.com/mogest/prawn-svg/commit/388632f1bc743d61aece7704a776922f239f3984

> Support <a> element with no functionality

So that's your first problem ;)

**Comment by stephenwhittle** [comment]
Alright, I'll file something with prawn-svg then. Thanks for clarifying!
