### ISSUE TITLE
Prose text indent reduces spacing below first paragraph line

### ISSUE THREAD

**Issue by abbrev** [asciidoctor/asciidoctor-pdf#1557]
When the `prose-text-indent` property is set to greater than zero, the space between the first and second lines of the paragraph is reduced. The space is reduced by the same amount regardless of the indent amount. This doesn't seem intentional as nothing is mentioned in the documentation about this side-effect, and I couldn't find any properties related to setting the space either.

Source (bug.asc):

```adoc
= asciidoctor-pdf bug
:doctype: book

XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX
XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX
XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX
XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX
```

Style (bug.yml):

```yaml
page-size: Letter
prose-text-indent: 0.1in
```

Here's what it looks like rendered as a PDF:

![bug-indent](https://user-images.githubusercontent.com/2147334/74485339-c61bb200-4e77-11ea-9503-0c260178d995.png)

Here's what it looks like rendered as a PDF after setting `prose-text-indent` to 0:

![bug-no-indent](https://user-images.githubusercontent.com/2147334/74485343-c87e0c00-4e77-11ea-91c8-eb20bcdbb411.png)

```
$ asciidoctor-pdf --version
Asciidoctor PDF 1.5.0 using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-cygwin]) (lc:UTF-8 fs:Windows-1252 in:UTF-8 ex:UTF-8)
```

**Comment by mojavelinux** [comment]
This seems to only happen when using [AFM fonts](https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#built-in-afm-fonts). If you use a TTF font instead, the calculation is correct. What I'm not sure of is why this is linked to AFM fonts.

There's a test for this scenario in the test suite that uses a TTF font and that test passes. But we aren't testing it with an AFM font, which is why this case is slipping through.
