### ISSUE TITLE
Slow conversion of book-size documents

### ISSUE THREAD

**Issue by slonopotamus** [asciidoctor/asciidoctor-pdf#1582]
1. `git clone git@github.com:progit/progit2.git`
2. `cd progit2`
3. `touch book/contributors.txt`
4. `bundle install`
5. `time bundle exec asciidoctor-pdf progit.asc`

Resulting PDF has 527 pages as of today.

On my Ryzen 1700, this book converts to HTML in 0.7s, to EPUB3 in 2.8s and to PDF in 1m46s.

```
$ bundle exec asciidoctor-pdf --version
Asciidoctor PDF 1.5.3 using Asciidoctor 1.5.6.2 [http://asciidoctor.org]
Runtime Environment (ruby 2.4.9p362 (2019-10-02 revision 67824) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
```

**Comment by mojavelinux** [comment]
This is largely going to be addressed by the changes coming in Asciidoctor PDF 2, which will do away with the dry run in most cases and only use a single pass. Conversion is also slow because Ruby is slow at reading and processing PNG images. It's decidedly faster to use prawn-gmagick.

Beyond that, there isn't much we can do. That's just the limitation of this stack (and the PDF generator in particular). We'll focus on achieving better speed with the web-based PDF converter.

**Comment by slonopotamus** [comment]
I believe it would not hurt to perform some profiling here to confirm that PNGs are the main issue.

**Comment by mojavelinux** [comment]
I've done that and I'm quite confident of where the problems are. The first and main problem is the double rendering of almost every node, esp large blocks (which is being addressed). The second are images, particularly PNGs. But beyond that, Prawn is just not efficient and is not being improved, so there isn't much we're going to be able to do. If someone can identify hotspots that we can fix, I'm glad make what changes are necessary to improve them.

In my experience, PDF generation is slow no matter what tool is used. I've never seen a fast PDF converter. So there are inherent limitations in the format itself. We're never going to come anywhere close to the speed of converting to HTML (unless the toolchain itself uses HTML).

**Comment by oddhack** [comment]
IME going through the asciidoctor -> latex -> pdflatex path was about twice as fast as asciidoctor-pdf on ginormous documents like the Vulkan specification, though I haven't done that for a couple of years. Maybe that's just because asciidoctor-pdf is doing twice as much work, but I will be grateful for any improvements as well. It takes 5.5 minutes on a Ryzen 2600 to generate our full specification document (ca. 2331 PDF pages), and there  are about 16 MB of SVG source incorporated in the output.

**Comment by mojavelinux** [comment]
I believe eliminating the double rendering will make a big difference. But there are still inherent limits in the PDF generation library that we won't be able to do anything about (short of writing a new PDF generator library, which I'm definitely not going to do). The future will be the browser-based stack, which I'll talk more about once Asciidoctor PDF 2 is out.

**Comment by oddhack** [comment]
Chromium takes about 1:45 to 'Print to PDF' of the same document from asciidoctor-generated HTML, so if you're planning to leverage a browser engine in some fashion as that name suggests, that could help. Not expecting miracles of course.

**Comment by mojavelinux** [comment]
As I suspected, the lag largely has to do with decoding PNG images. Here are the results on my machine converting Pro Git 2 using Ruby 3.1 and Asciidoctor PDF 2. (11th Gen Intel® Core™ i7-1065G7 CPU @ 2.80GHz (4 cores / 8 threads), 15.4 GiB RAM)

```
real    0m53.429s (without prawn-gmagick)
real    0m33.780s (with prawn-gmagick)
```

Decoding PNG images requires a lot of mathematical computation, and that's not a task Ruby is particularly efficient at performing. That's why prawn-gmagick makes such a substantial difference.

Contrary to what I anticipated, Asciidoctor PDF 2 isn't any faster than Asciidoctor PDF < 2. But it's not slower either. I get almost identical results.

There's nothing fundamentally I know that we can change to make Asciidoctor PDF any faster. We're limited by the capabilities of the PDF library (Prawn) and Ruby itself. And PDFs are extremely complicated to create for a variety of reasons, so it's going to be slower than producing other formats. That's why we'll be looking to using web-based technologies to generate PDFs in the future. But that's still very much on the horizon.

**Comment by oddhack** [comment]
Will the prawn-gmagick path be something supported OOTB with version 2?

**Comment by mojavelinux** [comment]
It's supported out of the box with Asciidoctor PDF 1.5.x, 1.6.x, 2.0.x, and all future versions. This is explained in the README (and will be explained in the docs once they are available). See https://github.com/asciidoctor/asciidoctor-pdf#supporting-additional-image-file-formats
