### ISSUE TITLE
Regression from 1.5.0rc1 to 1.5.3 (images in tables)

### ISSUE THREAD

**Issue by rillbert** [asciidoctor/asciidoctor-pdf#1608]
Hi.
I think that I have found a regression in how image content in tables are handled in situations where the image is deemed 'too large'.

The attached zip contains an adoc and two associated images. It is rendered in v1.5.0rc1 but will crash v1.5.3.

[bug_report.zip](https://github.com/asciidoctor/asciidoctor-pdf/files/4331350/bug_report.zip)

**Comment by mojavelinux** [comment]
While these seems like a bug, it's actually the expected behavior. You have not reserved enough room in the column for the image to fit with its natural size. And the reason for the error has to do with limitations in how text is arranged in Prawn (otherwise, we get other problems).

There are numerous ways to solve this problem:

1. Increase the width of the column (e.g., `cols="30s,40,30"`)
1. Give the image an explicit width that is less than the computed width of the column (e.g., `pdfwidth=1.5in`)
1. Add the AsciiDoc style to the table cell with the image (which changes how images are arranged)
1. Add the AsciiDoc style to the table cell with the image and use a block image instead of an inline image

The last solution is the most robust because it allows the image to be resized to fit the column width if necessary.

```
a|image::3-0_Imaging_Camera_gain.PNG[]
```

Related issue: #1555.

**Comment by mojavelinux** [comment]
Btw, this use case is documented in the Known Limitations section in the README.

> Inline images in table cells must fit within available space or Prawn::Errors::CannotFit error will be thrown.

**Comment by rillbert** [comment]
Thank you for the prompt answer.
Since the document is generated ok in 1.5.0-rc1, I assumed that this was a
regression.

Keep up your fantastic work!

/Anders

Den lör 14 mars 2020 kl 10:19 skrev Dan Allen <notifications@github.com>:
