### ISSUE TITLE
"Unknown tag 'pattern'; ignoring"

### ISSUE THREAD

**Issue by oddhack** [asciidoctor/asciidoctor-pdf#1621]
While trying to migrate from asciidoctor 1.5.8 I encountered a new warning message building our PDFs, of form:

> asciidoctor: WARNING: problem encountered in image: /vulkan/test/test.svg; Unknown tag 'flowRoot'; ignoring  
> asciidoctor: WARNING: problem encountered in image: /vulkan/test/test2.svg; Unknown tag 'pattern'; ignoring

This may not be happening in prawn-svg, as @mojavelinux suggested [on the Asciidoctor-Discuss list](https://discuss.asciidoctor.org/Diagnosing-quot-Unknown-tag-flowRoot-quot-warning-in-PDF-generation-td7773.html). I tried the trivial example that reads and renders an SVG found on 
https://github.com/mogest/prawn-svg and did not see this warning. However, I have a minimal case with asciidoctor-pdf (see attached zipfile). Reproduce by (*edit* cut&paste incorrectly):

> asciidoctor -b pdf  -r asciidoctor-pdf -o test.pdf test.txt

If the error is being reported by some toolchain component further down than asciidoctor-pdf, could I at least get some guidance on how to determine where it's happening and how that toolchain component is being invoked? That the message is prefixed 'asciidoctor' and is PDF-specific leads me to open an issue here first.

Running asciidoctor per above generates warnings about the <flowRoot> tag, which I can understand because it's apparently only supported by Inkscape, but also about the <pattern> tag which is AFAICT standard SVG per https://developer.mozilla.org/en-US/docs/Web/SVG/Element/pattern

The warning does occur in: asciidoctor 2.0.10 / asciidoctor-pdf 1.5.3 / prawn 2.2.2 / prawn-svg 0.30.0

The warning does not occur in: asciidoctor 1.5.8 / asciidoctor-pdf 1.5.0.alpha.16 / prawn 2.2.2 / prawn-svg 0.27.1

Minimal case:
[test.zip](https://github.com/asciidoctor/asciidoctor-pdf/files/4362621/test.zip)

**Comment by mojavelinux** [comment]
All SVG parsing errors and warnings should be directed to https://github.com/mogest/prawn-svg. Asciidoctor PDF doesn't do SVG processing. It only reads the SVG file and delegates the parsing and rendering to prawn-svg.

What you're observing is a difference in behavior due to the prawn-svg upgrade in Asciidoctor PDF. But that's still an issue with prawn-svg, not Asciidoctor PDF.

prawn-svg doesn't necessarily support all standard SVG tags. It tries to be as complete as possible, but the spec is very large and the author does the best he can to support the bulk of it.

Also note that this is not an error. It's just a warning. prawn-svg skips over tags it doesn't know, but still renders the SVG regardless.

**Comment by mojavelinux** [comment]
Actually, it wasn't the prawn-svg upgrade. It's that we now forward warnings from prawn-svg to the Asciidoctor logger. See https://github.com/asciidoctor/asciidoctor-pdf/issues/1479 So the warnings were always there.

**Comment by oddhack** [comment]
Well, that would explain why the output was visually identical, since the tags were silently getting ignored all along :-) Good enough.

**Comment by oddhack** [comment]
And thanks for the quick reply!

**Comment by Hollerweger** [comment]
Is there a way to ignore this specific WARNING for logs in antora builds? (as i see a lot of them)

**Comment by mojavelinux** [comment]
Please ask questions about usage in the project chat at https://chat.asciidoctor.org.
