### ISSUE TITLE
Break long table columns

### ISSUE THREAD

**Issue by somera** [asciidoctor/asciidoctor-pdf#1628]
My problem is that I can't see in the generated pdf the whole column. It will be cut at the end on the current page and on the next page it starts with the next row.

![image](https://user-images.githubusercontent.com/8334250/77947300-03bb8980-72c4-11ea-81fa-e1e0ac5de908.png)

Sorry, but I can't post here the whole screenshot.

I didn't find any solution for my problem.

I'm using this versions

`        <asciidoctor.maven.plugin.version>1.5.6</asciidoctor.maven.plugin.version>
        <asciidoctorj.version>1.5.4</asciidoctorj.version>
        <asciidoctorj.pdf.version>1.5.0-alpha.17</asciidoctorj.pdf.version>
        <jruby.version>9.2.7.0</jruby.version>`

**Comment by mojavelinux** [comment]
A cell cannot be taller than the height of a single page. You will have to split it manually. This is a hard constrain of this converter due to a limitation in the underlying PDF generator (specifically prawn-table). This constraint is documented in the README: https://github.com/asciidoctor/asciidoctor-pdf#known-limitations
