### ISSUE TITLE
working with page numbers from macros

### ISSUE THREAD

**Issue by 42sol-eu** [asciidoctor/asciidoctor-pdf#1631]
Dear Asciidoctor-PDF-Team,
thanks for your great work. We switched from madcaps flare to asciidoctor and looked never back since.

Step by step we try to increate our knowledge about asciidoctor and asciidoctor-pdf.

At the moment we are playing with manual index and table of contents.
We build a small inline-makro abd we would really like to access the page_number attribute from the pdf from there.

I really looked hard and long and tried to find a clue in the source code of the different projects, but I did not find how you access it. 

Could you point me in the right direction or give me a hint where I can look it up?
A link to a nice comprehensive documentation about the InlineMacro and the BlockMacro would also be very welcome.

What can I do to improve? Just ask if you know something.

Sincerely
  Felix

**Comment by mojavelinux** [comment]
It's tricky because the page numbers are not predetermined. The counter is updated as the content is written to the PDF stream.

In the macro, you can access the current page number (where the macro started) via `node.document.converter.page_number`.

If you are adding pages to the PDF after the converter runs, the page on which a section starts is accessible via `section.attr 'pdf-page-start`.

If you share some code, I might be able to help you with it. I'd also like to understand better why you aren't able to use the provided index and table of contents.

**Comment by 42sol-eu** [comment]
> I'd also like to understand better why you aren't able to use the provided index and table of contents.

That is mainly because of two reasons:
1. We want a highly modified table of content that will not span a whole page but be integrated on the titlepage of the pdf 

like so

```
   Title of the Document
   +--------+     +---------------+
   | lmage  |     | list of       |
   | on     |     | system-       |
   | left   |     | features      | 
   | column |     +---------------+
   |        |     +---------------+
   |        |     | compact       |
   |        |     | toc           |
   +--------+     +---------------+
```

2. we would like to be able to create chapter-wise / part-wise tocs for our handbook or training materials.

3. we struggled with cross refernces linke <<blockdiagram>> that should expand to "See the paragrpn **[3.2.1] blockdiagram** on _page_ *24*"

We started on a manual approach (I will provide source code later) with a simple 
due to a issue comment that you wrote some months ago.

```
<<<
counter:manual_page[]

[[blockdiagram; Chapter {active_chapter} Blockdiagram see on page {manual_page}]]
```
This would be a light weight a proach for documents with less than 20 pages like data sheets. There the page break is mostly manual  controlled with `<<<`

The more complex case would be a document with 100-200 pages that has a lot of long chapters. The manual approach with controlling every page break would vastly become to much effort. We investigated about setting counters to only mark the pages with the chapters like the simple example, but could not get the `counter` or  `calc` marco to work. And putting in the page_numbers of the chapters by hand.

We also considered a very basic approuch with two runs of `asciidoctor-pdf` and a `chapter_pages.adoc` file setting all variables like `chapter_2_page` `chapter_2_2_page` and include it after the first run in the main asciidoc document.

I am guessing we are on a wrong track (rabbit hole).
Is there a way (e.g. macro for partial tocs)?

**Comment by mojavelinux** [comment]
Thank you for sharing this information. That gives me a better grasp of what you're asking.

I strongly recommend that you do this customization programmatically (by extending the converter) rather than trying to shoehorn it into the AsciiDoc content. I always advise users to keep the AsciiDoc as clean as possible and void of artifacts that only serve the output. The direction you're headed makes it harder to maintain the content as it violates the separation of content and presentation.

I only recommend introducing using macros when they are semantically relevant to the content. And `counter:manual_page[]` (and counters in general) are certainly not that.

The default behavior of Asciidoctor PDF is intentionally simple (to fill a void in the publishing space). But, it also serves as a useful framework to extend and take it in a more specific direction.

```ruby
class CustomPDFConverter < (Asciidoctor::Converter.for 'pdf') do
  register_for 'pdf'

  # override methods here
end
```

**Comment by mojavelinux** [comment]
For completeness, here's how you can access the current page number via an inline macro (if you must).

```ruby
# usage:
#   This is page number pagenum:[].
Asciidoctor::Extensions.register do
  inline_macro :pagenum do
    format :short
    process do |node|
      node.document.converter.page_number
    end
  end
end
```

**Comment by 42sol-eu** [comment]
Hi Dan,
thanks for the reply. I agree: keeping the content free from artifacts is a much better way. I will look into the converter solution. And the code snippet with the page number is very helpful for good and simple references.

As far as I can see it from here, a mini_toc should be a possible solution via a block macro and a converter.

I will look into the material and come back to you

**Comment by mojavelinux** [comment]
I've added this example to the documentation.
