### ISSUE TITLE
Option to de-duplicate page numbers in Index

### ISSUE THREAD

**Issue by peterjaap** [asciidoctor/asciidoctor-pdf#1656]
When writing a paragraph, I do not know in advance on what page what term shows up. So when writing a paragraph with a term I want indexed, I wrap all occurrences of that term in double parentheses.

Example text;

```
=== PHP CLI ((SAPI))

While working with the PHP CLI, you’ll run into the term _SAPI_. ((SAPI)) stands for _Server Application Program Interface_, and it refers to the way the code runs on your system. The ((SAPI)) handles the communication flow between the user and the PHP engine. Some common ((SAPI))’s for PHP are CGI, FPM, Apache (when PHP is compiled as an Apache module), and CLI.

The ((SAPI)) we use in this book is the CLI ((SAPI)). Sometimes we want to be able to check which ((SAPI)) we are using to execute different code paths depending on whether it’s run in a CLI application or through a webserver. To do this, PHP provides a function called `php_sapi_name()` and the constant `PHP_SAPI`, which will both return the currently used ((SAPI)).
```

However, when generating the Index, the page numbers are shown multiple times;

![image](https://user-images.githubusercontent.com/431360/79965941-f9d51280-848c-11ea-8e7e-da718a355a5c.png)

I could only wrap the first occurrence of the term but then only page 13 shows up in the index, and not page 15 and 16. 

It would be nice to have a configuration option like `:index-page-numbers-unique: true` to control this behavior so we can have unique page numbers in the index.

Sidenote; just found out wrapping terms in parentheses in headers will not generate an index entry for it. Not really a problem though.

**Comment by mojavelinux** [comment]
The reason the numbers are repeated is because they are links. If dedepulicate them, then they won't be links anymore (or the range would have to link to the first occurrence).

Note that they are deduplicated when using media=print because on a physical page, there are no links (and thus we don't have the linking problem).

**Comment by peterjaap** [comment]
@mojavelinux thanks! `:media: print` was what I needed!

**Comment by peterjaap** [comment]
Wouldn't it be possible to still be able to create links, but instead linking to the actual term, link to the page they're on, like the ToC links to a specific page?

Because my book will mainly be distributed through PDF, so the link would still be very welcome, but I don't want the page numbers to be duplicated with links to the individual term occurrences.

**Comment by mojavelinux** [comment]
It feels like that behavior would be perceived as unexpected since some numbers would jump straight to the term while others would leave the reader hunting for it. If the ranges were to be consolidated, I think it would need to at least jump to the first occurrence.

The term we use internally for the grouping you are requested is "consolidate ranges". If we decide to move forward with it, it seems to make more sense to add it as an option on the index section. Something like:

```
[index%consolidate-ranges]
== Index
```

**Comment by mojavelinux** [comment]
In looking at this further, I can see that there are, in fact, three styles. The first is showing an entry for each page. The second is to link to the first occurrence on a page. The third is the range.

In order to support this different styles, the attribute we use to configure it should accept a keyword. I'm thinking something like `index-pagenum-sequence-style` with the following values:

* term (default for screen)
* page
* range (default for print or prepress)

**Comment by mojavelinux** [comment]
In the end, I quite like this enhancement. It makes a lot of sense.
