### ISSUE TITLE
Speed versus LaTeX

### ISSUE THREAD

**Issue by muv1** [asciidoctor/asciidoctor-pdf#1658]
Currently I am using LaTeX to create PDFs, however I wanted to explore other
options. If I have a LaTeX document like this:

~~~
\documentclass{article}
\begin{document}
\section{Sunday}
Monday
\end{document}
~~~

It will compile pretty fast:

~~~
> measure-command {pdflatex a.tex}
pdflatex: security risk: running with elevated privileges
pdflatex: major issue: So far, no MiKTeX administrator has checked for updates.
TotalSeconds      : 0.4850575
~~~

If I have an AsciiDoc like this:

~~~
= Sunday

Monday
~~~

Its about 20 times slower:

~~~
> measure-command {asciidoctor-pdf a.adoc}
TotalSeconds      : 9.9462198
~~~

Is this expected, or can I do something to speed it up?

**Comment by muv1** [comment]
After much thinking I went with HTML instead of LaTeX or AsciiDoc, this works for me:

<https://github.com/dompdf/dompdf>

**Comment by mojavelinux** [comment]
What I was going to write is that HTML-to-PDF is the approach we're going to be taking too. A significant portion of the latency in this converter is due to the fact that every block is rendered multiple times in order to compute its dimensions. This extra work will be eliminated with a new design in Asciidoctor PDF 2. We expect that change will improve performance substantially. But we'll still limited by the speed of the PDF generator, which isn't great. Plus, reading and decompressing compressed images like PNGs is very slow in Ruby since it involves math, though that problem can be mitigated by using prawn-gmagick (which delegates the decompression to GraphicsMagick).

What we've learned in developing this converter is that while we can get a pretty good result using these technologies, we need to start looking elsewhere. That's what the asciidoctor-pdf.js effort is all about, which I'll be announcing here in detail shortly after the Asciidoctor PDF 2 release.

**Comment by mojavelinux** [comment]
However, if it's taking 9 seconds to convert a 3-line AsciiDoc document to PDF, then your Ruby is misconfigured. Did you by chance install it using Homebrew? For some reason, the Ruby Homebrew installs performs terribly. That's why I always recommend installing Ruby using RVM.

Here's the result you should get (using Ruby 2.7)

```
real	0m0.857s
```

**Comment by mojavelinux** [comment]
My point still stands about large documents, but under no circumstances should Asciidoctor PDF take more than 1 second to start running.

**Comment by muv1** [comment]
I am using Windows, so any preconceptions are out the Window unless you are, can test with a Windows system. Dont mean to be curt, but the simple fact is that in general Windows sucks with stuff like this unless the maintainer has developed with Windows in mind, and not as an afterthought.

Again no disrespect, thanks for the replies.

**Comment by mojavelinux** [comment]
> can test with a Windows system

I can test with a Windows system and I do. We test every single commit on Windows. I can state with empirical evidence that Asciidoctor PDF is not that slow on Windows.

In fact, I test all the Asciidoctor-related software I write on Windows. So don't make presumptions.

**Comment by mojavelinux** [comment]
If you compare these two jobs, the tests are actually running faster on Windows than on Linux (granted the virtual hardware is not identical)

* https://travis-ci.org/github/asciidoctor/asciidoctor-pdf/jobs/678495714
* https://github.com/asciidoctor/asciidoctor-pdf/runs/611275751?check_suite_focus=true

**Comment by muv1** [comment]
I'm sorry, I just don't care enough about this to continue. I will say that I am using the Rubyinstaller version if that helps, not MSYS2 version

**Comment by mojavelinux** [comment]
I'm not expecting you to continue. I'm just trying to help. But I do get agitated when you make comments that suggest I leave users out. I spend **a lot** of my life trying to make Asciidoctor the best experience it can be on all platforms. If that isn't good enough for you, that's fine. Use something else. But save your attitude for somewhere else. It's not welcome here.
