### ISSUE TITLE
Fake error thrown for ampersand in quote author line

### ISSUE THREAD

**Issue by nitrocalcite** [asciidoctor/asciidoctor-pdf#1662]
When an ampersand is included in the quote author line:
```
[quote, J. Helliwell & B. McMahon, International Union of Crystallography Feature Article]
The richer the metadata available to the scientist, the greater the potential for new discoveries.
```
It generates an error on `pdf` compilation, but not `html` compilation:
```
asciidoctor: ERROR: failed to parse formatted text: — J. Helliwell & B. McMahon, International Union of Crystallography Feature Article
```
Despite this, the PDF output looks fine, rendering the "&" without issue.  
This error is not thrown for plain `&` characters in the document body.
This error can be suppressed by replacing `&` with `&amp;`.

Not sure what could be causing this. 
Output of `asciidoc-pdf --version` is:
```
Asciidoctor PDF 1.5.3 using Asciidoctor 2.0.11.dev [https://asciidoctor.org]
Runtime Environment (ruby 2.6.6p146 (2020-03-31 revision 67876) [x64-mingw32]) (lc:IBM437 fs:Windows-1252 in:UTF-8 ex:UTF-8)
```

**Comment by mojavelinux** [comment]
The error is very much real, it just so happens that the fallback text matches what you expect to see.

This happens because special characters like & are not escaped by default in the attribute and citetitle of a quote or verse block, so the internal parser cannot properly parse it. That's a bug.

You can workaround the problem by putting the author in single quotes. This forces Ascidoctor to escape the text.

```
[quote, 'J. Helliwell & B. McMahon', International Union of Crystallography Feature Article]
The richer the metadata available to the scientist, the greater the potential for new discoveries.
```

I'll close this issue once I put a fix in place so that it works with or without the single quotes (as it should).

Note, the HTML converter also has this problem. (You just don't get a log message about it).

**Comment by nitrocalcite** [comment]
Good to know, thanks a lot for the quick fix!
