### ISSUE TITLE
indent for images would be nice 

### ISSUE THREAD

**Issue by astrograph** [asciidoctor/asciidoctor-pdf#1670]
in the html version of an asciidoc version we indent the images by 20 pixel for aesthetical reasons, I wasn't able to create something similar in the pdf version we also create.

this is how it looks in the html version:
![2020-04-29 08_19_17-example](https://user-images.githubusercontent.com/5181456/80566073-6357a280-89f2-11ea-9da7-e355175118ed.png)
the read arrow indicates the indent, and was added in the screenshot

I think I am looking for something like this:
```
image:
  indent: [0.5in, 0]

```

**Comment by mojavelinux** [comment]
I have documented how to indent block images using an extended converter. You can find the example code at the following location: https://github.com/asciidoctor/asciidoctor-pdf/blob/main/docs/modules/extend/examples/pdf-converter-image-indent.rb This example, as well as numerous others, will be included in the documentation for Asciidoctor PDF 2.0.0 when it is released.

Since this feature has only ever been requested once, I think it's best left up to an extended converter. If it becomes clear that many people need this feature, I'd be happy to shift the code into the primary converter.
