### ISSUE TITLE
Page numbers in the footer

### ISSUE THREAD

**Issue by Eric-Sparks** [asciidoctor/asciidoctor-pdf#1695]
I'm working on writing a book and I'd like to include page numbers in the footer of the PDF (I'm using asciidoctor-pdf).

I found [this discussion](https://discuss.asciidoctor.org/Page-Numbering-td6487.html) but it doesn't look like anyone ever filed a ticket to make it happen.  It was suggested to use attributes like `pagenums-start` or `pagenums-offset` to control the starting value.

**Comment by mojavelinux** [comment]
@stallio Is absolutely correct. Page numbering just works by default. In fact, the `pagenums` attribute isn't even relevant anymore. It was keep only for backwards compatibility with a very old approach.

@Eric-Sparks Are you not seeing page numbers in the footer?

**Comment by mojavelinux** [comment]
Here's an example of how you'd customize the footer to show the page number in a centered column: https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#replacing

But you can position it a lot of different ways.

**Comment by Eric-Sparks** [comment]
No, I'm not seeing any page numbers.  I'm generating the pdf using asciidoctor-pdf (Asciidoctor PDF 1.5.0.beta.6 using Asciidoctor 2.0.10).

**Comment by Eric-Sparks** [comment]
I've been able to add page numbers by defining them in my style sheet.

**Comment by mojavelinux** [comment]
> I've been able to add page numbers by defining them in my style sheet.

Do you mean your theme file?

I can assure you that Asciidoctor PDF displays page numbers in the footer by default when using the default theme. (https://github.com/asciidoctor/asciidoctor-pdf/blob/v1.5.3/spec/running_content_spec.rb#L45-L77) Unless perhaps you are using a custom theme already which disables them.

If you can demonstrate otherwise, please attach the PDF that was generated.

> Asciidoctor PDF 1.5.0.beta.6

That's an old version of Asciidoctor PDF (from Oct 2019). Please use 1.5.3, which is the latest stable release.

**Comment by Eric-Sparks** [comment]
> > Asciidoctor PDF 1.5.0.beta.6
>
> That's an old version of Asciidoctor PDF (from Oct 2019). Please use 1.5.3, which is the latest stable release.

So packaged versions in Fedora are outdated; I'll open a bug on that later.

**Comment by Eric-Sparks** [comment]
> > I've been able to add page numbers by defining them in my style sheet.
>
> Do you mean your theme file?

"Theme"?  I'm defining certain things in a CSS-formatted file.  I wasn't turning anything off in the file, just defining fonts and such.

> I can assure you that Asciidoctor PDF displays page numbers in the footer by default when using the default theme. (https://github.com/asciidoctor/asciidoctor-pdf/blob/v1.5.3/spec/running_content_spec.rb#L45-L77) Unless perhaps you are using a custom theme already which disables them.

I'll test this in a bit and see.

**Comment by mojavelinux** [comment]
> So packaged versions in Fedora are outdated

1.5.3 is already available in Fedora 33 (thanks to the great work by Christopher Brown). https://apps.fedoraproject.org/packages/rubygem-asciidoctor-pdf

> "Theme"?

Yes, theme: https://github.com/asciidoctor/asciidoctor-pdf/blob/v1.5.x/docs/theming-guide.adoc

> I'm defining certain things in a CSS-formatted file.

Asciidoctor PDF doesn't support CSS. The theme is like CSS, as the theming guide explains here: https://github.com/asciidoctor/asciidoctor-pdf/blob/v1.5.x/docs/theming-guide.adoc#language-overview But it's not CSS.

> I wasn't turning anything off in the file, just defining fonts and such.

It would be best if you shared your theme file so that we can actually see what's happening.

**Comment by mojavelinux** [comment]
Please reopen if you find this is still an issue for you.
