### ISSUE TITLE
How to convert indexed page numbers to links back to the page

### ISSUE THREAD

**Issue by Webcompose** [asciidoctor/asciidoctor-pdf#1724]
If this is already possible add that to the manual for asciidoctor

**Comment by mojavelinux** [comment]
The documentation for the PDF converter is not included in the user manual. It will show up on the new docs site (at https://docs.asciidoctor.org) once we finish the migration. Until then, the documentation for the PDF converter lives in the repository (at https://github.com/asciidoctor/asciidoctor-pdf/blob/v1.5.x/README.adoc and https://github.com/asciidoctor/asciidoctor-pdf/blob/v1.5.x/docs/theming-guide.adoc).

**Comment by mojavelinux** [comment]
The reason media=prepress does not create the link is because media=prepress is designed more making output that goes to a printer. In that context, links aren't relevant. You can find info about that mode here: https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#prepress

**Comment by mojavelinux** [comment]
I have updated the docs to mention the impact setting the media attribute has on the index entries. See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#print
