### ISSUE TITLE
Ordered list numbers are wrongly positioned using inline literals with custom font

### ISSUE THREAD

**Issue by wimdeblauwe** [asciidoctor/asciidoctor-pdf#1759]
I am using a custom font for the inline literals (JetBrains Mono). When I use literals in an ordered list, the formatting is a bit off.

I managed to reproduce the issue with this simple theme that does not require a custom font:

```
extends: default-with-fallback-font
literal:
  font_color: '#0066a1'
  font_size: $base_font_size * 1.6
```

Asciidoc source:
```
Implementing a form submit is a multi-phase process:

. The browser does a `GET` to display the form.
. The user enters information using the form elements.
. The browser does a `POST` with the form elements' information.
. If there are no validation errors, the browser gets redirected to avoid double submissions.
. If there are validation errors, the form remains in place so the user can correct the information.
```

Resulting PDF:

![image](https://user-images.githubusercontent.com/1115823/91573386-2e7b3e00-e947-11ea-9a8f-2b7bb6531a1a.png)

Note how "1." and "3." are too high.

**Comment by mojavelinux** [comment]
This is because the literal font is too large to fit in the line, thus pushing the line upwards. You'll need to make the font size smaller. This is just how the PDF generator lays out text. We don't have control over it.

(I don't recommend making the literal font size larger than the main text).

**Comment by mojavelinux** [comment]
I'm afraid there's really nothing we can do here. The height of the codespan is taller than the line height, and therefore it changes the positioning of the marker relative to the line of text (which is aligning to the line height of regular text). It's true that this differs from how the browser works, which is to align the marker with the regular text. But Prawn doesn't have the same typesetting capabilities of a browser, far from it. So we just can't know know where the baseline is of the line after it's rendered. The best we can do is center on the line height of regular text.

I recommend reducing the size of the codespan so that it does not affect the line height.

If someone knows how to solve this and wants to propose a change to the code, I'm happy to consider it.

If you need assistance with writing a custom theme, please ask in the #asciidoctor-pdf stream in the project chat at https://chat.asciidoctor.org.
