### ISSUE TITLE
Chapter label and xref

### ISSUE THREAD

**Issue by dalai4git** [asciidoctor/asciidoctor-pdf#1761]
This may be simply a documentation issue, but a change of `chapter-label` to `Kap.` does not have any effect on `chapter-refsig`. I think the theming guide should at least mention that both may need to be changed to keep the document consistent. An automatic change could be nice, but may not be desired in all cases, e.g. when the `chapter-label` is empty. In any case, it would be useful if it was simpler to override `chapter-label` using a similar approach to `Asciidoctor::DEFAULT_ATTRIBUTES`.

I was going to write a pull request, but I thought I should ask first what is the proper solution.

Also the theming guide mentions only `chapter-label` but the code uses `chapter-signifier` as the preferred option.

**Comment by mojavelinux** [comment]
You are correct that they both need to be assigned. They apply to different things (and AsciiDoc doesn't change one attribute because you change another).

I agree this should be documented.

> Also the theming guide mentions only chapter-label but the code uses chapter-signifier as the preferred option.

The theming guide was written before chapter-signifier was introduced. Now that Asciidoctor 2 is the minimum version (starting in Asciidoctor PDF 2), we can assume chapter-signifier is always available and document it as such.
