### ISSUE TITLE
Use PDF:s as block (or inline) images, i.e. not on separate pages

### ISSUE THREAD

**Issue by gustav-b** [asciidoctor/asciidoctor-pdf#1767]
Is it possible to include an image in PDF format and have it placed just like any other block image? Currently if I include a PDF like:
```adoc
image::some-image.pdf[Here's an image]
```
…it will be rendered on a separate page. It make sense if the PDF is a full page, but it's quite limiting if you happen to have a small vector drawing in PDF. Is it possible to force asciidoctor-pdf to handle a PDF as a block image, or is there some technical reason why this is hard?

My particular use case is that I want to render [mermaid](https://mermaid-js.github.io) diagrams using [asciidoctor-diagram](https://asciidoctor.org/docs/asciidoctor-diagram/) but [prawn-svg](https://github.com/mogest/prawn-svg) seems to have problems with the SVG:s mermaid outputs (they're missing elements, colors are off, etc.). But mermaid can output PDF:s (which look correct) instead of SVG:s – now I just need asciidoctor-pdf to place them as block images…

Thanks!

**Comment by mojavelinux** [comment]
What you're asking about is not possible. Only whole pages of a PDF can be imported, which means it occupies a whole page in the generated document.

The importing of PDF pages is actually handled by prawn-template, not Asciidoctor PDF. And the only feature that library offers is to import whole pages. If you can find or provide a library which can import a specific object from an existing PDF document as an image object, then I might be able to integrate that into Asciidoctor PDF. But without that library, it's not something Asciidoctor PDF can offer.

My advice would be to use a tool to clean up the mermaid diagrams so that they are compliant with the standalone SVG specification. That way, they can be handled properly by prawn-svg. Another option would be to convert the image to a raster format such as PNG.

**Comment by gustav-b** [comment]
Thank you for the explanation – then it makes sense why it's currently not possible.

I'll see if I can wrap the mermaid cli with some filter to make prawn-svg happy with its SVG. I wasn't aware of asciidoctor-web-pdf, thanks for the tip!
