### ISSUE TITLE
code block with links is rendered with html entities

### ISSUE THREAD

**Issue by iranzo** [asciidoctor/asciidoctor-pdf#1802]
Hi,
We do use asciidoc to generate both HTML and PDF version of the same documentation 

~~~sh
# Build the documentation
asciidoctor -a release="${release}" -a toc=left ${extraargs} -b xhtml5 -d book -B "documentation/${basedir}/" "documentation/${basedir}/${basefile}" -o "${doc}.html" -D "../../website/${release}" 2>&1 | grep -v 'Try: gem'

# Build the documentation PDF
asciidoctor-pdf -a release="${release}" -a toc=left ${extraargs} -d book -B "documentation/${basedir}/" "documentation/${basedir}/${basefile}" -o "${doc}.pdf" -D "../../website/${release}" 2>&1 | grep -v 'Try: gem'
~~~

The HTML version looks fine: https://openshift-kni.github.io/baremetal-deploy/4.6/Deployment.html#configuring-the-install-config-file_ipi-install-configuration-files

However, the PDF version shows the html entities:

![image](https://user-images.githubusercontent.com/312463/96568754-92c3d980-12c8-11eb-8d25-06e09e587c2f.png)

Is there something that should be changed in the source document or invocation of asciidoctor-pdf or is it a bug?

Thanks

**Comment by mojavelinux** [comment]
You cannot use both embedded HTML and syntax highlighting in the same block when converting to PDF. That's just a limitations of how the technologies combine. It works for HTML because the syntax highlighting can be done in an HTML environment where the syntax highlighter is smart enough to be able to work around the HTML tags. But it's not something that can be done in the PDF generation pipeline.

If this is really important to have, you could extend the converter and try to figure out what you need to do to get the links to work. However, I don't know off the top of my head what you would need to do.

**Comment by iranzo** [comment]
Thanks @mojavelinux, would it be an easy way to disable syntax highlighting only for PDF? the HTML version works as intended: both colours and the internal links to the section containing the detailed explanation.

We make the PDF available for offline access, so I would consider inline links more important here than the colouring of the code itself.

Thanks for any pointer

**Comment by mojavelinux** [comment]
One way is to disable it globally by unsetting the `source-highlighter` attribute. You could also disable it on a per block basis using:

```
[source,yaml]
ifdef::backend-pdf[[listing]]
```

(or any ifdef that would effectively disable the language attribute on the block).

**Comment by iranzo** [comment]
![image](https://user-images.githubusercontent.com/312463/96574183-69f31280-12cf-11eb-8467-aad3a72c4277.png)


That seemed to do the trick, thanks a lot!

PD: File at: https://deploy-preview-539--baremetal-deploy.netlify.app/4.6/Deployment.pdf
