### ISSUE TITLE
Support prawn-svg 0.31.0 for v1.5.x

### ISSUE THREAD

**Issue by pevik** [asciidoctor/asciidoctor-pdf#1810]
Could you please backport support prawn-svg 0.31.0 for v1.5.x? (looks to me only 25755dc1387a991a05902cb44e658b9796e5d813).
Motivation: https://github.com/asciidoctor/asciidoctor-pdf/issues/1732 (https://github.com/mogest/prawn-svg/issues/125).

BTW I haven't seen prawn-svg setup in CI. Maybe worth of adding.
(I could try to add both, but probably faster for you to implement it yourself than reviewing and fixing my work.)

**Comment by mojavelinux** [comment]
Right now I am minimizing any more investment in 1.5.x because the focus is on the 2.0 release. If you submit a PR and verify that it works without changing any tests, then I would accept it.

> BTW I haven't seen prawn-svg setup in CI. Maybe worth of adding.

There's no need. It is a runtime dependency of asciidoctor-pdf, so it gets installed and tested by default.

**Comment by mojavelinux** [comment]
Resolved by #1861.
