### ISSUE TITLE
Can I somehow move the chapter and section numbers to the left, before the left text margin?

### ISSUE THREAD

**Issue by kwoot** [asciidoctor/asciidoctor-pdf#1865]
Hi,

Currently working on an asciidoctor-pdf theme for a large organization.

Their numbering is as follows:
In the toc:
```

     1       New subject - 5
     1.1     Some paragraph title - 7

     2       Other new subject - 8
     2.1     Some other paragraph title - 9

```
And the same in the doc (but without the page number of course).
```
     1       New subject
             This is where my lorem ipsum starts

     1.1     Some paragraph title
```

Is there currently support for this somehow?

**Comment by mojavelinux** [comment]
That kind of advanced layout is not something Asciidoctor PDF can or will be able to do out of the box. You have two options. First, you can extend the converter and implement your own layout logic. However, I will warn you that implementing that logic requires considerable effort. Second, you can try https://github.com/Mogztter/asciidoctor-web-pdf[Asciidoctor Web PDF] which gives you much more control over layout since it is web-based.

**Comment by kwoot** [comment]
Thank you so much! For the awesome asciidoctor-* sw and also for this tip. He had not heard about that project before and will definitely check it out. Thanks!
