### ISSUE TITLE
v1.5.x branch supporting recent dependencies

### ISSUE THREAD

**Issue by pevik** [asciidoctor/asciidoctor-pdf#1871]
v1.5.x branch require old dependencies:
* ttfunk: v1.5.x being locked on 1.5 due ttfunk 1.6 not compatible with Ruby 2.3 (latest release 1.7.0)
* prawn: v1.5.x requires 2.2.2 (latest release 2.4.0)

There are also other old dependencies
* ttfunk 1.5.1 (latest release 1.7.0)
* prawn-icon 2.5.0 (latest release 3.0.0)

Is the purpose of v1.5.x branch to stay on old Ruby versions? Or it's just it'd be difficult to update and thus you don't invest time and work on 2.0? I tried to update, but failed. Due this openSUSE will just have to wait till 2.0 which can be packaged (package maintainers refuse to package old versions).

**Comment by mojavelinux** [comment]
> Is the purpose of v1.5.x branch to stay on old Ruby versions? Or it's just it'd be difficult to update and thus you don't invest time and work on 2.0?

It's a mix of all of that. Asciidoctor PDF itself is not bound to Ruby 2 in any way. It's the dependencies that are the problem. Unfortunately, by upgrading prawn and ttfunk, it forces older versions of Ruby to be dropped, which is a breaking change for this library. And there have also been other changes in prawn that broke most of the tests. On top of that, the master branch has diverged so much from v1.5.x that it's extremely tedious to backport changes. So v1.5.x is staying how it is.

I've wanted to have Asciidoctor PDF 2 out for months, but my time has been limited. My intention is to get the final changes in soon so that I can at least make a prerelease. That's all I can tell you.

**Comment by mojavelinux** [comment]
Btw, all of these upgrades have been applied to the master branch already.

**Comment by pevik** [comment]
Thanks for all the info. Asciidoctor PDF 2 will solve these problems. Sure, I notices changes in the master branch before opening the ticket. But as you noticed I wasn't sure what else to backport, because tests are failing with just upgrading the dependencies. BTW Debian is using v1.5.4 with a newer (but not the latest) dependencies: prawn 2.3.0 and ttfunk 1.6.2.1
https://salsa.debian.org/keithp/asciidoctor-pdf/-/blob/1.5.4-1/debian/patches/0004-Update-gemspec-dependencies-to-match-debian-packages.patch
https://packages.debian.org/sid/ruby-asciidoctor-pdf
And even remove prawn-templates
https://salsa.debian.org/keithp/asciidoctor-pdf/-/blob/1.5.4-1/debian/patches/0001-Fix-dependencies-for-debian-build.patch
I'll have a look what is needed for working with the latest releases (prawn 2.4.0 and ttfunk 1.7.0) and if fail, openSUSE users will just have to wait for Asciidoctor PDF 2.

**Comment by mojavelinux** [comment]
I realize the situation is complicated. Prawn didn't have a release for the longest time, then it came out with a release that broke many things. It's frustrating, but it's the hand we were dealt.

It's not going to be easy to update the tests because, like I said, the changes to Prawn broken almost every visual test. The changes were subtle, so it's not like they are visible to the user. But it was enough to invalidate the reference files.

The best I can do is fix it in master. v1.5.x is just going to be a problem because of the restrictions / limitations in the dependency matrix.

**Comment by pevik** [comment]
You have support for latest gem releases in master, that's enough (it gets released in Asciidoctor PDF 2). I don't want to take your limited time for v1.5.x fixes (and thus postpone Asciidoctor PDF 2).

But for next "stable" release it'd be great to keep it working with newer releases (if doable not like now), due security as requiring old dependencies is generally requiring security problems.

**Comment by mojavelinux** [comment]
That's exactly the plan. Once 2.0.0 is released, it will mark a switch to semantic versioning, where we will have room to make updates to track dependencies with major version delineations as necessary. There is a balance to be achieved between braking compatibility and avoiding security vulnerabilities which semantic versioning has proved effective in striking.
