### ISSUE TITLE
Table without grid and frame still showing a grid line

### ISSUE THREAD

**Issue by vonas** [asciidoctor/asciidoctor-pdf#1873]
I have my table configured with `grid="none"` and `frame="none"`, yet it still contains a horizontal grid line in the middle of the table. Reordering the table options did not help.

Find my minimal example here: [**vonas/asciidoctor-pdf-issue-1873**](https://github.com/vonas/asciidoctor-pdf-issue-1873)

This is my [input](https://github.com/vonas/asciidoctor-pdf-issue-1873/blob/master/sample.adoc) and the corresponding [PDF output](https://github.com/vonas/asciidoctor-pdf-issue-1873/blob/master/erroneous.pdf):

```adoc
[frame="none",grid="none"]
|===
|Foo |Bar

|Tasty
|Strong

|Fluffy
|Sweet

|Muscular
|Tall

|===
```

![image](https://user-images.githubusercontent.com/24623262/106390297-fa211780-63e7-11eb-9f95-4901deb57837.png)

**Comment by mojavelinux** [comment]
The line you are seeing is the separator between the table header row and the table body. This line is always present unless disabled in the theme. The reason it is appearing below the second row is due to a bug in v1.5.x that has been fixed in master (and thus fixed in the upcoming release). It's mentioned in the CHANGELOG.

As to whether the line below the head row should be present when the grid is disabled is another matter. If we turn it off, other people will want it back. I don't know of a good solution.

**Comment by vonas** [comment]
Okay, that's great, thanks for pointing that out to me. &ndash; Should've checked how the master branch handles this before reporting.

I'll close this.

**Comment by mojavelinux** [comment]
I'll add an issue reference to the CHANGELOG to complete the circle.
