### ISSUE TITLE
Theming bibliography

### ISSUE THREAD

**Issue by odrotbohm** [asciidoctor/asciidoctor-pdf#1889]
My overall document uses text align justify. For the bibliography though, I'd rather switch to `left` but that currently doesn't seem to be supported.

**Comment by mojavelinux** [comment]
I'm happy to share that this is what the converter does by default for bibliography lists. See https://github.com/asciidoctor/asciidoctor-pdf/blob/39c0ffbaede17f4219e5a62e4dc8648b10134e1f/lib/asciidoctor/pdf/converter.rb#L1367-L1368. However, the list does have to be designed as a bibliography. Otherwise, the converter cannot recognize it.

To make the list a bibliography, you must add the bibliography style either to the section that contains it (preferred):

```asciidoc
[bibliography]
== Bibliography

* [[[bar]]] Bar, Foo. All The Things. 2010.
```

or directly on the list itself:

```asciidoc
== Bibliography

[bibliography]
* [[[bar]]] Bar, Foo. All The Things. 2010.
```

**Comment by mojavelinux** [comment]
@odrotbohm Does that solution work for you?

**Comment by odrotbohm** [comment]
Not sure if I do anything wrong on my end. I am using the Bibtex extension as follows:

```asciidoc
[bibliography]
= Bibliography

bibliography::references.bib[ieee]
```

The result looks like this:

![Bildschirmfoto 2021-03-18 um 16 13 42](https://user-images.githubusercontent.com/128577/111649944-21e80580-8805-11eb-8f8c-60685a7c8ede.png)

The second entry seems to indicate that the text is still using justified alignment.

**Comment by mojavelinux** [comment]
Aha! That's the detail I was looking for. I didn't realize you were using something else to generate the bibliography.

This turns out to be a shortcoming of asciidoctor-bibtex itself. It's not creating a list using the document model, so we have no way to recognize it as a bibliography list in Asciidoctor PDF. Instead, it's making a single paragraph for each bibliography item. Furthermore, it's not honoring the role set on the bibliography macro itself, so it's not even possible to pass in the `text-left` role to force the alignment on those paragraphs.

This is a problem that needs to be dealt with in asciidoctor-bibtex. It really shouldn't be creating multiple paragraphs. Instead, it should be constructing an unordered list with the bibliography role and letting the converter handle the formatting. It's important that extensions work in a way that is compatible with converters. Otherwise, the converters cannot properly format the document.

**Comment by odrotbohm** [comment]
Thanks for the explanation, Dan. I'll open a ticket with the bibtex extension.

**Comment by odrotbohm** [comment]
I've monkey-patched asciidoctor-bibtex (see asciidoctor/asciidoctor-bibtex#84). Not a serious suggestion for a fix, but does the trick for me for now.

**Comment by mojavelinux** [comment]
Nice. I'll follow up there.
