### ISSUE TITLE
asciidoctor-pdf hangs with no error message and no reason

### ISSUE THREAD

**Issue by mariuszpala** [asciidoctor/asciidoctor-pdf#1905]
Hi, 

I have a quite a large documentation to generate, it was working fine last time and now after recent additions it hangs taking all the CPU. There is no error message or any debug output that could help troubleshooting the issue. I'm using lateste 1.5.4 version. 
`asciidoctor-pdf --failure-level INFO --trace -v -t -a my.adoc`

I found another similar issue where the cause was \r existing in the files. I used dos2unix tool to make sure there are no such characters. Nevertheless, the issue still persist and I cannot generate my documentation. Any help appreciated!

I can share my files via PM (59mb). Thank you.

**Comment by mariuszpala** [comment]
Found the issue, looks like on of tests is generating a text file with the binary response - attached. 
Since I have hundreds of files it took me a while to find it. Can the tool fail if there is some character that causes issues instead of hanging indefinitely?
[http-response.txt](https://github.com/asciidoctor/asciidoctor-pdf/files/6249497/http-response.txt)

**Comment by mojavelinux** [comment]
If Prawn (the PDF generator library) encounters an error, it will be raised, but can sometimes take a long time to propagate. This is outside of the control of this converter. The problem originates deep within Prawn and likely has something to do with how Ruby works.

I ran Asciidoctor PDF on the file you provided and I was not able to reproduce the problem. If you can submit a test that demonstrates the hang, and I'm able to verify the problem is, in fact, coming from this converter, I will investigate a possible code change. Otherwise, there's no much I can do.

**Comment by mojavelinux** [comment]
I can't reproduce this issue, even with the provided sample file. Unless you can provide me with a reproducible test case, preferably in Asciidoctor PDF's own test suite, there is nothing I can do to address it. Please reopen if/when you can provide that test case.
