### ISSUE TITLE
cover page (back) can appear on even and uneven page

### ISSUE THREAD

**Issue by pdorrestijn** [asciidoctor/asciidoctor-pdf#1914]
If you were to print your nice asciidoc generated pdf with a cover, the cover page at the end could very well be on the inside...
Was that intended?

**Comment by pdorrestijn** [comment]
Ah, found it! Don't know why I overlooked this toggle to avoid such problems.
:media: prepress

**Comment by pdorrestijn** [comment]
unfortunately :media: prepress only seems to add a blank page (with background image :( ) to the book.
thus issue remains, cover page is not automatically put on the right page for printing books.

desired would we a toggle to specify a preference like add a blank page at the beginning (maybe with meta data, toc?) or just before the cover, or nothing when the last cover page would appear on an uneven page.

**Comment by mojavelinux** [comment]
My understanding is that the cover pages are typically printed separately. So instead of including the cover page in the prepress output, we offer a way to generate the PDF with no cover pages as though the cover pages are present. Here's what the documentation has to say about it:

> To apply the recto margin to the title page, but not include a cover, assign the value ~ to the front-cover-image and back-cover-image attributes.

This essentially makes a coverless PDF. You can then add the cover pages using another PDF tool however you like.

Here's the context behind that behavior: https://github.com/asciidoctor/asciidoctor-pdf/issues/793#issuecomment-290907119

If you have an idea for how Asciidoctor PDF can be configured to add these cover pages for this scenario, please offer a proposal.
