### ISSUE TITLE
theme a specific table to scale with 50% when role is applied ?

### ISSUE THREAD

**Issue by arcusbude** [asciidoctor/asciidoctor-pdf#1954]
is it possible to scale a table down to 50% because it not fits to an a4 page when rendering as is, based on "role" ?

i have an complex table exported via doctoolchain exportExcel plugin, with spanned cells and so on. it shows good at html output but pdf output is broken because the page break. also the first line is repeated on next page, obvously i dont want that.

so a simple scale to 70% or 50% could be a solution for me

**Comment by arcusbude** [comment]
i know there is an solution which is not ready (ascidoctor-web-pdf) but i need some workarround for now ;)
also some hack in doctoolchain or asciidoctor code is welcome ;)

**Comment by mojavelinux** [comment]
No, it's not possible to scale tables in Asciidoctor PDF.

**Comment by mojavelinux** [comment]
What you could do is render the table in a document by itself that specifies a larger page size (like A3).

    $ asciidoctor-pdf -a pdf-page-size=A3 big-table.adoc

(The page size can be very exact).

Then, you can import that PDF page into the main document using the block image macro.

```
image::big-table.pdf[]
```

That way, the table will be arranged on a larger page than the rest of the document. Instead of scaling the table down (which is not possible), you can scale the size of the page up.

> also the first line is repeated on next page, obvously i dont want that.

This is a very typical practice for print layout documents to help the reader identify the columns. If you don't want that behavior, don't use the header row of the table.

If you need more assistance, please ask your question in the project chat at https://chat.asciidoctor.org.
