### ISSUE TITLE
Landscape mode breaks Appendix 

### ISSUE THREAD

**Issue by haekelhexe** [asciidoctor/asciidoctor-pdf#1962]
Hi there, 
I created a document with several chapters and appendices, that I put together with an include: 
```
[appendix]
include::Appendix_Number_Registers_for_Routing_Config.adoc[]
[appendix]
include::Appendix_Routing_Commands.adoc[]
[appendix]
include::Appendix_Status_Report_Code.adoc[]
```
For one Appendix, I had to use the landscape mode by using 
```
[.landscape]
<<<
== Routing Commands
```
But this resulted in this appendix being ignored as Appendix but rendered as normal chapter. 
![grafik](https://user-images.githubusercontent.com/44695566/131641014-07faed06-ff44-428c-aea0-99b170ce3697.png)

Any idea how to solve this?

**Comment by mojavelinux** [comment]
Given the input you have provided, this is the expected behavior. The include file for Routing Commands starts with a page break. That means the `appendix` style is applied to the page break block instead of the section title. As a result, the parser sees this as a normal section, not an appendix.

This is the correct syntax:

```
[.landscape]
<<<

[appendix]
== Routing Commands
```

Generally, I recommend against adding a block style outside of the include directive as it makes the intent less clear. If it has to be dynamic, then hide the block style inside a preprocessor conditional instead.

**Comment by mojavelinux** [comment]
Another approach is to move the page break to the parent document, still above the `[appendix]` line.
