### ISSUE TITLE
Index customizer broken in 1.6.x?

### ISSUE THREAD

**Issue by rpavlik** [asciidoctor/asciidoctor-pdf#1976]
Had to adjust my docker images today for building stuff, and I noticed that my index customizer script (originally devised in #1174 - now listed in the README) was failing because of not finding `uppercase_mb`:

```
undefined method `uppercase_mb' for #<Asciidoctor::PDF::IndexCatalog:0x0000557242ea0f60>
Did you mean?  uppercase_pcdata
  Use --trace for backtrace
```

From here, it looks like the `upcase` method is probably what we want to use? Looks like that's a standard Ruby string method, so probably wasn't being used before due to not being in the oldest supported ruby?

https://my.diffend.io/gems/asciidoctor-pdf/1.5.4/1.6.0#d2h-121859

if so, the README should be updated.

**Comment by mojavelinux** [comment]
You're correct that uppercase_mb was a patch to provide proper Unicode support for the `String#upcase` method. Any custom code should be using APIs provided by Ruby, not private methods in Asciidoctor PDF. Since this method was always private, I don't feel there is a needed to mention it in the README. However, I would consider adding a mention of it to the CHANGELOG file. The commit you are looking for is 7e9e0bbe9f4ddad41b38725c607588c65618ebae. If you'd like this to be mentioned in the CHANGELOG, feel free to submit a PR to add it.

**Comment by rpavlik** [comment]
Thanks for the quick response! #1977 fixes the reference in the README to uppercase_mb. (It was already there) No idea if anyone else hit this, I didn't realize it was a private method, but it might be worth putting in the changelog. I'll add that to my PR.

**Comment by mojavelinux** [comment]
Ah. I now see what you are referring to. That was definitely a mistake to use uppercase_mb in that example as that is not a method that should have been exposed.

**Comment by mojavelinux** [comment]
PR merged. Thanks!
