### ISSUE TITLE
Table font size not applied to literals used inside the table

### ISSUE THREAD

**Issue by odrotbohm** [asciidoctor/asciidoctor-pdf#1978]
I've defined the following settings in my theme:

```
table:
  font_size: $base_font_size * 0.7
```

When I define a table like this:

```
|====
|Some text|`Some literal`
|====
```

"Some text" gets the size reduction applied, `Some literal` is still rendered in the originally defined font size (via `literal.font_size`).

Using a 2.0 build built locally from roundabout two weeks ago.

**Comment by odrotbohm** [comment]
The same applies to captions of source blocks. I.e. a

```
caption:
  font_size: $base_font_size * 0.8
```

does not get applied to literal also sees the font size defined for `literal` as is, not additionally reduced by a factor of 0.8.

**Comment by mojavelinux** [comment]
> The same applies to captions of source blocks

Although admittedly odd, this is the expected behavior since the caption does not apply font scaling. Rather, it sets the font size for "prose" text. It's the same for paragraphs. In order to support the reduction of the font size of a code span relative to the parent element, the same font scaling logic applied to tables would have to be applied everywhere...which is not something I'm planning to do right now.

I can see supporting the first issue you reported as we do expect the font to be scaled uniformly in a table. But it isn't going to change relative sizes.

**Comment by mojavelinux** [comment]
Aha! I did some more digging and I now remember where we left this. Inline elements do not have access to the font scale on the document and thus exempt from it. **However**, inline elements can be configured to have a font size that's relative to the current font size or root font size by using the `em` and `rem` units, respectively (just like in CSS).

Thus, if you use the following setting in your theme, you will get (very close) to the result you expect:

```yaml
literal:
  font_size: 0.85em
```

I'll update the theme to emphasize this recommendation.

Applying the font scale to fixed font sizes universally is still a big challenge since font scale was added to the theming system well after its initial design. I can see where we can set it, but adding breaks a lot of assumption and tests.

**Comment by odrotbohm** [comment]
I can report that using `0.85em` as value fully solves the problem both for captions as well as for table content. Might be a sole documentation issue then?

**Comment by mojavelinux** [comment]
Yeah!!

Knowing what we know about the state of converter and what it would take to support scaling of fixed font sizes, I'm going to say that this is a documentation issue for now. I've noted it down to look into the idea of redesigning font scaling so that it can be universal, but it's a big task and not one I'm prepared to take on right now.

We'll be sure to highlight this recommendation very visibly in the new docs for Asciidoctor PDF 2.
