### ISSUE TITLE
cannot find fonts when running from inside a container

### ISSUE THREAD

**Issue by am21** [asciidoctor/asciidoctor-pdf#2015]
I am using the latest container asciidoctor/docker-asciidoctor from hub.docker.com, which contains asciidoctor-pdf 1.6.2.

asciidoctor-pdf fails with: (only latest part of the trace)
```
No such file or directory - /usr/lib/ruby/gems/3.0.0/gems/asciidoctor-pdf-1.6.2/data/fonts/notoserif-regular-subset.ttf not found (Errno::ENOENT)
        from /usr/lib/ruby/gems/3.0.0/gems/asciidoctor-pdf-1.6.2/lib/asciidoctor/pdf/converter.rb:3608:in `each'
        from /usr/lib/ruby/gems/3.0.0/gems/asciidoctor-pdf-1.6.2/lib/asciidoctor/pdf/converter.rb:3608:in `each_with_object'
        from /usr/lib/ruby/gems/3.0.0/gems/asciidoctor-pdf-1.6.2/lib/asciidoctor/pdf/converter.rb:3608:in `block in register_fonts'
        from /usr/lib/ruby/gems/3.0.0/gems/asciidoctor-pdf-1.6.2/lib/asciidoctor/pdf/converter.rb:3607:in `each'
        from /usr/lib/ruby/gems/3.0.0/gems/asciidoctor-pdf-1.6.2/lib/asciidoctor/pdf/converter.rb:3607:in `register_fonts'
        from /usr/lib/ruby/gems/3.0.0/gems/asciidoctor-pdf-1.6.2/lib/asciidoctor/pdf/converter.rb:328:in `init_pdf'
```

But the file is there:

```
bash-5.1# ls /usr/lib/ruby/gems/3.0.0/gems/asciidoctor-pdf-1.6.2/data/fonts/notoserif-regular-subset.ttf
/usr/lib/ruby/gems/3.0.0/gems/asciidoctor-pdf-1.6.2/data/fonts/notoserif-regular-subset.ttf
```

Any idea?

**Comment by mojavelinux** [comment]
It sounds to me like this is a volume mapping issue. You may be mapping the volume in such a way that it cannot access the location of the font file anymore. I've seen cases where the message is misleading because one filesystem is fused into the other, so when you check the path after the fact it is present. You need to inspect the filesystem location while Asciidoctor is running, from within the container.

In the future, please direct questions about using the software to the project chat at https://asciidoctor.zulipchat.com. If you repost your question there, others might be able to chime in to help you debug it.
