### ISSUE TITLE
Cross reference takes attributes (bold, italic) from the title

### ISSUE THREAD

**Issue by rlopez133** [asciidoctor/asciidoctor-pdf#202]
If I cross reference a title that is say in italics, the cross reference also has the attribute (which I do not want.)

Example

```
[[tempest]]
== _Tempest_
Info about tempest

== _Rally_

=== _Before you Begin_

* <<refA>>
* <<refB>>
* <<tempest>>

```

Since my refA and refB where not italized, but my tempest title was, it looks awkward in the list. 

Output:
![selection_221](https://cloud.githubusercontent.com/assets/8877333/8185536/a0b9a258-140a-11e5-8a7d-548bb2d740b1.png)

**Comment by mojavelinux** [comment]
I'll start of by saying that this behavior is as designed. What we need to question is whether it is the right design. If not, this is a change that we need to make to Asciidoctor core.

A quick workaround for this is to provide your own text at the stop of the reference:

```
<<tempest,Tempest>>
```

That's probably how most people have been dealing with it thus far.

It seems pretty reasonable to me that the reference text would not take on the styling of the heading (after all, it doesn't show it in larger text, so why take the other styling). I do think we need some substitutions. For instance, we probably want to substitute, then strip out any formatting in the final result (santization if you will).

In your particular case, though, is there a reason you are explicitly making the heading text italic instead of using the theme? In other words, are the heading italicized for styling or for semantic meaning?

**Comment by mojavelinux** [comment]
Here's how you can style the headings from the theme:

http://gist.asciidoctor.org/?github-asciidoctor%2Fasciidoctor-pdf%2F%2Fdocs%2Ftheming-guide.adoc#heading

**Comment by mojavelinux** [comment]
I've filed an issue in core to discuss.

https://github.com/asciidoctor/asciidoctor/issues/1370

**Comment by rlopez133** [comment]
I'm just using italics for styling nothing more. Glad to know there is a workaround. :)

**Comment by mojavelinux** [comment]
Cool. So in your case I definitely recommend moving the styles to the theme. Then you should get the result you expect in the xref.

**Comment by mojavelinux** [comment]
Since styling via the theme can be used to avoid this issue, and an issue has been opened upstream to discuss stripping the formatting from the implicit reftext, I'm going to mark this one as closed.

Here's the theming example:

```
extends: default
heading:
  font-style: italic # or bold_italic
```
