### ISSUE TITLE
How to handle emphasis in code blocks when source highlighter is enabled

### ISSUE THREAD

**Issue by odrotbohm** [asciidoctor/asciidoctor-pdf#2086]
The following source code block:

```
[source, java, subs="+quotes"]
----
interface OrderRepository extends … {

  @Query("…")
  *Seq<Order>* findByComplexQuery(…);
}
----
```

Renders fine by adding emphasis to the `Seq<Order>` when not using a source highlighter (in prepress rendering). The source highlighter however turns this into:

```java
interface OrderRepository extends ... {

  @Query("...")
  <strong>Seq<Order></strong> findByComplexQuery(...);
}
```

Note the superfluous `<strong>` element. What's the best way to set this up in a way to render the emphasis if no source highlighting is enabled but simply avoid them if it is?

**Comment by mojavelinux** [comment]
This is a known issue that subs cannot be combined with source highlighting in the PDF converter. I don't know how to solve it because the two technologies both modify the source code at different phases. My advice is to not try to mix these two things. But if you can figure out what would need to happen to accommodate this use case in the Rouge adapter [https://github.com/asciidoctor/asciidoctor-pdf/blob/main/lib/asciidoctor/pdf/ext/rouge/formatters/prawn.rb](here), I'm open to applying the patch for it.

**Comment by mojavelinux** [comment]
The reason this comes up in the PDF converter is because the substitutions are applied before the source is highlighted. Thus, the HTML tags are present in the source that is passed to the syntax highlighter. It treats these tags just like language tokens (e.g., `<strong>` and <Order>`) are indistinguishable. And once the source is tokenized, it is never converted back to a string.

This works in the HTML converter because the syntax highlighter runs before all the subsitutions are applied. But in this case, the syntax highlighter converts the result back to a string. So the trailing substitutions are applied once again to a string, allowing additional HTML to be weaved in.

To try to emulate that same behavior in the PDF converter would be extremely complicated. It would mean differing the trailing substitutions, then walking the token array and trying to find AsciiDoc syntax. I can't even begin to think how that would be done.

As a compromise, what we could do is detect that additional HTML tags have been inserted into the source, strip them out, then proceed with syntax highlighting. That would at least prevent the tags from being passed through unprocessed, in source form. I'm open to that approach.
