### ISSUE TITLE
There is a lot of blank space between English and Chinese when converting to PDF 

### ISSUE THREAD

**Issue by GentleHe** [asciidoctor/asciidoctor-pdf#2108]
Excuse me!When I use Asciidoc, I use space between Chinese and English words to make my layout more beautiful, but when I convert ADOC to PDF, there is a lot of space between Chinese and English because I add a space (sometimes this happens, sometimes it doesn't). See pictures I posted). Is this related to text alignment? If not, what should I do?

![prob1](https://user-images.githubusercontent.com/40768488/166100959-423654f9-4799-4220-9c61-ade12280cb6c.png)
![prob2](https://user-images.githubusercontent.com/40768488/166100962-f8bcb4a0-ec66-44ea-8984-09aa27bd3703.png)
![prob3](https://user-images.githubusercontent.com/40768488/166101094-694e1829-7090-4a40-bde3-99678d3e210b.png)

**Comment by GentleHe** [comment]
Let me make a few points
1. I'm using the ADOc plugin for IDEA to convert PDF, but they use asciidoctor-pdf.jar
2. My preferred font to use is the recommended KaiGenGothicCN
3. This happens in Figure 2 and figure 3. Sometimes there is a lot of white space, sometimes just a normal blank space

**Comment by mojavelinux** [comment]
You need to set `-a scripts=cjk` so that break opportunities are inserted between the Chinese characters. This is covered in the docs. See https://github.com/asciidoctor/asciidoctor-pdf#support-for-non-latin-languages

In the future, please ask usage questions in the #users/asciidoctor-pdf stream in the project chat at https://chat.asciidoctor.org. Thanks!
