### ISSUE TITLE
Arbitrary TOC entry macro

### ISSUE THREAD

**Issue by nuket** [asciidoctor/asciidoctor-pdf#2127]
Is it possible to add a macro that, when encountered, adds an entry to the Table of Contents with user-specified text and serves as a jump target for the link created in the TOC?

At the moment, the only way to add entries to the TOC seems to be using Heading blocks, which are not always ideal.

e.g.
toc_entry::[text='An Arbitrary Table Entry', level=3]

`text` would be mandatory and could be the first positional option, `level` could be optional.

This enhancement request comes up after learning how to insert arbitrary, individual PDF pages, where heading text could already be a part of that PDF page and it would be odd to include it again in the following `.asciidoc` file, but for which there is no other way to get a jump target and TOC entry to that page.

https://github.com/asciidoctor/asciidoctor-pdf/issues/177
https://github.com/asciidoctor/asciidoctor-pdf/issues/1202

**Comment by mojavelinux** [comment]
I have documented how to add additional entries to the TOC using an extended converter. You can find the example code at the following location: https://github.com/asciidoctor/asciidoctor-pdf/blob/main/docs/modules/extend/examples/pdf-converter-additional-toc-entries.rb This example, as well as numerous others, will be included in the documentation for Asciidoctor PDF 2.0.0 when it is released.

Since the rules for adding additional entries to the TOC can vary widely, I think this functionality is best left up to an extended converter.
