### ISSUE TITLE
Option to enable borders and padding for collapsible blocks

### ISSUE THREAD

**Issue by edward-encoord** [asciidoctor/asciidoctor-pdf#2214]
I personally like the borders and padding for collapsible blocks in version 1. I like to put multiple blocks and paragraphs in a collapsible block. If there is no border, it's hard to see if a block/paragraph is inside a collapsible block.

**Comment by mojavelinux** [comment]
That's not the indented use of the collapsible block. If you want a decorated block, you should just use a regular example block.

The collapsible block is only meant to hide and reveal other content. In PDF, it should match the display of an open collapsible block in the HTML output. However, when examining what this converter produces, I realized that it was not meeting that requirement. I have opened #2219 to address that inconsistency. I think you may find that the fix for that issue addresses your concern that it's hard to see what is inside the collapsible region. I agree that is currently a problem.

That said, I'm not sure the collapsible block even makes much sense in the PDF output. You might want to just filter out the option using `ifndef::backend-pdf[]`. The converter is primarily focused here on being true to how the block appears in HTML in the open state without the behavior attached to it.

**Comment by edward-encoord** [comment]
> You might want to just filter out the option using `ifndef::backend-pdf[]`.

Thanks for the advice. In the meantime, I think it's good to have out-of-box support for collapsible block in PDF like #2219.
