### ISSUE TITLE
Allow theming to define a line number threshold for breakability for source code blocks

### ISSUE THREAD

**Issue by odrotbohm** [asciidoctor/asciidoctor-pdf#2304]
I find myself defining the `%unbreakable` option for *short* code blocks a lot as it looks weird if only a few lines are kept on the original page. Even for longer source code blocks, it would be nice to define a threshold for the number of lines I think are acceptable to move over to the other page as I think the resulting white space of the code now moving to the new page is bearable.

In other words, I would like to be able to set e.g. the threshold to 10, meaning that if the page breaks are applied in a way that if up to only 10 lines appear on the first page, consider the block unbreakable and just move it over to the next page completely. That would give me essentially a maximum of ten lines of source code length of whitespace at the end of a page.

Another option would be to offer a setting for the number of lines until the overall block is considered breakable. A 10 for that would consider source blocks up to 10 lines unbreakable, everything beyond that breakable.

**Comment by mojavelinux** [comment]
The breakable/unbreakable logic is already extraordinarily complicated, and I'm not looking to add more complexity to it. There's also no easy way to know how many lines were placed on a page to know whether it was too few. We just know that it did or didn't fit.

I do see two options that we could explore that would at least give you some control.

One idea is to be able to specify how much room must be left on the page (a fixed value) to start a code block on that page. That would allow you to avoid the problem of having the code block get split after 1 or 2 lines. The key could perhaps be named `code-min-height-start`. We would ignore this setting if the code block has only 1 line since a single line code block is never split (and thus has the opportunity to fit even if there isn't the requisite amount of room remaining on the page).

Another idea is to be able to specify a line threshold that makes a code block automatically breakable. If the code block has no more than this number of lines, it won't break. The key could perhaps be named `code-breakable-min-lines`.

The problem with the second option is that it does not address the case when the first line of a long code block is orphaned. That's why I think the first option gets you most of the way there.

**Comment by odrotbohm** [comment]
We definitely don't have to make it more complex than necessary. I just found myself marking all rather short code blocks with `%unbreakable` to avoid the split into two even shorter parts and thought, it might be neat to be able to prevent that by default. I didn't even think about longer code blocks with potentially very few lines before the break before filing the issue and thinking about other scenarios.

The `code-min-height-start` would nicely solve both scenarios IIUC. If it's easier to implement, even better.

**Comment by mojavelinux** [comment]
> The `code-min-height-start` would nicely solve both scenarios IIUC. If it's easier to implement, even better.

Great! I'll see what I can do.

> We definitely don't have to make it more complex than necessary.

Let's just say that Asciidoctor PDF finds a way to challenge me every day ;)

**Comment by mojavelinux** [comment]
After doing some testing, it became clear that these two options are mutually exclusive and thus both necessary. Here are the names I arrived at:

* `code-breakable-min-lines`\
the minimum number of lines a code block must have in order to be breakable; default is 2
* `code-orphans-min-height`\
the amount of usable space that must be remaining on the page (below the caption) in order to start a code block; default is 0

I think these two options give you a very reasonable amount of control over how code blocks break. We might even be able to extend them to other blocks in the future, but let's see how this goes first.

It's important to not that there's nothing we can do about widows. Once a page is used, it's used.

**Comment by mojavelinux** [comment]
I haven't decided what milestone to put this in. I'd prefer it to be 3.0.x, but I might be able to be convinced otherwise.

**Comment by odrotbohm** [comment]
Thanks for the insight, Dan. Option names look fine to me. No particular vote on the version. The project I'd use this in first uses a binary built from source anyway. Happy to give this a spin pre-release.

**Comment by mojavelinux** [comment]
We'll go with Asciidoctor PDF 3.0, which isn't long off. This PR will be a two-parter, so I'll reopen to let the next one close it.

**Comment by mojavelinux** [comment]
Both parts are in!
