### ISSUE TITLE
Can't control PDF TOC output location

### ISSUE THREAD

**Issue by wolandscat** [asciidoctor/asciidoctor-pdf#233]
I am unable to prevent the TOC coming out as the very first set of pages in the PDF. I want them in a controllable location later in the document (after Amendments table, Acknowledgements).

I tried `:toc: macro` at the top, and `toc::[]` at the desired location, but this has no effect. Ideally I need a solution that also enables the same source to generate an HTML output with TOC on the left. I don't mind invoking asciidoctor with different command lines if need be to achieve this.

UPDATE: I discovered that if I put :toc: macro below the title heading (first = xxxx line), that no TOC at all comes out even with the toc::[] later on. No idea what is going on now. Why does it matter where the :toc:  line goes?

**Comment by hmflash** [comment]
Related to #187 

+1 to being able to position the TOC after amendments/acknownegements/abstract

**Comment by mojavelinux** [comment]
Currently the location of the toc cannot be controlled in PDF. Part of the reason is that it's very complicated to calculate the page offsets as it is, and moving it makes it even more complicated. We just need some better abstractions so that moving the toc around doesn't break other things.

**Comment by eitansuez** [comment]
been working on retrofitting some internal documentation from docbook to asciidoctor.  loving it so far, but not being able to get a copyright notice in the front matter ahead of the toc (pdf) is problematic at best.  any updates on this ticket?  thanks in advance. / eitan

**Comment by mojavelinux** [comment]
What I recommend in the interim is to insert the copyright notice using a PDF combiner library. You can take the PDF and insert a static page before the table of contents. This won't affect page numbering since these are "front matter" pages.

The other option is to extend the converter. You could override the `layout_title_page` method, delegating to super and then adding your own logic to create another page.

**Comment by eitansuez** [comment]
I really appreciate these suggestions / workarounds.  Thanks!

**Comment by mojavelinux** [comment]
Sure thing! If you have questions about how to customize the converter, feel free to ask on http://discuss.asciidoctor.org. There are lots of people there who have done the same.

Btw, you might find PyPDF2 a useful library for injecting additional pages into the generated PDF. I certainly use that from time to time. http://mstamy2.github.io/PyPDF2/index.html

**Comment by igagis** [comment]
So, after resolving this issue the TOC could be place on a numbered page, correct?
Will the page with TOC have ordinary header and footer then? This is the feature I need right now.

**Comment by mojavelinux** [comment]
> Will the page with TOC have ordinary header and footer then? 

That's a separate issue. I don't think moving the TOC around means that it automatically gets a header and footer. That's an orthogonal concern.

**Comment by igagis** [comment]
If TOC appears somewhere in the middle of the document then it should have same header and footer as previous pages, as I understand it... Currently TOC goes before first page, so it is kind of OK that goes out of the general page style...

**Comment by psuzzi** [comment]
Same issue here: I'd like to have a TOC inside my document, but the conversion to PDF does not work. 

Below you see asciidoc code and the expected result in my case. 

![image](https://cloud.githubusercontent.com/assets/352831/16270601/2ef12e2c-3897-11e6-899b-83863ce6ad35.png)

The generated PDF still put the toc on a separate page, at the top

**Comment by mojavelinux** [comment]
> The generated PDF still put the toc on a separate page, at the top

That is an accurate description of the current limitation.

**Comment by ecki** [comment]
For me it would be enough to move the TOC inside the front-matter section. If the page numbers are the problem.

**Comment by mojavelinux** [comment]
When the doctype is article, the TOC should be placed directly after the doctitle, on the same page (if not placed manually). That's a follow-up from #105.

**Comment by mojavelinux** [comment]
With #1029, we're a step closer to getting what we want. While it's still not possible to fully control the location of the TOC, it will now show up where you expect it to. When using the article doctype, the TOC will appear between the doctitle and the content (i.e., inside the document). To restore the previous behavior of dedicated title and toc pages, you can set the `title-page`, which matches the behavior when the doctype is book.

The good news is that more of the necessary foundation is in place for macro placement. Since this issue has diverged into many directions, let's follow up with a separate issue for that enhancement (if it's still needed).

**Comment by mojavelinux** [comment]
See #1030 for a follow-up. We're one step closer to having full control, but the issue needed more focus.
