### ISSUE TITLE
SVG images getting cropped instead of resized

### ISSUE THREAD

**Issue by ponchofiesta** [asciidoctor/asciidoctor-pdf#2342]
I'm converting docx files to adoc using pandoc and then I clean up things.

I'm trying to embed a SVG image. Actually it gets cropped at the bottom and right. PNG images are resized instead.

```
image:media/internal.svg[image,width=214,height=214]
```

Is:
![image](https://user-images.githubusercontent.com/12248938/190385601-10f82f5c-6695-470c-819a-27f3b6638860.png)

Should be:
![image](https://user-images.githubusercontent.com/12248938/190385742-fc4aa664-1af9-4eea-8c70-5f7bcce4f16b.png)

Using:
- asciidoctor-pdf 2.3
- `asciidoctor-pdf -a pdf-themesdir=.. -a pdf-theme=asciidoctor file.adoc`
- Header:
```
= XXX
// Variables
//:revdate: 18.08.2022
:subtitle: XXX
//Document
:appendix-caption: Anhang
:appendix-refsig: {appendix-caption}
:caution-caption: Achtung
:chapter-signifier: Kapitel
:chapter-refsig: {chapter-signifier}
:example-caption: Beispiel
:figure-caption: Abbildung
:important-caption: Wichtig
:last-update-label: Zuletzt aktualisiert
ifdef::listing-caption[:listing-caption: Listing]
ifdef::manname-title[:manname-title: Bezeichnung]
:note-caption: Anmerkung
:part-signifier: Teil
:part-refsig: {part-signifier}
ifdef::preface-title[:preface-title: Vorwort]
:section-refsig: Abschnitt
:table-caption: Tabelle
:tip-caption: Hinweis
:toc-title: Inhalt
:untitled-label: Ohne Titel
:version-label: Version
:warning-caption: Warnung
// German, additional translations
:responsible-label: Herausgeber
:date-label: Datum
:of-date-label: vom
:sectnums:
:sectnumlevels: 5
:!showtitle:
:title-page:
:toc: macro
:toclevels: 4
:pdf-page-size: A4
:doctype: book
:chapter-signifier:
:xrefstyle: full
:icons: font
```

**Comment by mojavelinux** [comment]
Can you please try setting pdfwidth=100% on the macro?

Also, please share the SVG file. Otherwise, I have no way of knowing what
is happening with this SVG.

**Comment by ponchofiesta** [comment]
I can resize the image using pdfwidth=... but it still gets cropped the same way. I created the SVG by converting the WMF file using Inkscape extracted from the docx document. Anfortunally I assume I must not share this file to public. But I deleted main parts of it, kept the border and here it is:

![internal2](https://user-images.githubusercontent.com/12248938/190392814-5a0c22c9-971d-446b-bde8-a0c4340f2ba3.svg)

**Comment by mojavelinux** [comment]
It looks like the problem is that this SVG does not set a viewBox. That is critical information that prawn-svg needs to be able to correctly interpret the SVG data and translate it to PDF objects.

If I try it with prawn and prawn-svg alone, I get the same result.

```rb
require 'prawn-svg'

Prawn::Document.generate 'out.pdf' do
  result = svg File.read 'test.svg'
  puts result[:warnings].join ?\n
end
```

Once you set the viewBox attribute, you will find that it works as expected.

To add a viewBox, open the file in Inkscape, open the Document Properties dialog, expand the viewBox section, and bump one of the values up and down, then save the file as a plain SVG.

You may also notice that prawn-svg is encountering a tag it does not know how to process.

```
Unknown tag 'pattern'; ignoring
```

This could be benign. If it happens to be important, unfortunately there's little we can do about that. This [has been reported before](https://github.com/mogest/prawn-svg/issues/119#issuecomment-605349965) and the author decided not to implement it at that time. I'll note this limitation in the Asciidoctor PDF docs.

**Comment by ponchofiesta** [comment]
Viewbox setting toggle did it. Thank you!

I also exported the SVG as "Plain SVG" now which removed the pattern property and some other inkscape properties. Made the SVG more clean.
