### ISSUE TITLE
Syntax code blocks lose indenting but keep colours in PDF

### ISSUE THREAD

**Issue by wolandscat** [asciidoctor/asciidoctor-pdf#236]
Code that is rendered correctly in the [HTML output ](https://rawgit.com/openEHR/spec-publish-asciidoc/master/docs/AOM2/AOM2.html#_conformance_semantics) is coloured correctly (indicating that Pygments styling is occurring), but the indenting is lost in the PDF:

![image](https://cloud.githubusercontent.com/assets/1481744/8368026/f814ff40-1b9c-11e5-8df5-8949fd150631.png)

**Comment by mojavelinux** [comment]
Aha! This is a tab issue. We convert spaces (to an internal PDF spacer character) but we do not current convert tabs. Therefore, the tabs get dropped.

This is related to https://github.com/asciidoctor/asciidoctor/issues/1170. We can implement this feature ahead of core since it is handled by different code anyway. But that proposes the design we indent to implement.

**Comment by mojavelinux** [comment]
A quickfix is to use spaces instead of tabs, but I do understand that it's necessary to support both.

**Comment by wolandscat** [comment]
Using spaces does work, and that's pretty acceptable from my point of view. The confusing thing is when something renders the way you expect in HTML but not in the PDF.

**Comment by mojavelinux** [comment]
>  The confusing thing is when something renders the way you expect in HTML but not in the PDF.

That's just life at the moment since these are two completely different worlds. We're doing our best to squash these differences so that you can think at the higher level of abstraction...and I believe we can achieve that for all but the rarest edge cases. We just have to keep throwing data at it so we can see the trouble spots light up.

**Comment by mojavelinux** [comment]
I'm going to leave this issue open so that we normalize tabs, one way or another.

**Comment by wolandscat** [comment]
It may be worth adding something to the Asciidoctor user guide [here](http://asciidoctor.org/docs/user-manual/#literal-text-and-blocks) and/or [here](http://asciidoctor.org/docs/user-manual/#source-code-blocks) to say: use spaces to be sure of getting expected output, since noone can be sure how TABs might render.

**Comment by mojavelinux** [comment]
I decided to do this correctly by actually expanding tabs to spaces instead of simply replacing them. That means counting columns and expanding tabs to the number of spaces needed to fill the column in which the tab is used. Not only will the spaces be preserved, it will now be possible to use tabs to align output into columns (such as the output of a command or otherwise tab-separated data).

Unfortunately, things are going to be a bit weird before Asciidoctor 1.5.3 if you're using the indent attribute. The indent attribute triggers a replacement of tabs to spaces, but not with the expand logic (see https://github.com/asciidoctor/asciidoctor/blob/v1.5.2/lib/asciidoctor/parser.rb#L2632). Therefore, you may get mixed and unexpected behavior. If you aren't using the indent attribute, you won't be affected.

The good news is now I know how to solve https://github.com/asciidoctor/asciidoctor/issues/1170 properly.
