### ISSUE TITLE
No author & revision lines

### ISSUE THREAD

**Issue by WizzardHub** [asciidoctor/asciidoctor-pdf#2378]
# Asciidoctor & Asciidoctor PDF Versions

`Asciidoctor 2.0.18 [https://asciidoctor.org]`
`Runtime Environment (ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [x86_64-linux])`

`Asciidoctor PDF 2.3.4 using Asciidoctor 2.0.18 [https://asciidoctor.org]`
`Runtime Environment (ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [x86_64-linux])`

# The issue

Author and revision lines are missing on the pdf version.

Using HTML conversion works.
Using PDF conversion, it does not work.

# Example

(From official documentation, see https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/ example 20)
```
= Document Title
Author Name <author@email.org>
v2.0, 2019-03-22
```

Running the command `asciidoctor test.adoc -o test.html`, works fine !
![image](https://user-images.githubusercontent.com/70410159/206439839-35c85adb-2785-4a83-847d-f15a5fb4d89c.png)

Running the command `asciidoctor-pdf test.adoc -o test.pdf`, does not work.
![image](https://user-images.githubusercontent.com/70410159/206440032-a1328ac1-0f0d-4928-b17e-059d146868cc.png)

# More
Let me know if you need anything else.
Gbye.

**Comment by mojavelinux** [comment]
The behavior you're observing is by design. The PDF converter uses a title page to display the author and revision information. See https://docs.asciidoctor.org/pdf-converter/latest/title-page/ Not all converters have to produce the output in exactly the same way. This is one such example.

If you want to output the author and revision information in a PDF without a title page, you can use the attribute references in the opening paragraph. See https://docs.asciidoctor.org/pdf-converter/latest/title-page/#author-and-revision-information

If you have questions about how to use Asciidoctor PDF, I would prefer if you asked in them in the project chat at https://chat.asciidoctor.org. Thanks!
