### ISSUE TITLE
the string >; followed by a code callout breaks the code callouts

### ISSUE THREAD

**Issue by stallio** [asciidoctor/asciidoctor-pdf#2390]
Inside a code listing, when the string `>;` is followed by a code callout, the callout breaks and the XML is dumped into the listing.

```
= listing test

.Test 1
----
 >; 
----

.Test 2
----
 >; <1>
----
<1> Callout breaks listing
```

Test 1 works but Test 2 returns the following error:

ERROR: failed to parse formatted text: Â &gt<font color="58595B"><font name="M+ 1mn">â�¶</font></font> (reason: Expected ';' after &gt at byte 5)

**Comment by mojavelinux** [comment]
This issue comes from Asciidoctor core. The problem is that `>;` gets escaped to `&gt;;` and the callout replacer considers `;;` to be the start of a line comment. So it gets swallowed up and messes up the line. You can work around this issue by setting the `line-comment` attribute on the block.

```
[line-comment=//]
----
>; <1>
----
```

You can also set the attribute to empty string to turn off the check for the line comment altogether.
