### ISSUE TITLE
Asciidoctor-pdf: stem blocks are not rendered in pdf, but very well rendered in html

### ISSUE THREAD

**Issue by aksigkvgithub** [asciidoctor/asciidoctor-pdf#2417]
IfDear Sir,
I would like to bring to your kind notice that the asciidoctor-pdf  is not rendering the stem blocks (both asciimath as well as latexmath) in pdf format. Howerver, the same is very well rendered in html format..

For the example I am attaching below .pdf file for your kind review:

https://github.com/asciidoctor/asciidoctor-intellij-plugin/files/11111912/Uniformity_trials_asciidoctor.pdf

Since .html file is well rendered, I did not attach it. As for the .adoc file is concerened, I changed it to .txt format so that github may allow to attach it, hence the same is attached below:

https://github.com/asciidoctor/asciidoctor-intellij-plugin/files/11111966/Uniformity_trials_asciidoctor.txt

I have tried many times to install gem asciidoctor-mathematical, but couldn't. I tried asciidoctor-web-pdf, which rendered the stem blocks very well and the entire document seems to be very nice. But, on close examination it tells that it is taking page breaks at improper places, for which I have raised complaint at GitHub issues site of asciidoctor-web-pdf In fact it should give similar output as of asciidoctor-pdf, but with, of course, stem blocks properly rendered too.
enhancement, please verify that you're using Asciidoctor PDF 2 by running `asciidoctor-pdf -v`. If not, please upgrade and retest your scenario. Asciidoctor PDF 1.6.2 and below is no longer supported and will not be updated. When reporting a bug, please provide a sample document that reproduces the problem.

Once you've confirmed you're in the right place, delete this message and proceed!

**Comment by mojavelinux** [comment]
I'm sorry that you're having difficulty installing asciidoctor-mathematical. However, that is how stem blocks and macros are supported in Asciidoctor PDF, and is thus a requirement (as [stated in the docs](https://docs.asciidoctor.org/pdf-converter/latest/stem/#mathematical)). Asciidoctor PDF cannot handle these elements otherwise.

If you can't get past the installation of asciidoctor-mathematical, you can consider using the [Docker (OCI) image for Asciidoctor](https://github.com/asciidoctor/docker-asciidoctor) that's maintained by members of the Asciidoctor project, which includes asciidoctor-mathematical.

As the issue template clearly requests, questions about usage should be directed to the project chat at https://chat.asciidoctor.org. I ask that you please honor the policies we have established for this project.

asciidoctor-web-pdf is a separate project and thus discussions about it are not relevant in this issue tracker. However, you may ask questions about it in the chat.
