### ISSUE TITLE
The roles like fill towards right, [.right]##(4)##, are not formatting in asciidoctor-pdf

### ISSUE THREAD

**Issue by aksigkvgithub** [asciidoctor/asciidoctor-pdf#2422]
Sir, 

With great difficulty I could somehow install docker-asciidoctor. Using asciidoctor and asciidoctor-pdf inside the docker, I have rendered two files:

1. Q.html
2. Q.pdf

The pdf file is attached below for ready reference:

[Q.pdf](https://github.com/asciidoctor/asciidoctor-pdf/files/11412253/Q.pdf)

In the rendered pdf file, a question paper, the roles assigned for right filling with space, before the marks of the questions, using the formatting code,  "[.right]##(4)##", are not right aligning the marks.

However, the same are very well right aligned in the html file rendered by asciidoctor of the docker, which is not attached here, because github does not allow attaching html files.

But, for the same of completeness, and to enable locating the problem, I am also attaching below the .adoc file by renaming in .txt format to be able to attach it, as github does not allow attaching .adoc file too: 

[Q.txt](https://github.com/asciidoctor/asciidoctor-pdf/files/11412258/Q.txt)

It seems I am missing something. I therefore request you to kindly guide me as what to do to correct it.

**Comment by mojavelinux** [comment]
The right role is not supported on an inline phrase in Asciidoctor PDF, and it's not possible to do so. It works in HTML only because CSS is more powerful and happens to be able to interpret it from the inherited styles.

You can learn about what built-in roles are supported on the following page in the docs: https://docs.asciidoctor.org/pdf-converter/latest/roles/

> I therefore request you to kindly guide me as what to do to correct it.

Questions like this should be directed to the project chat at https://chat.asciidoctor.org. That's precisely what the issue template requested. It's not a good use of my time to have to repeat it. We're happy to guide you in the project chat. But it's not what the issue tracker is for.
