### ISSUE TITLE
asciidoctor-pdf stops rendering section headers at a certain level

### ISSUE THREAD

**Issue by houserockr** [asciidoctor/asciidoctor-pdf#2443]
I'm running asciidoctor-pdf on osx m2 (aarch64) with the following version installed via homebrew:

Asciidoctor PDF 2.3.7 using Asciidoctor 2.0.20 [https://asciidoctor.org]
Runtime Environment (ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)

It seems that section headings at a certain level aren't rendered.

![Screenshot 2023-08-28 at 13 46 33](https://github.com/asciidoctor/asciidoctor-pdf/assets/8655705/a3a70a21-826e-411e-b637-95012e693c05)

Section 9.11.2.2.2 - which has 6 '='s in the *.adoc - is still rendered, but the next section one level down 9.11.2.2.2.1 - which has 7 '='s - isn't.

Is there a parameter that limits the maximum number of levels?

**Comment by houserockr** [comment]
![Screenshot 2023-08-28 at 17 58 19](https://github.com/asciidoctor/asciidoctor-pdf/assets/8655705/a2cd0b5f-020b-456e-9be8-8b573ee335e6)
Why does it just stop at level 5???

**Comment by wmat** [comment]
I don't know.  You will get more answers in the community chat at https://asciidoctor.zulipchat.com

**Comment by mojavelinux** [comment]
> Why does it just stop at level 5???

Section levels are limited to 0-5 because HTML only supports heading levels 1-6 (the heading level in HTML is always one more than the section level). This decision was made long ago and Asciidoctor complied with it. However, we are reconsidering this restriction in the AsciiDoc Language specification. However, no change will be implemented in Asciidoctor until at least the first draft of that specification is ready.

For further explanation, see https://docs.asciidoctor.org/asciidoc/latest/sections/titles-and-levels/#section-level-syntax

**Comment by houserockr** [comment]
I mean I get that you need to be compatible with html, pdf, and all other output formats. And if one of those only supports a certain amount of levels for section headers, that is in fact a limitation. But imho, simply passing the asciidoc code through to the resulting document is a very bad idea.

Wouldn't it be nicer to at least render a section title having a level higher than the limit as a paragraph title (`.Paragraph Title`)?

**Comment by mojavelinux** [comment]
Your objection has been heard and, as I said, a change has already been proposed in the AsciiDoc Language specification (in part for the reasons you cited). No change is going to happen in Asciidoctor until that has cleared, so there's no use discussing it here further. You are welcome to join the specification effort if you want to contribute to the proposal.
