### ISSUE TITLE
Suggestion on colophon

### ISSUE THREAD

**Issue by pwaugh** [asciidoctor/asciidoctor-pdf#2455]
When one looks at most books, one sees that the colophon is printed on the even page, yet if we use 
    :media:     prepress
it starts the colophon on an odd page after inserting a blank page.  This should be changed.  Further, this comes before anything, even any preamble, which currently cannot come before it.  I would like to see this corrected.

Frankly, it would be nice to position it with a macro similar to the TOC macro, as it really comes after other things too.

**Comment by mojavelinux** [comment]
It is possible to achieve this customization using an extended converter. That is the approach the the InfoQ Mini Book (and books that are derived from it) has taken. I will document that approach on the extended converter use cases page. See https://github.com/asciidoctor/asciidoctor-pdf/pull/2456

Beyond that, there are a few things...

First, I'd like to see an authoritative reference that documents the proper placement of a colophon. I'm skeptical there is one. And even if there is, publishers all have their opinions about what is right, or at least what they prefer. There have been numerous books published using Asciidoctor PDF. Are we going to break those books by changing this behavior in Asciidoctor PDF.

Second, the colophon doesn't have special meaning in AsciiDoc, Asciidoctor, or Asciidoctor PDF. It is one of a variety of special sections. So there is no precedent for treating the colophon differently. And even the definition of a colophon itself is rather loose. Some prefer to place it at the end of the book, or after other supplementary sections. Asciidoctor PDF cannot accommodate all these different needs, which is why it provides a way to extend the converter and apply the customization that works for you.

Finally, the code that I have shared assumes the colophon is only a single page. Adding an arbitrary number of pages in front of the table of contents is very complicated in Asciidoctor PDF. For one, I don't have time to try to figure that out in Asciidoctor PDF. And second, adding that could introduce incompatibilities with existing uses of Asciidoctor PDF, which I don't even want to try to imagine. On the other hand, using an extended converter is safe.

As for the idea of a custom macro or insertion slot...you are certainly welcome to develop a custom block macro that would insert a colophon wherever you want it in the document...extending the converter if necessary to fine-tune the placement. That is a capability Asciidoctor affords you. We will not be adding a built-in macro as it is entirely too specialized.

**Comment by pwaugh** [comment]
Actually, the proposal would be easily implemented in a properly protocol oriented design, and is a generalization, making things more flexible, not less, and it further follows existing capabilities.  Very disappointed in your design philosophy and apparent lack of vision in that regard.  One has only to look at a variety of books to see the standards of colophons.But, at least I know now not to waste further time.P.T. Waugh, M.A.Sent from my iPadOn Oct 8, 2023, at 3:26 AM, Dan Allen ***@***.***> wrote:﻿
It is possible to achieve this customization using an extended converter. That is the approach the the InfoQ Mini Book (and books that are derived from it) has taken. I will document that approach on the extended converter use cases page. See #2456
Beyond that, there are a few things...
First, I'd like to see an authoritative reference that documents the proper placement of a colophon. I'm skeptical there is one. And even if there is, publishers all have their opinions about what is right, or at least what they prefer. There have been numerous books published using Asciidoctor PDF. Are we going to break those books by changing this behavior in Asciidoctor PDF.
Second, the colophon doesn't have special meaning in AsciiDoc, Asciidoctor, or Asciidoctor PDF. It is one of a variety of special sections. So there is no precedent for treating the colophon differently. And even the definition of a colophon itself is rather loose. Some prefer to place it at the end of the book, or after other supplementary sections. Asciidoctor PDF cannot accommodate all these different needs, which is why it provides a way to extend the converter and apply the customization that works for you.
Finally, the code that I have shared assumes the colophon is only a single page. Adding an arbitrary number of pages in front of the table of contents is very complicated in Asciidoctor PDF. For one, I don't have time to try to figure that out in Asciidoctor PDF. And second, adding that could introduce incompatibilities with existing uses of Asciidoctor PDF, which I don't even want to try to imagine. On the other hand, using an extended converter is safe.
As for the idea of a custom macro or insertion slot...you are certainly welcome to develop a custom block macro that would insert a colophon wherever you want it in the document...extending the converter if necessary to fine-tune the placement. That is a capability Asciidoctor affords you. We will not be adding a built-in macro as it is entirely too specialized.

**Comment by mojavelinux** [comment]
Frankly, I don't deserve this lack of respect. I'm disappointed in your lack of professionalism. I'll merge the documentation PR that I submitted and that will be the last I will engage with this pointless conversation.
