### ISSUE TITLE
:pdf-page-margin: bug?

### ISSUE THREAD

**Issue by mementum** [asciidoctor/asciidoctor-pdf#2474]
asciidoctor-pdf: `2.3.10` either on Ubuntu 22.04 or cygwin with ruby `3.0.2.p107` and `3.2.0` respectively.

I have checked the `CHANGELOG` for the latest unreleased changes and there seems to be nothing related to that.

The margins in the example have been over-dimensioned to show the problem. Current configuration
```
:pdf-page-size: [6in, 9in]
:pdf-page-margin: [1.5in, 1.375in, 1.5in, 1.357in]
```

But not all content in the page respects the margin settings. The page number in the footer (and the separation line) remain at the bottom. See the screenshot below. The actual page content is properly rendered respecting the margins, but if one wants to use the resulting PDF for publication, the page number at the bottom may be outside the trim area.

The problem happens with all `:media:` options, i:e: `screen`, `prepress` and `print``

![image](https://github.com/asciidoctor/asciidoctor-pdf/assets/5713511/31bab97f-6fa6-450c-bff2-4aea7429e64d)

**Comment by mojavelinux** [comment]
This behavior is by design. The running content is a stamp on top of the page and thus works independently from the page margins.  The footer manages its own bottom margin (and the header its own top margin). To configure it, refer to https://docs.asciidoctor.org/pdf-converter/latest/theme/running-content/#footer (margin).

You'll not that the default side margins for running content is "inherit", which means inherit from the side margins of the page. However, the running content is not restricted to page margin and can be configured otherwise.

If you need more assistance, please direct follow-up questions to the project chat at https://docs.asciidoctor.org (asciidoctor-pdf stream).

**Comment by mementum** [comment]
Hi,

Thanks for the clarification.

I believe it would be good for the current and future users of `asciidoctor-pdf` to see this in the documentation.

  - https://docs.asciidoctor.org/pdf-converter/latest/asciidoc-attributes/#asciidoc-document-attributes

If `:pdf-page-size:` defines the `size` of the entire page, it is only logical for anyone looking at the documentation to conclude that `:pdf-page-margin:` is going to define the `margin` of the entire page.

Hinting there at the usage of theming for fine control of the "theming" possibilities would help a lot.

A longer route would introduce `:pdf-content-margin:` for the same purpose, deprecate `:pdf-page-margin:`, remove it from the docs, and  issue warnings when used,  until a given target version removes it.
