### ISSUE TITLE
Missing callout numbers and admonition images if PDF is opened with Adobe acrobat reader

### ISSUE THREAD

**Issue by joerg256** [asciidoctor/asciidoctor-pdf#2531]
Dear Asciidoctor-pdf team, 

I am having the following problem: 

PDFs are not displayed correctly when opened in _Adobe acrobat reader_ and _Adobe acrobat reader DC_ on windows 10. 

1. Admonition images are not visible (like for note, warning ...) in the PDF.
2. Callout numbers (in code segments) are not visible in the PDF. 

The following error message appears: 

> Cannot extract the embedded font '635a1d+SegoeUISymbol'. Some characters may not display or print correctly.

I have tried different fonts and added fallback fonts to resolve this: 

- M+ 1mn
- M+ 1p
- SegoeUISymbol

(the named font in the message was different in those cases.) 

In all other programs to view PDF-files everything worked fine! I have tested _Firefox_, _Edge_, _pdf24Reader_.

(Additional note 1: This was not an issue in the past. I can still open older generated PDFs without this problem.)
(Additional note 2: The Adobe reader had the same problems with notoserif-italic-subset.ttf.)

Thank you in advance!
Joerg

**Comment by mojavelinux** [comment]
Check whether you are using ttfunk 1.8 instead of 1.7. If you installed the Asciidoctor PDF gem from rubygems.org, you should have ttfunk 1.7 since Asciidoctor PDF locks to that version (see https://github.com/asciidoctor/asciidoctor-pdf/blob/v2.3.x/asciidoctor-pdf.gemspec#L38). ttfunk 1.8 has known issues (see https://github.com/prawnpdf/ttfunk/issues/102) and should not be used.

In the future, please ask questions about usage in the project chat as the issue template requested. Issues should only be filed one a problem is verified. This helps make the project more sustainable. You can find the policies here: https://docs.asciidoctor.org/about/get-help/

**Comment by joerg256** [comment]
Thank you a lot. This solved the problem instantly! :)
