### ISSUE TITLE
URI for local file is not working for title logo image

### ISSUE THREAD

**Issue by aeromorrison** [asciidoctor/asciidoctor-pdf#2545]
I'm just learning AsciiDoc and asciidoctor-pdf, so please pardon if I've missed something obvious here. I am an avid reader of documentation and I've read the related sections and tested this as much as I could figure out.

### Issue
When I try to use a URI to a local file in the :title-logo-image: setting it can never locate the file. I'm using the identical syntax with my references to stylesheets in HTML builds, which are working just fine.

### Example
I placed a logo in the root of my E: drive. The filename is logo.png. I include a reference in the header as follows:

`title-logo-image: image:file://E:/logo.png`

I build using the following command, being careful to include allow-uri-read option:

`asciidoctor-pdf -a allow-uri-read document.adoc`

When this is run I get an error message that says: "asciidoctor: WARNING: could not retrieve remote image: file://E:/logo.png; bad URI(is not URI?): "file://E:/logo.png"

If I replace the URI with a relative reference such as `image:../../../logo.png` then it works as expected and builds properly. Also note that I'm using a file://  URI for my stylesheet reference for HTML builds without issue. It works fine for that.

**Comment by mojavelinux** [comment]
Welcome!

There's no need to use a file URI in this case (and deal with the side effects). You can just use an absolute path:

```
title-logo-image: E:/logo.png
```

Btw, the image macro is only needed if you want to specify attributes. Otherwise, the path is sufficient. See https://docs.asciidoctor.org/pdf-converter/latest/background-images/#page-background-image for related information.

In the future, please direct questions about usage to the project chat at https://chat.asciidoctor.org. Thanks!

**Comment by aeromorrison** [comment]
OK. Thanks so much for the information. I'll give it a try. Thanks also for the tip about the project chat. I'm new to asciidocs and the associated tools, but I'm really liking it so far.
