### ISSUE TITLE
Pallete-based transparency in PNG is not currently supported.

### ISSUE THREAD

**Issue by shahryareiv** [asciidoctor/asciidoctor-pdf#257]
I receive this while compiling:
"asciidoctor: WARNING: could not embed image: .... Pallete-based transparency in PNG is not currently supported."
Probably a limitation by Prawn :https://github.com/prawnpdf/prawn/issues/783
But anyway, in a toolchain with multiple format outputs, Pallete-based transparency can be required.

**Comment by mojavelinux** [comment]
My advice is to pursue this fix upstream in Prawn. If Prawn is unwilling to address this issue, then I suppose we need to take the maintainer's advice and replace the entire image system in Prawn so that we have something more reliable. While that may seem drastic, there are other reasons I've considered doing that. The current PNG handling in Prawn is extremely slow. Delegating the work to ImageMagick could have a major performance benefit.

**Comment by pismute** [comment]
prawnpdf/prawn#783 is solved now(prawnpdf/prawn#920). Please check it.

**Comment by mojavelinux** [comment]
Available since Prawn 2.1.0. Marking as closed.

Another solution to this problem, btw, is to use [prawn-gmagick](https://github.com/packetmonkey/prawn-gmagick). That gem delegates image processing to ImageMagick, and does it a hell of a lot quicker. Since it's a native gem, we won't add a hard dependency to it, though.
