### ISSUE TITLE
Rake install tasks

### ISSUE THREAD

**Issue by dsisnero** [asciidoctor/asciidoctor-pdf#261]
When I fork this repository to make changes, and then run  rake install or rake install:local,
none of the lib folders are included.  Also, there are no tests in this repository.  How are test, if any, run

thanks

**Comment by mojavelinux** [comment]
> there are no tests in this repository. How are test, if any, run

There are no tests yet. That's something I'm currently working on integrating. There's at least one open pull request, but I'm not sure it's the way we want it yet.

**Comment by mojavelinux** [comment]
I've never used `rake install` (which might explain why it doesn't work correct). I tend to use this sequence:

```
$ rake build
$ gem install pkg/asciidoctor-pdf-1.5.0.dev.gem
```

Perhaps the lib isn't being included when you call rake install because of this line? https://github.com/asciidoctor/asciidoctor-pdf/blob/master/asciidoctor-pdf.gemspec#L21 (I'm just guessing atm).

**Comment by mojavelinux** [comment]
I see now that `rake install` basically does the two steps I just mentioned. I tried it and it works fine for me. I see all the files in the lib folder. Are you checking out the code via git? I'm not seeing how this is not working unless the line I pointed to is failing for some reason. Could you debug the rescue block?

Side note: I tend to do the steps manually since I install the gem into a separate RVM gemset when using it. But most of the time I just run it directly out of the development tree using `./bin/asciidoctor-pdf`.

**Comment by mojavelinux** [comment]
This has since been resolved. See:

* https://github.com/asciidoctor/asciidoctor-pdf#install-the-application-optional
* https://github.com/asciidoctor/asciidoctor-pdf#run-the-tests
