### ISSUE TITLE
Gem file structure

### ISSUE THREAD

**Issue by chloerei** [asciidoctor/asciidoctor-pdf#262]
According to http://guides.rubygems.org/name-your-gem/

asciidoctor-pdf require statement should be

``` ruby
require 'asciidoctor/pdf'
```

Then the file structure should be

```
|-- lib
|   `-- asciidotor
|       |-- pdf
|       |   `-- version.rb
|       `-- pdf.rb
```

And I think module name should be `Asciidoctor::PDF` (current is `Asciidoctor::Pdf`)

I'm going to create some CJK extension(patch and theme) for asciidoctor-pdf, I'm confuse which rule should I follow.

**Comment by chloerei** [comment]
Current I use this struct, follow both rubygems and asciidotcor convention:

```
|-- asciidoctor
|   `-- pdf
|       |-- cjk
|       |   `-- version.rb
|       `-- cjk.rb
`-- asciidoctor-pdf-cjk.rb # <- require 'asciidcotor/pdf/cjk'
```

**Comment by mojavelinux** [comment]
In general I try to follow the RubyGems conventions, but there are places where I don't agree with the recommendations. These are the two main examples.

In both places, I have found some precedent for my choice, so I wouldn't say it's just the Asciidoctor way. It's just another popular view. I'll provide some reasoning behind my choices.

Regarding the require path, I find `asciidoctor/pdf` non-ideal for several reasons. First, it's more awkward looking on the commandline:

```
asciidoctor -r asciidoctor/pdf file.adoc
```

But the stronger reason is that it gives the impression that it is part of Asciidoctor core, and potentially conflicts with that namespace, whereas `asciidoctor-pdf` makes it clear that it's a separate gem.

But above all, the problem is that it's confusing for novices because the require path doesn't match the gem name. So it's very non obvious why they have to use `asciidoctor-pdf` to install the gem but `asciidoctor/pdf` to require it. And I think that's what really clinched it for me.

Having said all that, I'm 100% in support of doing what Asciidoctor LaTeX did, and what you are proposing, which is to add a require alias at the path `asciidoctor/pdf` so that you can type it either way. However, I still believe that the implementation files should be under the `asciidoctor-pdf` directory. It avoids a namespace collision and it isn't so deeply nested.

Regarding the class naming convention, years of Java development has taught me that acronyms should not be in all uppercase as it's a) harder to type and b) makes it harder to implement "bean conventions" because if you lowercase the first letter and the rest of the letters are uppercase, it just looks strange (e.g., "hTML"). There are cases of this convention in some of the top gems like multi_json and sass. I'm willing to reconsider, but it does have a ripple effect into Asciidoctor core.

**Comment by mojavelinux** [comment]
I'll add the require path alias.

**Comment by chloerei** [comment]
OK. So I will keep alias too.

And I'm using `Asciidoctor::Pdf::CJK` module name, should I change it to `Asciidoctor::Pdf::Cjk`? If it will have a ripple effect into Asciidoctor core.

**Comment by mojavelinux** [comment]
I think it's good to be consistent within our own ecosystem, so I recommend `Asciidoctor::Pdf::Cjk`.

**Comment by mojavelinux** [comment]
I studied a lot of the gems in the ecosystem as well as Ruby core. I've determined that it's most common for acronyms to remain in uppercase, so I decided to adhere to that. I've also decided to add `asciidoctor/pdf` and `asciidoctor/pdf/version` as require aliases. We may decide to move the files in the future, but at least now to the consumer it appears like the files have that structure.

**Comment by mojavelinux** [comment]
I have an idea that I'd like to float. What if we use all uppercase for an acronym that stands alone (e.g., PDF), but sentence capitalization when combined with another word (e.g., PdfObject)? That way, we kind of get the best of both worlds.

For reference, I polled Twitter about the casing issue. See https://twitter.com/mojavelinux/status/782878580871049216. That led to a few references regarding style:

1. https://google.github.io/styleguide/javaguide.html#s5.3-camel-case
1. http://cr.openjdk.java.net/~alundblad/styleguide/index-v6.html#toc-class-interface-and-enum-names
1. http://stackoverflow.com/questions/2236807/java-naming-convention-with-acronyms/7366332#7366332

The recommendations in (2) support by idea. "Format an abbreviation as a word if it is part of a longer class name." Therefore, I'm inclined to adopt it.

**Comment by chloerei** [comment]
https://github.com/bbatsov/ruby-style-guide#naming

This guide recommend PDFObject.

**Comment by mojavelinux** [comment]
Yes, that is true. We are discussing challenging that convention. It appears that the Ruby convention is at odds with much of the industry.

**Comment by chloerei** [comment]
Both style are valid syntax, and will not bring real problems, it's OK to formulate a gem specific style. The best part of a convention is avoid spending time on formulate style.

If choose a style, it's better to choose a Ruby style but not Java, because it's Ruby gem. (and same with other language)

**Comment by mojavelinux** [comment]
> If choose a style, it's better to choose a Ruby style but not Java, because it's Ruby gem. (and same with other language)

While you have a good point, what we decide here is going to affect the whole Asciidoctor ecosystem, which spans numerous languages (Ruby, JavaScript, Asciidoctor). We don't want to have different rules for different language platforms within the ecosystem or else it gets really confusing for polyglot users. In particular, the AsciidoctorJ API mirrors the Ruby API, so we'd end up violating Java's style.

I really think that the PDF / PdfObject split is a great compromise that is forward thinking. Ruby is definitely stuck in the past here.

**Comment by mojavelinux** [comment]
To confuse matters, JRuby seems to use both conventions :/

http://www.javadoc.io/doc/org.jruby/jruby-complete/9.1.5.0

**Comment by chloerei** [comment]
> what we decide here is going to affect the whole Asciidoctor ecosystem

Fine, I have not considered that.

Best way is follow style in each language, but it need a lot of work.

For cross language style, it does not need to be consistent with Ruby style, `Pdf` is OK, be consistent in the ecosystem. I confuse with `PDF` and `PdfObject`.
