### ISSUE TITLE
Processing stalls

### ISSUE THREAD

**Issue by orloffm** [asciidoctor/asciidoctor-pdf#309]
So, I want to include several files into my document, 1, 2, 3, 4, 5.

If I include (1, 2) or (3, 4, 5), I get the resulting PDF in 10 seconds. It is 1 megabyte large and the process uses 65 megs of RAM max.

If I include (1, 2, 3, 4, 5), the process reaches the same ~65 megs over the same 10 seconds and then does nothing indefinitely, slowly consuming more RAM.

What can be done with it? Again, it is latest alpha 9 version and I'm on Windows. I have no Ruby experience and have no idea how to approach this.

**Comment by mojavelinux** [comment]
There are several reasons that the PDF generation consumes so much RAM, but 90% of the time it's processing PNG images. The first thing I recommend is to turn off all images (messing with the imagesdir path) just so that you can determine if that's where the time is being taken up.

Aside from that, I need access to the documents in order to test them or I can only guess what the problem may be. Would you be able to provide me with the source documents?

**Comment by orloffm** [comment]
OK, I figured it out. The file numer 2 had four dots in the beginning of the line almost at the end, so presumably its end and files 3, 4, 5 were treated as a huge literal block.

I've put files to https://github.com/orloffm/testbook/ if you need them.

**Comment by mojavelinux** [comment]
Good to hear!
