### ISSUE TITLE
horizontal labeled list doesn't seem to work

### ISSUE THREAD

**Issue by aidanhs** [asciidoctor/asciidoctor-pdf#310]
I was expecting something like "Labeled horizontal" on http://powerman.name/doc/asciidoc

Is this unimplemented, or have I missed a theme setting?

**Comment by mojavelinux** [comment]
This is currently unimplemented.

We'd likely need to use a Prawn table to achieve this layout. We could also consider the grid layout in Prawn.

**Comment by ericis** [comment]
Despite being unimplemented, authors might consider leaving the `[horizontal]` tag in your document until it is supported as PDF. Once added, your formatting intentions will just work like you intended.

**Comment by gdamore** [comment]
This is pretty annoying.  I'm using some lists like this, and I had previously implemented a table to work around this, but now both the HTML and epub look *great* when viewing this as a horizontal list (I've had to make some changes to the epub3 rendering and CSS to get the right results though).  But sadly it looks *horrible* in PDF this way.  I'll probably wind up doing an ifdef block to switch rendering between PDF and everything else....

Any idea on when this might get fixed? I don't really know ruby that well, nor prawn, or I might otherwise be tempted to fix it myself.
