### ISSUE TITLE
How to prevent line break at a given position?

### ISSUE THREAD

**Issue by orloffm** [asciidoctor/asciidoctor-pdf#321]
I have a document that contains this:

> «Всем известно, что...», «точно установлено...», 

When it is rendered, a line break is inserted before `»`, so it looks like this:

> «Всем известно, что...
> », «точно установлено...», 

How to fix that? I've tried inserting `&#65279;`, but that causes the parser to fail.

**Comment by orloffm** [comment]
OK, "zero width non-breaking space" `&#8288;` works, but is treated as a non-breaking *space*. Can it be parsed as a zero-width character?

**Comment by mojavelinux** [comment]
Ideally, you'd use the zero-width character, though it's probably not recognized by the inline parser atm (every entity has to be parsed when passing it though Prawn). I suppose we could add `&zwsp;` to the list of matched entities. See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/lib/asciidoctor-pdf/formatted_text/transform.rb#L6-L12.

But even if we did that, it's still not the right way to solve the problem because you shouldn't be adding those characters to your AsciiDoc to fix Prawn. This is an i18n issue in Prawn. Prawn should not be breaking the line at any quote character. It's probably hard coded somewhere in Prawn to only check for English quotes.

If we can't get it fixed in Prawn, we can introduce a patch so that Prawn behaves the right way. The bottom line is, you shouldn't be getting a break before the quote. That's the real problem to solve.
