### ISSUE TITLE
Table breaking

### ISSUE THREAD

**Issue by mbartelsm** [asciidoctor/asciidoctor-pdf#331]
Is it possible to prevent a table from breaking at the end of a page by completely moving it to the next one?

**Comment by mojavelinux** [comment]
Not at the moment, though we could consider adding it.

This comes at a pretty high performance cost the way that Prawn works, though, because we have to render the whole table into a draft document to determine its height. We do that with other blocks already, but tables are the most complex thing to render, hence the reason its the highest cost.

What I recommend doing now is add manual page breaks temporarily once the document reaches a stable state (such as at a release). It's a manual typesetting step, but at least it gives you the result you desire currently.

**Comment by mojavelinux** [comment]
We might be able to use the before_rendering_page page hook in Prawn::Table.

**Comment by janicemhdc** [comment]
There's a whole bunch of related stuff in issue #2082

**Comment by graphitefriction** [comment]
Related to #2022

**Comment by graphitefriction** [comment]
In the upcoming release of Asciidoctor PDF 2.0, you will be able to prevent an orphaned table caption by assigning the option `breakable` to a table.

```
.Optional table caption/title
[%breakable]
|===
|Content |Content

|Content |Content
|===
```

Note that the table will still break if it flows from the current page to the next page. The `breakable` option only prevents the table caption (and ID, if one is assigned) from being orphaned. (We decided it was best if people choose to opt-in to this behavior due to the potential performance costs in some cases.)

Also, you'll be able to assign the `unbreakable` option to a table if you don't want it to break and flow to the next page when it doesn't fit on the current page.

```
.Optional table caption/title
[%unbreakable%header,cols="2*"]
|===
|Content
|Content

|Content
|Content
|===
```
