### ISSUE TITLE
Set attribute default from theme

### ISSUE THREAD

**Issue by ghost** [asciidoctor/asciidoctor-pdf#360]
Hi,

is there a way to set default document-attributes from the theme?

e.g:
asciidoctor's default: figure-caption is 'Figure'
-is overwritten by
theme's default: figure-caption is 'Image'
-is overwritten by
user's setting inside the document: figure-caption is 'Diagram'

**Comment by mojavelinux** [comment]
I could see an argument for having an attributes section in the theme. The counter argument is that these should be added using an include directive, such as:

```
= Document Title
include::settings.adoc[]

content
```

The third possibility is that these are actually language settings and would therefore be satisfied by the planned language feature described in https://github.com/asciidoctor/asciidoctor/issues/566.

**Comment by elfrinjo** [comment]
I guess the problem is that attributes are a mixture of theming-, (meta)content- and technical-settings.

As I love the idea of splitting those and to not bother an author with non-content settings while not touching the content (or includes) for other things, my personal favourite workflow would be:
- Set content stuff in the adoc files (authorgroup, keywords, ...)
- Set theming stuff in the theme (icon-set, numbered, ...)
- Set technical stuff at the commandline or options file (pdf-fontsdir, imagesdir,...)

The ability to influence the defaults of attributes from the theme was my idea to tackle this without loosing flexibility.

**Comment by mojavelinux** [comment]
The more I think about this, the more reasonable it seems that we have a slot in the theme for setting attributes. We'll advise that this slot be reserved for theming-related attributes, but we won't enforce it.

**Comment by mojavelinux** [comment]
The problem here is that the theme is read in much to late to influence a lot of the attributes that are set. The theme is read by the converter. But by the time the converter runs, the document has already been parsed and many of the attributes have done their job already.

I think this is better handled by this proposal in core: https://github.com/asciidoctor/asciidoctor/issues/566
