### ISSUE TITLE
Icons within source code support

### ISSUE THREAD

**Issue by mnhock** [asciidoctor/asciidoctor-pdf#364]
It would be great if the export to PDF works for inline icons within source code. For HTML it works perfect. 

It would help to mark code as good / bad code. 
```
[source, java, subs="normal"]
----
Set carList; icon:frown[float=right] 
----

[source, java, subs="normal"]
----
Set cars;  icon:smile[float=right]
----
```

**Comment by mojavelinux** [comment]
The problem here is that icon set is not getting loaded before an attempt is made to use one of the icons. This can be solved by checking for the icon set name in the `font` function and loading the font if necessary.

```ruby
def font name = nil, options = {}
  if name
    if (['fa', 'fi', 'octicon', 'pf'].include? name)
      (@font_icon_data ||= {})[name] ||= ::Prawn::Icon::FontData.load self, name
    end
    options = { size: options } if ::Numeric === options
  end
  super name, options
end
```

Also, the listing should be written as:

```asciidoc
[source, java, subs=+macros]
----
Set cars;  icon:smile-o[]
----
```

Unfortunately, this can't work when you use syntax highlighting because there are just too many conflicting markups in the pipeline to make sense of what to do. We'd need another way to flag a character as an icon aside from using an SGML element.

**Comment by mojavelinux** [comment]
The proposed fixed allows the icon fonts to be used in listing or literal blocks (not source highlighted).

**Comment by mnhock** [comment]
Thanks!
