### ISSUE TITLE
Add support for inline roles to theme

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-pdf#368]
Allow the theme to control the styling for roles on inline elements. When a role is detected on an inline element, it consults the theme to get styling information to merge into the default. This effectively brings styling using CSS classes to inline elements.

Example:

```
[.type]#name of type#
```

**Comment by mojavelinux** [comment]
We also may want to define some built-in, semantic role names as discussed in https://github.com/asciidoctor/asciidoctor/issues/1664.

**Comment by mattwynne** [comment]
Given that this issue is still open, is there any way at the moment for me to style individual pages or other elements in a PDF, e.g. adding a different background image to each level 1 section?

No criticism or pressure meant - I work a lot on OSS myself and I know you need to be free to just get around to things when you can. I'm just new to asciidoctor and trying to get my head around the scope of what's possible. In general it seems like an awesome piece of work so far, so thanks very much.

**Comment by mattwynne** [comment]
@mojavelinux I dunno how hard this is or how much bandwidth you have, but I am feeling the pain of this right now and would be motivated to have a crack at implementing it myself if you were able to give me some pointers.

I'm going to experiment with using a custom converter (as mentioned in #337) for now.

**Comment by mojavelinux** [comment]
I think the open pull request for this should at least get you part of the way there. See https://github.com/asciidoctor/asciidoctor-pdf/pull/350

What we need is someone to take that to completion. It will solve a lot of open requests.

**Comment by mojavelinux** [comment]
The tricky part is deciding how to configure the properties (i.e., keys) of the role in the theme so they don't collide with built-in keys.

I think the simplest way to do this is to reserve `role` as a top-level category. The custom roles would then be defined inside that category.

The first subkey level represents the role name (no hyphens or underscores allowed), and the keys under those roles are the concrete theming properties such as `font-color`.

Here's an example of some roles for text colors:

```yaml
role:
  red:
    font-color: ff0000
  green:
    font-color: 00ff00
  blue:
    font-color: 0000ff
```
