### ISSUE TITLE
Special characters and icons inside kbd macro not supported

### ISSUE THREAD

**Issue by SandMann1** [asciidoctor/asciidoctor-pdf#387]
See attached example adoc in index.zip. Arrow up (and other special characters - icons or glyphs) can be parsed correctly, but when parsed within a kbd macro something goes wrong. 
Error message from asciidoctor-pdf:

`Failed to parse formatted text: This is me trying to get an arrow up in a kbd macro - <code>Ctrl</code>+<code><font name="fa" size="</code>">?</font>`

Result in pdf (both custum and default theme from alpha 11) is:
![image](https://cloud.githubusercontent.com/assets/8665274/12196581/02542668-b600-11e5-8d8f-892ffd60acc2.png)

Edit: Note that the kbd macro without up-arrow icon, just the `Ctrl` is parsed just fine.

Result in html5 (asciidoctor) is ok. 

[index.zip](https://github.com/asciidoctor/asciidoctor-pdf/files/82566/index.zip)

**Comment by mojavelinux** [comment]
This is a limitation only of the default theme. This happens because we choose to bundle a monospaced font, M+ 1mn, with a limited set of characters (anticipating that special characters are rarely, if ever, used in a monospaced context). In addition, the parser doesn't recognize a `<font>` element inside of a `<code>` phrase, which happens when you put an icon in a kbd macro.

Simply put, this is not a supported combination atm. We can consider adding it in the future.

**Comment by mojavelinux** [comment]
It turns out this does work after all. However, you need to properly escape the icon macro inside the kbd macro. Here's how that would look:

```
:icons: font
:icon-set: fas
:experimental:

kbd:[Ctrl,icon:arrow-up[\]]
```

The fact that it works without escaping the icon macro in the HTML output is just a fluke. It's not suppose to work that way.

If you want to use an AsciiDoc attribute for this, you'll need a separate one with the escaped square bracket to use inside another macro.

**Comment by mojavelinux** [comment]
I'll add a test for this scenario just to be sure.

**Comment by mojavelinux** [comment]
Test added.
