### ISSUE TITLE
Ellipses, arrows, m-hyphens generate errors

### ISSUE THREAD

**Issue by gtapper** [asciidoctor/asciidoctor-pdf#389]
->, <=, --, ..., and other formatting generate the following error:

The following text could not be fully converted to the Windows-1252 character set

I work around this issue by using html code such as `&#8212;`

**Comment by mojavelinux** [comment]
It's likely this is happening because these characters are not in the font provided by your theme. Please see http://gist.asciidoctor.org/?github-asciidoctor%2Fasciidoctor-pdf%2F%2Fdocs%2Ftheming-guide.adoc#fonts and let me know if you have additional questions.

**Comment by antoyo** [comment]
I am not sure about this, because I replaced `...` by `…` (one character) and I don't get this error anymore.

**Comment by mojavelinux** [comment]
The only way you see this message:

> The following text could not be fully converted to the Windows-1252 character set

Is if you are not using a custom, TTF font. If your TTF font is missing the character, you will not get any notification (due to a bug/limitation in Prawn). I would still like to have a warning if the character is missing from a TTF font, but I haven't looked into that yet.

See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#fonts.

**Comment by mojavelinux** [comment]
If you are still having problems, please fill a new issue with additional information.

It should now be a lot easier to extend the default theme without losing the fonts (or providing your own). See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#keys-extends for details (or see the chronicles-example.adoc in the examples folder).
