### ISSUE TITLE
Add support for images to span width of page

### ISSUE THREAD

**Issue by gunillabolin** [asciidoctor/asciidoctor-pdf#424]
Opening a new issue after discussion in issue [https://github.com/asciidoctor/asciidoctor-pdf/issues/418]

It is possible to achieve this by setting the pdfwidth option to 120% but this possibility either needs to be documented or another, more obvious, way to do it needs to be implemented.

To me, the most obvious way for the percentage to work would be to let 100% actually span the page, not taking any margins into account.

**Comment by mojavelinux** [comment]
I have an idea that fits more with the spirit of CSS, which we're attempting to imitate.

In CSS, percentage is always relative to the parent element. That's consistent with how % in Asciidoctor PDF works today. However, CSS encounters the same limitation we're observing with this issue. What if you want the image to span the width of the viewport?

What CSS has done is introduce an additional percentage unit that communicates the parent should be ignored and the percentage should be based on the width of the viewport. That unit is `vw`. I think that unit solves our problem.

To get an image to span the width of the entire page, I propose using the following:

```
image::image01.png[pdfwidth=100vw]
```

This would be easy for Asciidoctor PDF to calculate. I think we should also assume that the image should be placed relative to the edge of the page instead of aligned with the content.

**Comment by gunillabolin** [comment]
Sounds good!

What about the cases where you want the image aligned with the content, would you then  use the normal percentage unit?

**Comment by mojavelinux** [comment]
Correct.

**Comment by mojavelinux** [comment]
Related to this issue, we've also discussed having a "cover" role for the image block. This role would instruct the converter to fit the image to the width of the page (clipping if it overflows). This would be similar to the background-size property in CSS. However, I believe that differs from the vw units.

**Comment by mojavelinux** [comment]
I designed it such that the image stretches to the width of the page, but the caption for the image stays within the content width.
