### ISSUE TITLE
placing pdf images

### ISSUE THREAD

**Issue by kastork** [asciidoctor/asciidoctor-pdf#436]
When I try to place a pdf image like so:

```
[[Figure-2.4]]
.Caption text
[caption="Figure 2.4. "]
image::2.4.pdf[width=5in,align=center,scaledwidth=5in]
```

Adobe Reader complains that there is an error reading the file, but not until I scroll down to where the image is supposed to be.  And the image is not rendered.

Sleuthing around in the code, I see some handling of 'pdf' as an input type, but it looks to be handled as though any pdf placement is supposed to be a a full page insertion.

I've been trying to get this to work because of all the upstream problems with Prawn's SVG handling.  Seems like being able to just place pdf images directly would be a useful solution.

**Comment by mojavelinux** [comment]
The problem here is that importing PDF pages into a Prawn document is very hit or miss. It depends on the complexity of the PDF being imported. In some ways, it's no more or less chancy than importing an SVG. The strategy used in both cases is very similar. Prawn attempts to recreate the objects from the original document in the current document.

You're likely getting an error because Prawn is messing up the import. The more sound approach is to continue to help mature Prawn SVG.

**Comment by kastork** [comment]
understood, thanks for the explanation.
