### ISSUE TITLE
menu: macro should use -> instead of |

### ISSUE THREAD

**Issue by vogella** [asciidoctor/asciidoctor-pdf#441]
If I define the following

menu:View[Zoom > Reset]

I get a nice output in HTML, similar to the following:

View -> Zoom -> Reset

The PDF output uses | which IMHO is less optional. 

View | Zoom | Reset

Can the PDF output adjusted to also use arrows?

**Comment by mojavelinux** [comment]
If I remember correctly, I chose the pipe because the font we were using at the time didn't have the arrow glyphs. I believe that is corrected now that we have the fallback font.

**Comment by mojavelinux** [comment]
I think this is similar to #313.

**Comment by vogella** [comment]
I guess the change should be done in https://github.com/asciidoctor/asciidoctor-pdf/blob/master/lib/asciidoctor-pdf/converter.rb#L1493

Looking at http://unicode.org/charts/PDF/U2190.pdf I think the PDF encoding for the arrow is 2192. I think in PDF language this maps to %(\u2192).

While I have no idea about Ruby nor PDF syntax, I think a patch is simple. I give it a try.

**Comment by vogella** [comment]
This is basically a guess now to fix that. I don't know how to test this locally.

https://github.com/asciidoctor/asciidoctor-pdf/pull/443

**Comment by mojavelinux** [comment]
Thanks @vogella!

**Comment by mojavelinux** [comment]
I also introduce a key in the theme to control the content used for the caret, so you can set it to whatever character your font supports...in whatever color you want (using pseudo HTML tags):

```
menu_caret_content: " \u25ba "
```

I held off documenting this key in the theming guide because I'm not yet convinced we have the naming right. I'll let it simmer a bit before I document it.
