### ISSUE TITLE
btn: macro should add a background to the button

### ISSUE THREAD

**Issue by vogella** [asciidoctor/asciidoctor-pdf#451]
It would be nice if the PDF output would add a themeable background color to a button. I think the relevant macro is convert_inline_button node. 

I put up a proof of concept patch very soon but unforunately can't find an example in the existing inline macros for that. The other macros seem to follow another approach for styling so advice or update of my little proof of concept patch would be helpful.

Once this is fixed for buttons, I think a fix for improved kbd: support with a background color and a border should be trivial.

**Comment by vogella** [comment]
Test PR https://github.com/asciidoctor/asciidoctor-pdf/pull/452

**Comment by vogella** [comment]
Currently blocked by #350. @mojavelinux Any change to merge #350 for the next alpha?

@fap- FYI

**Comment by mojavelinux** [comment]
Ideally, the theme should be able to control the appearance of the button. There will be some limitations, since we can't do things like a shadow, but if we support background color and border in addition to the normal font settings, it should provide a lot of flexibility.

While #350 has some nice ideas, that's not exactly how I plan to implement it. I don't like the hardcoded colors.
