### ISSUE TITLE
theming guide: remove heading_font_size

### ISSUE THREAD

**Issue by igagis** [asciidoctor/asciidoctor-pdf#460]
The PDF theming guide for [heading](https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#heading) says that there is a *font_size* attribute. But actually setting the attribute has no any effect. Only setting *font_size* for specific *header_h2* or 3 etc. has effect.

So, the theming guide has to be corrected, *font_size* to be removed from *heading*.

**Comment by mojavelinux** [comment]
Thanks for pointing this out. This just needed to be documented more clearly. The base theme assigns a font size to each heading level. In order to get the value to inherit from `heading_font_size`, you have to set the value of the heading level to null.

While documenting this behavior, I discovered that the theme loader was quoting `null` values. So I also implemented a fix so that doesn't happen. Until then, you can use the value `~`.

**Comment by mojavelinux** [comment]
See #461.
