### ISSUE TITLE
Option to show the link in the generated PDF

### ISSUE THREAD

**Issue by vogella** [asciidoctor/asciidoctor-pdf#463]
For printouts I would like to show the URL.

http://www.vogella.com[vogella] should be become something readable.

Maybe 
vogella [http://www.vogella.com]

Is this option already available? If not, could you add it?

**Comment by mojavelinux** [comment]
I agree. I think we can link this to the already proposed "print" mode. We should mimic what we do in the print styles in the HTML output.

![print-link](https://cloud.githubusercontent.com/assets/79351/15659263/46a9f388-2685-11e6-8903-4534e4169b6a.png)

**Comment by mojavelinux** [comment]
I propose the following attribute:

```
-a media=print
```

**Comment by vogella** [comment]
> -a media=print

+1 assuming that the Asciidoctor Gradle task can use that.

**Comment by mojavelinux** [comment]
Absolutely.

Note that this is similar to the option the DocBook toolchain named `ulink.show`. There's also an option `ulink.footnotes` which shows the link in a footnote. I'd like to start with just showing it inline. Then we can go from there.

In addition to `media=print`, we could also honor the individual attribute `reveal-uri` (or something).

**Comment by vogella** [comment]
For reference, DocBook does it already nicely:

````<ulink url="https://jenkins-ci.org">Homepage of the Jenkins project</ulink>```` results in:
Homepage of the Jenkins project [https://jenkins-ci.org]

**Comment by mojavelinux** [comment]
I prefer the round brackets to the square brackets. I think the square brackets don't kern well against the text and look too abrupt.

**Comment by vogella** [comment]
Round brackets look also fine. 

As long as the link is visible in the printout. Without this option I have to decide if the HTML output will look "unusual" or if the PDF printout is harder to use, as the links are missing.

**Comment by mojavelinux** [comment]
It turns out that this was already implemented, enabled by the showlinks attribute. However, I have updated the functionality so it works as described in this issue. Setting either of these two attributes will reveal the URI for any non-bare link:

* show-link-uri
* media=print

I have also surrounded the link in square brackets in normal font with a slightly reduced font size (0.9em).

**Comment by vogella** [comment]
Awesome, that will remove a lot of painful editing work for me.  Can a new version of the plug-in be published? I do not see v1.5.0.alpha.12 yet in bintray: https://jcenter.bintray.com/org/asciidoctor/asciidoctorj-pdf/

**Comment by mojavelinux** [comment]
The new version is available only as a RubyGem at the moment. (https://rubygems.org/gems/asciidoctor-pdf/versions/1.5.0.alpha.12). We have plans to set up an automated release pipeline so that AsciidoctorJ PDF releases get triggered automatically by Asciidoctor PDF (Ruby) releases. But we're not there yet.

Btw, I'm going to be making another release in the next couple of days which bring a few more features you were looking for. Depending on Robert's availability, we might have AsciidoctorJ PDF skip the alpha.12 release and go right to alpha.13.

**Comment by vogella** [comment]
> Btw, I'm going to be making another release in the next couple of days

Thanks for that. I'm already excited about the solution for #455, this will help me also a lot.
After these two issues, solved I will only have to fight with #464. :-)

**Comment by vogella** [comment]
Create a separate issue for the asciidoctorj release https://github.com/asciidoctor/asciidoctorj/issues/505

**Comment by mojavelinux** [comment]
:+1:

**Comment by vogella** [comment]
FYI - the old setting with  :showlinks: does not work anymore. Totally fine for me, switching to :show-link-uri: is easy but I justed wanted to ensure that this is intentional and your are not breaking existing clients.

**Comment by mojavelinux** [comment]
That is correct. I renamed the attribute. Since we're still in alpha, there's no guarantee for backwards compatibility (though I've been careful not to cause too much disruption).
