### ISSUE TITLE
Install alpha 12 on Ruby 1.9.3?

### ISSUE THREAD

**Issue by stallio** [asciidoctor/asciidoctor-pdf#528]
I've been running alpha 11 on Ruby 1.9.3 for a while with no problem but when I try to install alpha 12 I get:

ERROR: Error installing asciidoctor-pdf:
     prawn-svg requires Ruby version >2.0.0.

I do have prawn 1.3.0 installed as directed in the install instructions but that doesn't seem to cut it anymore.

Alpha 12 now requires prawn-svg 0.25.1, which requires Ruby 2.0.0. If this means that Ruby 1.9.3 no longer works with this version, then that should be noted in the install instructions.

**Comment by mojavelinux** [comment]
Thanks for pointing this out. It looks I inadvertently broke 1.9.3 support by upgrading prawn-svg. (This is one of the many reasons it's so important to get that test suite in place). I'll need to fix this in alpha 13 (which is due out later this week).

I'll still need to update the install instructions to pre-install prawn-svg 0.21.0, similar to what has to be done with prawn.

It's becoming harder and harder to support 1.9.3 because our dependencies are dropping support for it.

**Comment by mojavelinux** [comment]
Of course, the easiest path for you would just be to move to Ruby 2+, if you can.

**Comment by stallio** [comment]
Thanks, I think I hit a snag last time I tried to switch to to 2+ but this is a good excuse to try again.
