### ISSUE TITLE
Add ability to start page numbering after first page of body

### ISSUE THREAD

**Issue by cascer1** [asciidoctor/asciidoctor-pdf#560]
I would like support to reset page numbers from an arbitrary position in the document. I would also like to be able to use roman numerals as page numbers. 

for example, my document has an introduction that I would like to give a separate numbering scheme, so the final page numbers should be something like 

i, ii, iii, iv, 1, 2, 3... 20, 21

**Comment by barspi** [comment]
I was looking for exactly that. (roman numeral section, followed by the normal section where I choose which one is "page 1")

**Comment by nicolas33** [comment]
I need something similar. The page numbering must be like: 

1, 2, 3.. 20, 21, i, ii, iii, iv

where the roman numbering is for the appendices.

**Comment by chuck-confluent** [comment]
Adding my voice to the choir, although I'm not sure if my requirement is slightly different.

I have a single document that `includes` other documents to make a book. I would like each `include`ed part to have its own page numbering in the footer. Something like `{chapter-number} - {chapter page number}`. From experimentation, modifying a custom `{chapter-number}` attribute throughout doesn't work because the footer appears to happen last, and so only uses the final value of custom attributes.

Perhaps better would be to have a "progress indicator" like `{chapter-number} - {chapter page number}/{total number of pages in chapter}`

Let me know if this makes sense.

**Comment by mojavelinux** [comment]
If we focus on the initial request of allowing the arabic page numbering to start beyond the first page of the body, I think we can achieve it. Something like:

```
page:
  numbering:
    start_at: 4
```

The value is assumed to be a physical body number. In other words, the keyword `body` is `1`, and here the 4th physical body page will be virtual page number 1. All pages before are in roman numerals.

> 1, 2, 3.. 20, 21, i, ii, iii, iv

This is outside the scope of the design of this converter.

@chuck-confluent what you are asking about would be an entirely different request. I have already been thinking about setting an implicit attribute in the running content to hold the chapter number. There may be room to store the page-number-of-chapter as well, but I'm not sure.

> From experimentation, modifying a custom {chapter-number} attribute throughout doesn't work 

No, it would not. The running content should only be accessing implicit attributes or attributes defined in the document header.
