### ISSUE TITLE
Use asciidoctor-theme as default

### ISSUE THREAD

**Issue by leif81** [asciidoctor/asciidoctor-pdf#60]
I'm proposing we switch the default theme to asciidoctor-theme.yml because I think it would be a good to have all asciidoctor backends, browser extensions, and editor extensions using the same theme by default. That way when someone switches between backends, browsers, editors, etc they get a common look and feel / branding. We did this for Brackets (asciidoctor/brackets-asciidoc-preview#9 ) not too long ago.

WDYT?

**Comment by mojavelinux** [comment]
Since this came up again on the mailinglist, I wanted to restate my position. The problem is that, right now, there's really no such thing as an Asciidoctor theme. While default stylesheet for the HTML output presents a familiar Asciidoctor look and feel, it's never really been vetted as a reusable theme. Again, we need a branding effort that will define the parameters of an Asciidoctor look and feel. Once we have that, then I'm absolutely in support of defining a theme that implement it.

On a side note, we might want to think about adding a theme repository that offers a number of different themes for Asciidoctor PDF. I think that's something we should do once we are in beta or perhaps even after the 1.5.0 release (when the theming engine is more stable).

**Comment by mojavelinux** [comment]
Cleaning up old issues...

The default theme for Asciidoctor PDF was designed to provide a typical, no-frills, professional-looking PDF document by default. That's what most users are after based on the input I have received. However, I recognize this look won't suit everyone. That's why we've made the theming system extensible.

If someone wants to contribute an "asciidoctor" theme to the repository, I'd be happy to accept it. However, to avoid having to bundle more fonts in the gem, that theme would need to use the NotoSerif and M+ fonts that are already bundled. So it would still slightly differ from the default stylesheet shipped with the HTML converter.
