### ISSUE TITLE
Consequent NOTE: signs have different sizes

### ISSUE THREAD

**Issue by habamax** [asciidoctor/asciidoctor-pdf#618]
The following 
```
NOTE: Предыдущая версия плагина не поставляется вместе с данным Hotfix'ом.

NOTE: Номер мажорной версии предыдущего релиза не отличается от версии текущего релиза.
```
gives:
![asciidoctor-pdf-notes](https://cloud.githubusercontent.com/assets/234774/19230275/5da7958a-8edc-11e6-8936-ede423f00033.png)

Note that signs sizes are different.

**Comment by habamax** [comment]
HTML export is fine though

**Comment by mojavelinux** [comment]
This behavior is as expected. It is due to the fact that the first
admonition only has one line and thus not enough vertical space to fit the
icon at the preferred size. If you want all icons the same size, you need
to customize the theme to make the preferred size smaller or the padding on
the admonition content greater. See the theming guide for details.

We could consider default settings that would allow the preferred size to
fit in the case of a single line.

**Comment by habamax** [comment]
I see, thx for clarification.

I can't find 'preffered' size in a documentation though.

I tried to set up:

```
admonition:
  icon:
    note:
      size: 32
```

and it affects only multirow note:
![asciidoctor-pdf-notes](https://cloud.githubusercontent.com/assets/234774/19234082/193ff6e2-8ef2-11e6-98e6-f34ae42bb0a5.png)

**Comment by mojavelinux** [comment]
You found the right property. 24 is the default, so you have to go smaller
like 18.

**Comment by habamax** [comment]
So it should be somehow aligned with the basefont size?

**Comment by habamax** [comment]
BTW, I have just tried:

```
admonition:
  column_rule_style: dotted
  column_rule_width: 2
  icon:
    note:
      size: 32
```

column_rule_stuff have no effect

**Comment by habamax** [comment]
And the last question, am I correct that I have to set up sizes for every icon type?

**Comment by mojavelinux** [comment]
The column rule change is not yet in a release. It will be in alpha.14.
