### ISSUE TITLE
Add support for pdfwidth to inline images

### ISSUE THREAD

**Issue by vogella** [asciidoctor/asciidoctor-pdf#620]
pdfwidth does not work for an inline image.

```
image:model_spy_targetplatform.png[pdfwidth=1%]
```

![image](https://cloud.githubusercontent.com/assets/139910/19249892/06d45fb6-8f38-11e6-85de-1d97f488bc5c.png)

I upload soon an example via a PR.

**Comment by vogella** [comment]
This issue should is demonstrated via https://github.com/asciidoctor/asciidoctor-gradle-examples/pull/32

**Comment by mojavelinux** [comment]
pdfwidth is not yet support for inline images. I've been meaning to file an issue. You took care of it for me :)

**Comment by mojavelinux** [comment]
In your case, you just need to change the single colon to a double colon since it seems you mean in insert a block image (aka figure).

**Comment by vogella** [comment]
> you just need to change the single colon to a double colon

Thanks, that was really my intent. My problem is fixed, but I agree the pdfwidth support for inline images would a nice to have.

**Comment by vogella** [comment]
@fap- can you fix this and send a PR to @mojavelinux?
Not very important for us, but I would guess, relatively simple to fix and I hope this helps @mojavelinux

**Comment by fap-** [comment]
@mojavelinux I'm working on this but I could use some help.

My understanding is that inline images get converted to pseudo html in [AsciiDoctor:Pdf:Converter#convert_inline_images](https://github.com/asciidoctor/asciidoctor-pdf/blob/b3cd0de7ff6f744b0b8badd7cd90001f96d1eb77/lib/asciidoctor-pdf/converter.rb#L1784).
I assume that this is where the `pdfwidth` attribute is currently lost?
If this is right then my solution would be to add pdfwidth to the pseudo html so the node that enters [AsciiDoctor:Pdf:Converter#convert_image](https://github.com/asciidoctor/asciidoctor-pdf/blob/b3cd0de7ff6f744b0b8badd7cd90001f96d1eb77/lib/asciidoctor-pdf/converter.rb#L892) comes with this attribute.
Could you please point me to the location where the pseudo html is parsed?

**Comment by mojavelinux** [comment]
> My understanding is that inline images get converted to pseudo html in AsciiDoctor:Pdf:Converter#convert_inline_images.

Correct. Inline elements first get converted a pseudo-html and then handled by the [text formatter](https://github.com/asciidoctor/asciidoctor-pdf/blob/b3cd0de7ff6f744b0b8badd7cd90001f96d1eb77/lib/asciidoctor-pdf/formatted_text/transform.rb#L75-L87). (This is necessary since parts of the AsciiDoc / Asciidoctor parser assume that the content has an SGML structure).

> I assume that this is where the pdfwidth attribute is currently lost?

Yes, the pdfwidth either needs to be passed on or resolved to a width when encoded into the pseudo-html. There are edge cases when resolving a percentage value in the convert method will lead to an incorrect value since we don't yet know what page we're on (and thus don't know the precise page properties).

The absolute correct thing to do would be to include units with the value of the width attribute. The "pdfwidth" is really just "width" for the PDF converter. We'd then defer resolution to an absolute (pt) value until the text formatter. This may require enhancing the resolve_explicit_width to not convert to pt.

But we could take this in two stages. First we can resolve to an absolute pt value in the convert method. Then we can go deeper and defer that resolution until the text formatter, passing along an unresolved value with units.

**Comment by fap-** [comment]
So we would defer the conversion until the Formatter is called because the cursor in Prawn::Document::BoundingBox is on the right page at this point and we can calculate the correct value?

> The absolute correct thing to do would be to include units with the value of the width attribute. The "pdfwidth" is really just "width" for the PDF converter. We'd then defer resolution to an absolute (pt) value until the text formatter. This may require enhancing the resolve_explicit_width to not convert to pt.

Wouldn't it be possible to keep resolve_explicit as it is and call it after the formatter parsed the pseudo html? (assuming the formatter would know the converter/Prawn::Document)
I'll look into it next week.

**Comment by mojavelinux** [comment]
> So we would defer the conversion until the Formatter is called because the cursor in Prawn::Document::BoundingBox is on the right page at this point and we can calculate the correct value?

That would be the most correct thing to do.

> Wouldn't it be possible to keep resolve_explicit as it is and call it after the formatter parsed the pseudo html? 

Yes, but then we would have to pass pdf_width to the psuedo-html. I'd like to avoid that. The pseudo-html should only pass a width value that contains units. Then, the formatter will know exactly what to do with that information without having to do any additional resolution.

Here's an example of the conversion that would occur in the converter:

* width=500 => width="500px" (or width="375pt")
* width=500, pdfwidth=1in => width="1in"
* width=500, pdfwidth=75% => width="75%"

As you can see, we need to get down to a single width value and pass that on.

**Comment by mojavelinux** [comment]
We might even want to resolve the width to either pt or %. We don't know what to do with % yet, but all other units we can convert to pt since those units have fixed meaning.

**Comment by fap-** [comment]
I pushed a new version. I didn't touch resolve_explicit_width for now because it also gets called from other locations.
Is this more or less how you had it in mind?

**Comment by mojavelinux** [comment]
Yes, that looks like what I had in mind. Let me do a bit more in-depth review to make sure we aren't missing something, then we'll proceed.

**Comment by mojavelinux** [comment]
Review completed. See PR.

(This issue has been a lot trickier to solve than I expected. Lots of nuance.)
