### ISSUE TITLE
label lists and source code blocks page break issue

### ISSUE THREAD

**Issue by jmarley** [asciidoctor/asciidoctor-pdf#64]
Hi,
I really like this new addition to asciidoctor, it is really sweet. I noticed an issue/feature though that I wanted to bring to your attention. When I have an list and then a subsection of the list is source code block that wraps more than 1 page pdf builder doesn't recognize the fact that the list header belongs on the preceeding line of the text vice creatinga  page break specifically for the new code.
e.g. 

```
list-element::
[source,python]
-----
''''bunch of code that spans more than a page'''
-----
```

Regardless of whether I create a page break before the list-element the list element always has a page break between the source code.

**Comment by mojavelinux** [comment]
If the code can fit on a single page, it will automatically be advanced to the next page. If it cannot fit on a single page, it will begin at the cursor and spill over to the next page.

That gap between the term and the description caused by the block being advanced to the next page cannot be changed.

We're discussing a possible solution to control the "breakability" of blocks in this issue: #509.
