### ISSUE TITLE
UTF-8 characters do not render correctly in PDF when used in heading

### ISSUE THREAD

**Issue by memmaker** [asciidoctor/asciidoctor-pdf#647]
When using the default settings (default style and fonts) the UTF-8 characters (in this instance I was testing with German Umlauts ä,ö,ü) just don't show up. After reading up on the bundled fonts just being subsets of the Unicode range, I included a custom font with the relevant UTF-8 characters present.

After setting up a custom style file, referencing the new font files and assigning them to the heading and base text the rendering was still not satisfying. The new result was a misaligned UTF-8 character.

Interestingly enough, I found a fix for the second level headings:
Adding a manual reference anchor in front of the Heading fixes the problem. Unfortunately this only works for this level and does not affect the other subheadings.

Problematic Heading:
```
== Überschrift
=== Überschrift Level 2
```

Workaround for first level:
```
[[uberschrift]]
== Überschrift
=== Überschrift Level 2
```

Does NOT work for second level:
```
[[uberschrift]]
== Überschrift
[[uberschrift_second]]
=== Überschrift Level 2
```

Expected behaviour:
The headings should just work with UTF-8 characters without the user having to supply a non-UTF-8 reference anchor.

**Comment by mojavelinux** [comment]
Can you tell me which version of Asciidoctor PDF you are using?

**Comment by memmaker** [comment]
asciidoctor-pdf -V
Asciidoctor PDF 1.5.0.alpha.13 using Asciidoctor 1.5.5 [http://asciidoctor.org]
Runtime Environment (ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)

**Comment by mojavelinux** [comment]
I don't know why these characters wouldn't show up. I also can't explain why adding an ID would make any difference. The headings show up just fine when I convert the document using alpha.13 and the latest master. Can you send me the generated PDF to see if you are getting something different than me? (Just dump it on a temporary file hosting service if you can't attach it the issue).

The bundled fonts include glyphs for all major and many minor languages. German is included.

Creating a custom font for Asciidoctor PDF requires special preparation...specifically with how kerning information is saved. I still intend to document the steps necessary to prepare the font using FontForge. Basically, you need to open the TTF font and save it with the old-style kern table option enabled. Otherwise, the spacing between letters is not correct.

**Comment by memmaker** [comment]
I am sorry. It might be my fault and not actually an issue. I just noticed, while trying to prepare a test document, that re-entering the missing characters into the source AsciiDoc leads to them showing up in the rendered PDF. My best guess is that the relevant characters have been copy pasted from a non-UTF-8 source. How they could still end up not properly encoded in the source file my atom editor was saving as UTF-8 to disk I don't know. So I am closing this issue for now and am sorry for taking your time.

**Comment by mojavelinux** [comment]
>  How they could still end up not properly encoded in the source file my atom editor was saving as UTF-8 to disk I don't know. 

Actually, that explains it perfectly. Just because you can see the character in the editor doesn't mean it's the right character in the file. What matters is what glyph Asciidoctor PDF (and under that Prawn and under that Ruby) sees in the file. Chances are, it wasn't what you typed.

It's critically important that you make sure that the editor is in UTF-8 mode. Otherwise, it's essentially making a corrupt file. The operating system likes to trick the eye of the beholder.
