### ISSUE TITLE
Be able to set custom page sizes for pdf 

### ISSUE THREAD

**Issue by IbnSaeed** [asciidoctor/asciidoctor-pdf#65]
Hello

Would it be possible to add the ability to set custom page sizes such as A5 or using any custom dimensions such as 134mm x 233mm etc.

Specifically targeting Printed Books

**Comment by IbnSaeed** [comment]
Was this released in 1.5 ?

**Comment by mojavelinux** [comment]
Not yet. This is still scheduled to be completed. I'll mark it as a hackfest item as it's a nice self-contained change.

**Comment by mojavelinux** [comment]
I decided to go with the attribute name `pdf-page-size`. Note that this attribute now supports setting the width and height using dimensions with units, including in, cm, mm and pt.

For example:

```
:pdf-page-size: [8.25in, 11.69in]
```

Units can also be used in the theme file.

**Comment by mojavelinux** [comment]
Let me know if this looks good and I'll merge.

**Comment by mojavelinux** [comment]
I've added support for the syntax `width x height` (e.g., `8.5in x 11in`). I also switched to a manual and more strict parser instead of delegating to YAML.

**Comment by mayeulk** [comment]
Hi,
I had difficulties having this work (especially since https://github.com/asciidoctor/asciidoctor-pdf/issues/1518 says "widht x heigh" is OK) **with the command line**. So this might help others.
This works for me:

     asciidoctor-pdf --attribute=pdf-page-size="[14cm, 14cm]" myfile.asciidoc

The following DOES NOT worked:
`asciidoctor-pdf  attribute=pdf-page-size="[14cm x 14cm]" action-bookmark.asciidoc`

Config:
Asciidoctor PDF 2.3.19 using Asciidoctor 2.0.23 [https://asciidoctor.org]
Runtime Environment (ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)

**Comment by mojavelinux** [comment]
Please ask questions in the project chat at https://chat.asciidoctor.org. The issue tracker is not a support forum, especially closed issues.
