### ISSUE TITLE
Can I use a locally produced gem in my Gradle build

### ISSUE THREAD

**Issue by vogella** [asciidoctor/asciidoctor-pdf#650]
@fap- is currently build the Asciidoctor-pdf gem so that we can benefit from not yet released versions.

@mojavelinux describes how to use a released Ruby version of asciidoctor in https://github.com/asciidoctor/asciidoctor-pdf/issues/572#issuecomment-248848703

Is it also possible to use a locally produced gem in a Gradle build? We tried to use flatdir but failed and our attempts to put it into the local Gradle cache or .m2 cache were also not successfully.

**Comment by fap-** [comment]
Hey there,

so far we tried to get the gradle jruby to load the development version of asciidoctor-pdf from a local maven or gradle repository/cache, but we weren't successful.

Another option would be to locally host the gem with rubygems_servlets, but this feature is [undocumented](https://github.com/torquebox/rubygems-servlets/issues/15) so far.

Would it be alright with you if we uploaded the current asciidoctor-pdf dev version to rubygems.org, under our own 'namespace'? e.g. 'vogella-asciidoctor-pdf-dev'
This would probably solve our problem.

**Comment by mojavelinux** [comment]
I would really prefer if you didn't add a development gem to rubygems.org since it will stick around forever and eventually confuse people.

There is a way to specify a path to a local directory or file as the gem dependency using the JRuby Gradle plugin. If you figure this out, it will help out a lot of other people who have tried. We can then document it in the Gradle plugin README so we don't forget.

**Comment by mojavelinux** [comment]
See https://github.com/jruby-gradle/jruby-gradle-plugin/issues/102

**Comment by mojavelinux** [comment]
I figured out how you can do this. It's a bit of a hack, but it should get the job done for now.

First, you need to build the gem locally and store it somewhere.

```
git clone https://github.com/asciidoctor/asciidoctor-pdf.git
cd asciidoctor-pdf
bundle
bundle exec rake build
```

The gem file can be found under pkg/.

We'll need to manipulate the configuration for the JRuby Gradle plugin, so you need to declare it:

```
plugins {
  ...
  id 'com.github.jruby-gradle.base' version '1.3.3'
}
```

In order to use a local gem from Gradle, we have to specify all the dependencies of that gem manually.

```
dependencies {
  gems 'rubygems:prawn:2.1.0'
  gems 'rubygems:prawn-table:0.2.2'
  gems 'rubygems:prawn-templates:0.0.3'
  gems 'rubygems:prawn-svg:0.25.2'
  gems 'rubygems:prawn-icon:1.3.0'
  gems 'rubygems:safe_yaml:1.0.4'
  gems 'rubygems:thread_safe:0.3.5'
  gems 'rubygems:treetop:1.5.3'
}
```

Next, override the JRubyPrepare task to use all these dependencies plus the one you built:

```
import com.github.jrubygradle.JRubyPrepare
task customJRubyPrepare(type: JRubyPrepare) {
  dependencies project.configurations.gems
  dependencies file('development-gems/asciidoctor-pdf-1.5.0.alpha.14.dev.gem')
  outputDir buildDir
}
```

Finally, make sure that the asciidoctor task depends on customJRubyPrepare and that it requires asciidoctor-pdf.

```
asciidoctor {
    dependsOn customJRubyPrepare
    requires 'asciidoctor-pdf'
    gemPath customJRubyPrepare.outputDir
    ...
}
```

You should see that it uses the Asciidoctor PDF gem from your local file system.

I'd like to see this supported more easily out of the box in the plugin.

**Comment by fap-** [comment]
Thank you very much! 
I just tried it out and it works. Also way better than the other options.

**Comment by mojavelinux** [comment]
+1

**Comment by mojavelinux** [comment]
This information is now referenced in the contributing code guide. See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/CONTRIBUTING-CODE.adoc
