### ISSUE TITLE
Asciidoctor PDF theme inline content error

### ISSUE THREAD

**Issue by pjwin** [asciidoctor/asciidoctor-pdf#653]
I have a theme with the following footer:
```
footer:
  recto_content:
    left: '1/2'
```
It seems the '1/2' is being evaluated as a mathematical expression instead of being rendered as plain text as desired.

`Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.3:process-asciidoc (generate-pdf) on project docs: Execution generate-pdf of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.3:process-asciidoc failed: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method ``include?' for 0.5:Float -> [Help 1]`

I tried escaping with a backslash `'1\/2'` but then both slashes are rendered as text.

**Comment by pjwin** [comment]
I found a workaround. I defined a custom document attribute, and then referred to it in the theme. Now I can have forward slashes in the pdf footer between numbers without it being evaluated as a mathematical expression.

my asciidoc:
```
= Document Title
:footerContent: 1/2
```

my theme:
```
footer:
  recto_content:
    left: '{footerContent}'
```

**Comment by mojavelinux** [comment]
I believe this has since been fixed if you use the latest version of Asciidoctor PDF.

```
footer:
  recto:
    right:
      content: 1/2
```

We now explicitly bypass mathematical expressions in content values. If you still need the mathematical expression, you can use a custom theme variable:

```
custom_value: 1 / 2
footer:
  recto:
    right:
      content: $custom_value
```

However, that raises an error because we aren't coercing the content value to a string (which is actually the original bug). I'll address that issue.
