### ISSUE TITLE
highlight.js

### ISSUE THREAD

**Issue by JBR69** [asciidoctor/asciidoctor-pdf#673]
Hi,

I use **highlight.js** to color code blocks for HTML documents.
Is there a way to have the same colors in the generated PDF?

Thank you
Jérôme

**Comment by mojavelinux** [comment]
Using Rouge, this is possible (once alpha.14 is released). See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#source-highlighting-theme.

**Comment by JBR69** [comment]
ty
I'm trying the example of your documentation but I have this error
```
custom.rb:4:in `<module:Themes>': uninitialized constant Rouge::Themes::CSSTheme (NameError)
```
I continue my research but if you have the solution ...

**Comment by JBR69** [comment]
**custom.rb** must begin with `require 'rouge'`

**Comment by mojavelinux** [comment]
Oops, you are right. I forgot to commit that change to the example. Fixed!

**Comment by mojavelinux** [comment]
Otherwise, does it work out for you?

**Comment by JBR69** [comment]
Yes it's work.
Now I must configure correctly the colors :-)

I saw a problem if I use conum in my block, but I don't know if it's a asciidoctor-pdf's bug or rouge's bug.
For example,
```
[source, apache]
----
<VirtualHost 0.0.0.0:2080>
       ServerAdmin name@domain.tld
       ServerName servername.domain.tld <1>
       ServerAlias www.servername.domain.tld
       ....
</VirtualHost>
----
<1> aaaaaa
```
The keyword `ServerAlias` is not colored because there is a conum in the line before.
If I delete conum, it's OK.
Other workaround, insert after une conum a comment line
```
       ServerAdmin name@domain.tld
       ServerName servername.domain.tld <1>
       # Add a comment ligne to colorize works in the next line !
       ServerAlias www.servername.domain.tld
```

**Comment by mojavelinux** [comment]
Unfortunately, this is where the callouts and the code highlighter don't agree since there's no valid way to add a trailing comment in an Apache conf file. This is where you'd need to specify the callouts in the block attributes, which is still a pending feature. See https://github.com/asciidoctor/asciidoctor/issues/598

**Comment by mojavelinux** [comment]
Actually, no, this is something different. We are removing the callout numbers before rouge highlights. The problem seems to be that we are removing the trailing character that rouge is looking for to end the line. That does seem to be a possible bug in what we are doing in Asciidoctor PDF.

**Comment by mojavelinux** [comment]
I see what is happening. We are leaving behind the space before the callout number. So this is what Rouge is seeing:

```
ServerName servername.domain.tld \n
```

Rouge seems to be overly sensitive in this case and refusing to highlight if there is a space before the endline. I think you should file that with [rouge](https://github.com/jneen/rouge) because a trailing space is valid (at least according to VIM syntax highlighting).

**Comment by mojavelinux** [comment]
Btw, you can fix it by not using a space before the callout number. Though, the result isn't great:

```
ServerName servername.domain.tld<1>
```

**Comment by JBR69** [comment]
that's great.
Thank you very much for your great responsiveness; it's very pleasant

**Comment by mojavelinux** [comment]
I'm glad to be of service. I'm not always as responsive as I'd like to be, but I certainly try!
