### ISSUE TITLE
undefined method `on_page_create' for #<Asciidoctor::Pdf::Converter:0x007ff89307f6c8>

### ISSUE THREAD

**Issue by jninja** [asciidoctor/asciidoctor-pdf#68]
The following error appears when trying to convert a document:

undefined method `on_page_create' for #<Asciidoctor::Pdf::Converter:0x007ff89307f6c8>

This error seems new to asciidoctor-pdf-1.5.0.alpha.6 release.

**Comment by jessedoyle** [comment]
Note that as of Prawn v2.0.0, the `on_page_create` method has been reinstated into the Prawn interface. 

If this was the only reason to stay on an older Prawn dependency (1.2.1), I propose to update that dependency to the latest current version (2.0.1).

See: https://github.com/prawnpdf/prawn/blob/master/CHANGELOG.md

**Comment by mojavelinux** [comment]
The plan is definitely to upgrade to Prawn 2 as part of the march towards a 1.5.0. I would also like to make use of the new View API instead of the currently inheritance. See #53

**Comment by mojavelinux** [comment]
I think we should add a check for this method (e.g., `respond_to :on_page_create?`) so that at least the processor doesn't crash if the wrong version of Prawn is used. This will reduce support issues. We could even consider issuing a warning if this scenario is detected.

**Comment by mojavelinux** [comment]
Btw, it seems like people get into this situation when they update their gems. The update command does not seem respect the version requirements in the Gemfile (or gemspec). Perhaps we can mention in the README how we recommend updating gems (remove Gemfile.lock and run bundle again).

**Comment by mojavelinux** [comment]
In the proposed pull request, I've upgraded Prawn and added a check for the existence of the on_create_page method since its status is questionable.

**Comment by mojavelinux** [comment]
I'm fine with upgrading Prawn to 2.0.1, but it does introduce some challenges:

* you must use at least Ruby 2.0.0 (at installation time)
* installing Asciidoctor PDF under JRuby becomes a pain since you have to enable 2.0 to allow Prawn to be installed (and 2.0 mode is still flaky under JRuby 1.7) (best advice: Use JRuby 9.0.0.0)
* using AFM fonts is pretty much out since Prawn halts when it finds a character it can't encode to WINANSI (before it replaced it with an underscore)

Aside from those hurdles, things seem to work out just fine. In fact, if you can get past installation, you can use Prawn with Ruby 1.9.3.
