### ISSUE TITLE
More granular control over PDF template?

### ISSUE THREAD

**Issue by r0ckarong** [asciidoctor/asciidoctor-pdf#696]
I've been looking through the project(s) now for a bit and I can't find the right place where the PDF template is technically defined. I have modified the YAML file that allows me to style it's parameters but not the actual layout itself. Where is that handled? Can I modify this? I would like to add/move around some elements like the Author information away from the title page.

Is this possible?

**Comment by mojavelinux** [comment]
There is no PDF template in Asciidoctor PDF. Just a Ruby-based converter class. In order to change the position / layout of elements, you must extend this class*. The YAML theme file is designed for altering the style properties (such as font and border properties) of elements, not their positioning (in the spirit of CSS). (The one exception are elements on the title page, which can be rearranged or hidden).

For example of extending / patching the converter, refer to the work Matt Raible did for his InfoQ Mini-Book:

* [Blog post](https://raibledesigns.com/rd/entry/re_customizing_an_asciidoctor_pdf)
* [Git repository](https://github.com/mraible/infoq-mini-book)

The goal of Asciidoctor PDF is to provide a simple mechanism for creating a PDF from an AsciiDoc document without having to mess with complicated XSL templates like the DocBook toolchain requires. If you need that level of control over the design, then the DocBook and LaTeX toolchains are very powerful for that purpose and are still available to you by writing in AsciiDoc. Asciidoctor PDF is just another approach.

\* Keep in mind that due to #53, the API used by the converter may change. Just keep in mind that you may have to rework your code after we make that change.

**Comment by barspi** [comment]
A great idea could be to have a converter that uses templating based, maybe, on a YAML file where you specify certain elements of the document and the order in which they must appear.
I know.. it's easy to say it and I could do it if I had a lot of free time in my hands to first learn ruby better and all the API... but I don't at the moment :-)

In any case... this could be done in a future milestone (if someone is not working in something similar/better already)

**Comment by mojavelinux** [comment]
It's extremely unlikely at this point that we're going to invest anymore in the aspects of the layout the theme can control. What we've learned is that while being able to influence the appearance of the elements is reasonable, doing manual layouts with this stack is just too costly (both in terms of development time and runtime). Instead, we're going to start looking into an AsciiDoc -> HTML/CSS -> PDF workflow that will give you endless possibilities for both styling and layout.

Asciidoctor PDF has served it's purpose, which is to typeset a flow document from top to bottom and allow you to influence the appearance of elements using colors, fonts, spacing, and borders. Anything beyond that is really outside the goals of the project.
