### ISSUE TITLE
Missing international characters in the bundled font

### ISSUE THREAD

**Issue by miko** [asciidoctor/asciidoctor-pdf#72]
For this adoc file I get my national letters stripped out of my name, because:
"Asciidoctor PDF uses custom fonts. When I created the font files that are bundled in the gem, I did not include all international characters in the font (something I've been meaning to fix)." (see issue #69 )

```
= Hello World
Michał Kołodziejczyk <miko@example.com>
1.0.0, 2014-12-10

Hello world!
```

**Comment by kubamarchwicki** [comment]
I see the international characters working with Asciidoctor PDF

**Comment by mojavelinux** [comment]
It's highly dependent on which characters. When I produced the current Noto
Serif fonts, I included a broad range of characters, but not Cyrillic and
the CJK characters are not part of that font. That's the change that's
being requested.

**Comment by kubamarchwicki** [comment]
Got it. Noto is a custom font? I see two options. I'm happy to help with extending the font with Easter European - if possible. 
Or a way to configure some other (less pretty fonts) - for the time being.

**Comment by mojavelinux** [comment]
I subsetted the font to make the gem smaller because at the time we had
lots of different fonts. Now we have room to include the full font, so it's
just a matter of swapping it in. I'll better document those steps when I do
so it's clear what the situation is.

**Comment by kubamarchwicki** [comment]
:+1:

**Comment by mojavelinux** [comment]
I want to clarify that we still have to process the font because Prawn
requires that we rewrite the kerning information to a separate table in the
font.

**Comment by mojavelinux** [comment]
@goeh Actually this is slightly different because you're pointing out missing characters in the code font. This is separate from the body font. I intentionally subsetted the code font to only include ASCII to keep the size of the gem down. While the fallback font will catch these now, we still may want to reconsider that decision as code can have non-ASCII characters (comments, strings, etc). Let's tackle that in a separate issue.

**Comment by mojavelinux** [comment]
@goeh You will no longer be missing characters in monospaced text, but those characters will be coming from the fallback font atm.

**Comment by mojavelinux** [comment]
With the proposed pull request (#281), I think we're in a much better position to support a broad range of languages out of the box. We now include Cyrillic (for Russian, etc), Vietnamese characters and Latin Extended-A (for Polish, Czech, Turkish, etc) in the subsetted Noto Serif font. There really isn't much we are leaving out that the main Noto Serif font doesn't provide. The fallback font will catch Japanese characters as well as missing glyphs in literal text.

The only glaring void that remains is Chinese because we aren't yet bundling a font that has offers a complete set of glyphs (only those used in Japanese too). I think the right solution for that problem is a separate gem, which has already been setup.

Of course, we simply can't cover all languages with a single font...which is why I think the right long-term solution is to have gems for each language group that isn't covered by the fonts shipped in Asciidoctor PDF core.

**Comment by mojavelinux** [comment]
I'm going to document somewhere under docs the character ranges that are included in the bundled fonts. I'll also document why we subset / regenerate the fonts and how to do it for your own font.
