### ISSUE TITLE
Funny Special Character cannot be represented by Font

### ISSUE THREAD

**Issue by stefan79** [asciidoctor/asciidoctor-pdf#722]
Hi,
I am fairly new to all of this, please have patience if any question is odd.

I am using a special font (Panton) which I had to convert form to TTF first. I am using UTF-8 only encoding and mostly everything is working like a charm. Thanks for the great software!

I am having a minor problem in certain edge cases:

## First Issue: Funny Character in ToC
In the TOC directly before the page number. I get funny box characters - I assume these characters or glyphs not supported by my font. When I switch to the default font the funny boxes vanish in the TOC.

See: <img width="481" alt="bildschirmfoto 2017-01-04 um 20 45 27" src="https://cloud.githubusercontent.com/assets/167485/21656527/c8d926e0-d2be-11e6-856d-0e44b14de3c3.png">

## Second Issue: Indents break Encoding
The second issue, occurs when I try to use indents:
`-- häufig in Echtzeit --` which is transformed to ` — häufig in Echtzeit — `. Looks OK in the browser, but in the PDF I get ugly box characters around the indents. 

See: <img width="223" alt="bildschirmfoto 2017-01-04 um 20 44 54" src="https://cloud.githubusercontent.com/assets/167485/21656528/c8e0fdf2-d2be-11e6-8510-f5cff263e916.png">

When I tries to troubleshoot this and remove the `base-font-family` attribute from the stylesheet and leave the other files untouched I get following warning from the command-line

`The following text could not be fully converted to the Windows-1252 character set:` for the paragraph containing the indent. Also I get a funny key character as padding character `¬—¬häufig in Echtzeit¬—¬`

See: <img width="243" alt="bildschirmfoto 2017-01-04 um 20 44 09" src="https://cloud.githubusercontent.com/assets/167485/21656525/c7ab7098-d2be-11e6-81db-c43a2bc4f1a1.png">

Oh and I use OSX and set UTF as my LC setting:
`LC_CTYPE=de_DE.UTF-8`

Am I doing something stupid? Are these bugs? Are there workarounds I can apply?

Thanks for your efforts

Stefan

**Comment by stefan79** [comment]
Hey guys,
I would appreciate any feedback. Even if it that the ticket does not make sense, or RTFM. I am kind of stumped to be honest.

Stefan

**Comment by mojavelinux** [comment]
This is due to missing characters in your custom font. I have yet to document it clearly (see #297). Suffice to say, when you introduce your own font, there are certain requirements you must make it meet in order to be compatible with Asciidoctor PDF. One of those requirements is to add, if missing, the glyphs Asciidoctor PDF uses for spacing. Otherwise, they show up as the missing glyph, which is the funky symbol you see.

It appears you're missing the no-break space. This one is easy to add. Open the font in Font Forge, copy the glyph from space (\u0020) and paste it in the no-break slot (\u00a0). Then just save the file. The font has to be saved with the old-style kern table format in order for kerning to work in Prawn.

**Comment by mojavelinux** [comment]
I just checked and I can confirm that Panton is missing the no-break space.

**Comment by mojavelinux** [comment]
I had to prepare a custom font for a client just yesterday and I found myself forgetting the process. Therefore, I've prioritized #297 because it's absolutely essential for understanding how to make custom themes in Asciidoctor PDF.

**Comment by stefan79** [comment]
Sorry for the delayed feedback. I installed the fallback font explicitly (like it says in the manual...my bad) and it is working perfectly - I don't care if it is a bit slower! Thanks!
