### ISSUE TITLE
asciidoctor-diagram error with asciidoctor-pdf

### ISSUE THREAD

**Issue by ssydorov** [asciidoctor/asciidoctor-pdf#739]
Hi All!
I got next error with adciidoctor-diagram and asciidoctor-pdf. Type of diagram is plantuml.

```
 source
 .The PlantUML Bob->Alice : hello
 [plantuml, diagram-classes2, svg]
 ----
 @startuml
 
 Боб->Алиса : hello
 Боб<--Алиса : пока
 @enduml

```
Command line:
>asciidoctor-pdf -r asciidoctor-diagram test.asc

Error:
The following text could not be fully converted to the Windows-1252 character set:
| Боб
"Боб" is in cyrillic letters 
and SVG file with incorrect font.

but html file with command 
>asciidoctor-pdf -r asciidoctor-diagram test.asc
is ok (without any error on console and correct SVG file.

Could you help me to solve problem?

thank!

**Comment by ssydorov** [comment]
additional comment from my side. Error exists in asciidoctor-pdf  and diagramm out format SVG. With PNG output everything are ok.

**Comment by ssydorov** [comment]
and with  asciidoctor result is ok

**Comment by mojavelinux** [comment]
It's necessary to set the font that Asciidoctor Diagram uses so Asciidoctor PDF knows how to draw the glyphs. Otherwise, the generated diagram will uses sans-serif, which gets mapped to an afm font. afm fonts only support basic Latin. (Remember, PDF is bring your own font: https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#built-in-afm-fonts).

To set the font used in the diagram, first create a file named plantuml.conf and populate it with the following content:

```
skinparam defaultFontName Noto Serif
```

Then pass that value to the `plantumlconfig` attribute in your AsciiDoc document (or pass the attribute to the CLI or API):

```
:plantumlconfig: plantuml.conf
```

Clear the cache of your diagrams. Now the diagrams should be generated using Noto Serif as the font. (You could also use M+ 1mn or M+ 1p Fallback).

If you want to use a different font, that font must first be defined in your Asciidoctor PDF theme. See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc for details.

**Comment by mojavelinux** [comment]
Now documented in README.

**Comment by diguage** [comment]
I test the solution. But it does not work. And I search the attribute name in the source code, it could not be found.

If I write the `skinparam defaultFontName Hiragino Sans GB` on the top of the PlantUML block, it is OK.

My environment is described at <https://github.com/asciidoctor/asciidoctor-maven-examples/issues/77#issuecomment-557384815>
