### ISSUE TITLE
How to use the same style file for asciidoctor and asciidoctor-pdf?

### ISSUE THREAD

**Issue by danijar** [asciidoctor/asciidoctor-pdf#746]
I want to compile the same source file into both HTML and PDF. Currently, I use two different commands and need to specify two style files, one in CSS and one in YAML.

```
asciidoctor -b html -a stylesheet=style.css chapter.ad
asciidoctor-pdf -a pdf-style=style.yml -a pdf-stylesdir='./' chapter.ad
```

Despite the language, the style files contain the same rules. Is there a way to use the same file to style both targets?

**Comment by mojavelinux** [comment]
No. While the styling system in Asciidoctor PDF is inspired by CSS, it is not CSS. Granted, you could in theory create an adapter for the theming system in Asciidoctor PDF that reads from CSS, but in the end you'd probably still need a different CSS file.

You can specify both styles in your document at the same time so you don't have to pass an attribute to the command:

```
= Document Title
:stylesheet: style.css
:pdf-style: style.yml
:pdf-stylesdir: .
```

However, I'm not sure that's what you are asking.

**Comment by danijar** [comment]
Thanks. So `style.css` is for shared styles and `style.yml` is for PDF specific ones?

**Comment by mojavelinux** [comment]
Essentially, yes. I would say that `style.css` is for HTML and `style.yml` is for PDF (specifically the Asciidoctor PDF converter).

It's possible to create PDF from the HTML, thus taking a different route. Some people chose to do this and it's always an option to keep in mind. There are some limitations, since HTML wasn't really designed for print media, but if those limitations are acceptable, it could be a good path. You'd get there by using some sort of Print to PDF function, either manually or using a tool like wkhtmltopdf or similar.

**Comment by mojavelinux** [comment]
The main purpose of Asciidoctor PDF is to stand in for the PDFs that people were previously creating using the fo/pdf or dblatex output of the DocBook toolchain.

**Comment by danijar** [comment]
Thanks. I see how `asciidoctor-pdf` fits in, especially with print specific features such as footnote/figure placement being worked on.

**Comment by mojavelinux** [comment]
:+1: 

Footnotes are next on my list. I know they are a huge pain point right now.

**Comment by barspi** [comment]
I think the footnotes issue is the only big roadblock I'm having now for adopting asciidoctor-pdf (the last release fixed the other ones)

**Comment by mojavelinux** [comment]
I'm so glad to hear alpha.14 knocked out a bunch of issues for you. I'll start hacking on the footnotes and hopefully get it into alpha.15.
