### ISSUE TITLE
Split up converter.rb?

### ISSUE THREAD

**Issue by mchernosky** [asciidoctor/asciidoctor-pdf#758]
I'm loving Asciidoctor -- and going directly to PDF with asciidoctor-pdf to in particular. I tested out changing some of the behavior (change the title page layout, header/footer placement, etc), but **converter.rb** is a pretty large file and hard to find my way around.

It seems to me that it should probably have it's functionality split up into _a bunch_ of other files. Does anybody else think so? Or have any ideas about how to do so?

**Comment by mojavelinux** [comment]
I agree. In fact, the comment at the header of that file reminds me of this every time I open the file.

This is certainly a goal. However, I'm not willing to refactor this file until #37 is solved because we have no way to verify if we break anything (aside from manual testing).

We also want to join this with #53, because we have to rewrite everything anyway to fit in that new model. It would be a perfect time to address both issues.

**Comment by mchernosky** [comment]
Hmm, a unit test suite, that _would_ be great... and make refactoring safer. Seems like a reasonable prerequisite.

**Comment by mojavelinux** [comment]
I regret putting it off. Trust me.

**Comment by mojavelinux** [comment]
Btw, the test suite is there now, with > 700 tests.

I still want to see this wrapped up as part of #53 since we don't want to do the work twice.

**Comment by mojavelinux** [comment]
At this point, I don't have any plans personally to break up converter.rb. But we do have a test suite that is approaching 2,000 tests. That's the backstop I need right now to ensure stability and accommodate refactoring.

Now that we have a test suite, I'm comfortable with someone coming along and proposing different ways to organize the code. But I ask that you keep the changes focused on a particular part of the code to avoid one monolithic change.
