### ISSUE TITLE
Render include_processor into pdf document

### ISSUE THREAD

**Issue by kytrinyx** [asciidoctor/asciidoctor-pdf#78]
I understand that the `asciidoctor/extensions` support is experimental, so this may not be feasible at the moment.

We have a custom `include_processor` that includes code at a specific git tag:

```asciidoc
[source,ruby,src_numbered]
----
include::smart:lib/bottles.rb[git_repo='../../99bottles/.git', git_tag='example-incomprehensibly-concise']
----
```

 When generating the pdf, this shows up as:

```
link:smart:lib/bottles.rb[]
```

Is there a way to hook into the extensions when generating the pdf?

**Comment by mojavelinux** [comment]
The include processor extension should work with the pdf converter, at least I expect it to behave itself :)

I'll cite the extension lab for a working example. If you install asciidoctor-pdf:

    $ gem install asciidoctor-pdf --pre

Then clone the extension lab repository:

    $ git clone https://github.com/asciidoctor/asciidoctor-extensions-lab

You can run one of the include processor examples to see how the extension is enabled with asciidoctor-pdf

    $ asciidoctor-pdf -r ./lib/uri-include-processor.rb lib/uri-include-processor/sample.adoc

or

    $ asciidoctor -r asciidoctor-pdf -r ./lib/uri-include-processor.rb lib/uri-include-processor/sample.adoc

If you're still having trouble getting it to work with your example, let me know where your extension lives and I'll try to debug.

Btw, the extensions are more stable than the documentation suggests. It's the documentation that's still in the experimental phase ;)

---

In your example, if you are seeing:

    link:smart:lib/bottles.rb[]

It means two things:

1. The extension isn't being enabled (check that you are using `-r` or requiring the extension if calling from the Ruby API)
2. The safe mode is set to the default (secure) since the normal include isn't working (in secure mode, the include becomes a link...though admittedly not ideal inside a listing block).

**Comment by kytrinyx** [comment]
> Btw, the extensions are more stable than the documentation suggests. It's the documentation that's still in the experimental phase ;)

Hah. Perhaps I can help stabilise the documentation, then.

Both of your points were true. We weren't properly requiring the extension, and safe mode was set to secure.

**Comment by mojavelinux** [comment]
I'm glad to hear you got it working!

> Perhaps I can help stabilise the documentation, then.

That would be marvelous.

The information about extensions is a very weak section of the user manual. It's not really written with the goal of helping a developer understand how to use them. That's because the text was copied out of the design documents, so it's more about why it is needed and the scope. As someone exploring the API with fresh eyes, perhaps you can offer some perspectives about how to best explain it.

**Comment by kytrinyx** [comment]
I'll definitely keep this in mind as I continue to explore the docs.

**Comment by mojavelinux** [comment]
:+1:
