### ISSUE TITLE
error: <top (required)>': can't modify frozen Array (RuntimeError)

### ISSUE THREAD

**Issue by fly7632785** [asciidoctor/asciidoctor-pdf#782]
I have followed the Get Start.but some problems happened.
I just wanna whether the reason is for the Ruby's version too high  and  incompatible?
environment:
ruby 2.4

error:
`JafirdeMac-mini:~ jafir$ asciidoctor-pdf -v
/usr/local/lib/ruby/gems/2.4.0/gems/prawn-templates-0.0.3/lib/prawn/templates.rb:246:in `<top (required)>': can't modify frozen Array (RuntimeError)
	from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/asciidoctor-pdf-1.5.0.alpha.14/lib/asciidoctor-pdf/converter.rb:10:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/asciidoctor-pdf-1.5.0.alpha.14/lib/asciidoctor-pdf.rb:3:in `require_relative'
	from /usr/local/lib/ruby/gems/2.4.0/gems/asciidoctor-pdf-1.5.0.alpha.14/lib/asciidoctor-pdf.rb:3:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/asciidoctor-pdf-1.5.0.alpha.14/bin/asciidoctor-pdf:4:in `<top (required)>'
	from /usr/local/bin/asciidoctor-pdf:22:in `load'
	from /usr/local/bin/asciidoctor-pdf:22:in `<main>'`

**Comment by dduportal** [comment]
Hello @fly7632785 !

This seems to be corrected in the next version (at least it is merged in master).

@mojavelinux have provided explanation and a quick fix here: #772 

Hope it helps !

**Comment by fly7632785** [comment]
Hi,I've try the answer .

**Comment by dduportal** [comment]
Hello @fly7632785 , what do you mean by "it doesn't work" exactly ? What steps did you try ?

Can you please ensure you first removed asciidoctor-pdf gem and its dependencies, and only then, install prawn in 2.1.0, and install asciidoctor-pdf gem again ? (Just sayin', since installing prawn AFTER asciidocotr-pdf has already been install won't sole anything).

If you are not into ruby or gem dependencies, I strongly suggest you to try the asciidoctor image, that embed a working asciidoctor-pdf and its dependencies, without requiring you to change anything on your machine outside Docker4Mac: https://hub.docker.com/r/asciidoctor/docker-asciidoctor/

**Comment by fly7632785** [comment]
@dduportal , thank you very much. I've solved the problem.
Firstly, exec 'gem uninstall prawn ', just uninstall 2.2,
Then install 2.1.
Everything is ok.
Shake hands.😉

**Comment by mojavelinux** [comment]
Thanks for the assist on this one @dduportal!
