### ISSUE TITLE
prawn-templates

### ISSUE THREAD

**Issue by MaWiMa** [asciidoctor/asciidoctor-pdf#803]
Please change asciidoctor-pdf.gemspec line 46, to deal with prawn 2.2.2 and prawn-templates 0.1.1
I tried it locally and it does work.

 s.add_runtime_dependency 'prawn-templates', '>= 0.0.3', '<= 0.1.1'

**Comment by mojavelinux** [comment]
In order to make this change, we also need to document how to install Asciidoctor PDF on Ruby 2.0 (since Prawn 2.2 requires Ruby 2.1). We just need to make sure people have a path to being able to install and use Asciidoctor PDF back to Ruby 1.9.3 (which is the older version of Ruby we support).

See https://github.com/asciidoctor/asciidoctor-pdf#prerequisites

**Comment by mojavelinux** [comment]
I am a little frustrated that prawn-templates forces the use of Prawn 2.2. I think that's really unnecessary that an extension forces a choice of core...but that's really out of our control.
