### ISSUE TITLE
Unable to include sections from other adoc files

### ISSUE THREAD

**Issue by saleemjaffer** [asciidoctor/asciidoctor-pdf#809]
I have included all my .adoc files in a master.adoc files. Now within one of the included files I try to reference a section from another .adoc file(This .adoc file is already included in master.adoc).

If I try to reference a section using `<<Design, Design details>>` it works fine. This works fine as the adoc file containing `Design` is in the same directory as the adoc file in which I want to include it. 

But if I do this `<<design.adoc#Design, Design>>` and try to click on the link I get an error pop up on my mac saying "There is no application set to open the URL design.pdf#".

I need this as I also need to include sections from adoc files in other directories (these adoc files are also included in master.adoc)

How to to this?

**Comment by mojavelinux** [comment]
Inter-document cross references only resolve if you structure your document in accordance with the design. Specifically, the path segment of the inter-document reference must match the value used to include the document.

For example, if you use the following include:

```
include::chapters/chapter-1.adoc[]
```

Then the inter-document cross reference must be:

```
<<chapters/chapter-1#anchor-name,Chapter 1>>
```

This is true no matter which document the cross reference is in.

To resolve the inter-document cross reference, Asciidoctor first checks if the target matches the docname attribute. Then, it looks to see if the target matches one of the included files. (In both cases, ignoring the file extension).

If Asciidoctor cannot resolve the target of an inter-document cross reference, then it simply makes a link, as you have observed.

Keep in mind that since PDF is a single document, you have to provide both a target and an anchor in the inter-document cross reference. Otherwise, the link will just jump to the top of the document.

**Comment by mojavelinux** [comment]
I'm going to mark this issue as documentation since this information belongs in the README.

**Comment by mojavelinux** [comment]
Here's a complete example. Assume you are converting the following book document at the root of the project:

**book.adoc**
```
= Book Title
:doctype: book
:idprefix:
:idseparator: -

include::chapters/chapter-1.adoc[]

include::chapters/chapter-2.adoc[]
```

The contents of chapter 1 is as follows:

**chapters/chapter-1.adoc**
```
== Chapter 1

We cover a little bit here.
The rest you can find in <<chapters/chapter-2.adoc#chapter-2,Chapter 2>>.
```

The contents of chapter 2 is as follows:

**chapters/chapter-2.adoc**
```
== Chapter 2

Prepare to be educated.
This chapter has it all!

To begin, jump to <<chapters/chapter-2/first-steps.adoc#first-steps,first steps>>.

<<<

include::chapters/chapter-2/first-steps.adoc[]
```

Where the content of the nested include is:

**chapters/chapter-2/first-steps.adoc**
```
=== First Steps

Let's start small.
```

Admittedly, you sometimes have to get creative to make inter-document cross references work. The design is still evolving.

**Comment by saleemjaffer** [comment]
Apparently the reason why I was not able to get it to work were the `idprefix ` and `idseparator` attributes. 

If an adoc file I want to reference is in the same directory I can use `<<Section Title, Section>>` . 
But if I need to include an adoc file in another directory then I need to use <<files.adoc#section-title, Section Title>>.  Meaning I need `idprefix ` and `idseparator`  if I have to cross reference sections of documents in other directories. Why is the `idseperator` a must?

Is this a bug?

**Comment by mojavelinux** [comment]
> If an adoc file I want to reference is in the same directory I can use `<<Section Title, Section>>`.

This always works. It's just not an inter-document cross reference, so it doesn't work unless you are combining the sources into the same output file. It's just a regular in-page reference. It's orthogonal to the feature we are talking about.

> Meaning I need idprefix and idseparator if I have to cross reference sections of documents in other directories.

The value of the idprefix and idseparator don't affect this feature. They only affect the generated ID. I just added them because I like to make the values explicit. If you didn't add them, then the cross reference in the example would be:

```
<<chapters/chapter-2#_chapter_2,Chapter 2>>
```

That's because the default value for both attributes is underscore. I'll probably remove them when I copy over the documentation so it doesn't distract from the point.

> But if I need to include an adoc file in another directory...

then the first segment of the inter-document cross reference must match the path of the file relative to the master document (minus the file extension). I refer to this path as the rootname (taking the terminology from Python).

**Comment by saleemjaffer** [comment]
Cool everything makes sense. It is really helpful getting a detailed explanation!

One last thing:

> This always works. It's just not an inter-document cross reference, so it doesn't work unless you are combining the sources into the same output file. It's just a regular in-page reference. It's orthogonal to the feature we are talking about.

This does not always work right? **Even if I include all the adoc files in the master adoc**, I am able to do `<<Section Title, Section>>` to get a link to section named `Section Title` only if the adoc containing `Section Title` and the adoc from which I try to reference it are in the same directory level. Otherwise it fails and I have to use the syntax by you.

**Comment by philipp2100** [comment]
Is there any point in having this requirement (of paths in xrefs being relative to the including file)?

Maybe `relfileprefix` could be used to resolve xrefs correctly in this case?
It already seems to be used when generating the links after not being able to resolve the xrefs, so a much cleaner solution may be to just use it in the resolving stage already.

This way, the included documents could be clearly separated from the including document and wouldn't even need to know that they are included.
That would allow for example for the included documents to be "compiled" separately *or* as includes -- both would work. This way you could have an HTML version with separate files and a PDF version using `include::` to generate one big file.
Another use case would be separate top-level projects -- in different folders -- including the same files.

`relfileprefix` would be set accordingly in the including documents in this case.
However, maybe that would break existing code that already uses `relfileprefix` for other purposes and relies on it not being used. There may be ways to overcome this, however.

The current behavior is a bit surprising, as this seems to be exactly what `relfileprefix` should do (it doesn't even work when you put it in the included file).
The other way around -- using xrefs relative to the including file but include `relfileprefix` in the *included* files to make the xrefs work when they are "compiled" on their own -- works and is at least a workaround for the first use case.
It seems confusing, though, that `relfileprefix` behaves differently with included files. If this is supposed to stay this way, I think it should be documented, maybe also mentioning this workaround.

Disclaimer: I'm pretty new to AsciiDoc (but I already love it), so apologies if this just stems from bad understanding on my side!
