### ISSUE TITLE
Cross Reference Does Not Work as Proposed in Documentation

### ISSUE THREAD

**Issue by KlugB** [asciidoctor/asciidoctor-pdf#810]
This may be a documentation error. [http://asciidoctor.org/docs/user-manual/#anchordef](http://asciidoctor.org/docs/user-manual/#anchordef) says:
> Defining an inline anchor ID in an header
> _=== [[current]]Version 4.9_

It seems this does not work. Example:

```
= SampleDoc
:doctype: book
:encoding: utf-8
:toc: left
:numbered:

== ChapterOne

A reference to <<ChapterTwo>> works.

A reference to <<chapter3>> works, too.

A reference to <<chapter4>> points to the Table of Contents entry 
instead of the chapter heading AND breaks the link of the ToC-entry.

Tested with both asciidoc-preview 2.10.1 in Atom 
and Asciidoctor.js Live Preview 1.5.5.100 in Chrome.

== ChapterTwo

[[chapter3]]
== ChapterThree

== [[chapter4]]ChapterFour
```

But shouldn't the chapter4 version work also?

**Comment by KlugB** [comment]
Sorry, this should of course have landed in asciidoctor / asciidoctor. Could you move it there, please?

**Comment by mojavelinux** [comment]
If this is a documentation error, then it belongs in asciidoctor/asciidoctor.org. However, I first need to make that determination. Stay tuned.

**Comment by mojavelinux** [comment]
The inline anchor in a section title is only promoted to the section ID if it follows the section title and is offset by at least one space character.

For example:

```
== ChapterFour [[chapter4]]
```

Otherwise, it's just a regular inline anchor, which can interfere with the the linking mechanism of the TOC due to https://github.com/asciidoctor/asciidoctor/issues/840 (and also reported in https://github.com/asciidoctor/asciidoctor/issues/1875).

**Comment by mojavelinux** [comment]
I'm going to update this information to the user manual.

**Comment by mojavelinux** [comment]
I've updated the documentation. Since the problem of anchors getting stuck in the generated ID (and TOC) is well covered by other issues, I'm going to close this one.
