### ISSUE TITLE
PDF does not include some content produced by a BlockMacroProcessor that is included when generating HTML

### ISSUE THREAD

**Issue by wilkinsona** [asciidoctor/asciidoctor-pdf#815]
This problem was original [reported as a Spring REST Docs issue](https://github.com/spring-projects/spring-restdocs/issues/396) but appears to apply to `asciidoctor-pdf` in general. I've prepared a [minimal example](https://github.com/wilkinsona/asciidoctor-pdf-block-macro-content-problem) that hopefully illustrates the problem.

In short, there's a block macro processor that loads a fragment of Asciidoctor content and then adds the blocks from that fragment to the parent. This works fine when generating HTML with section titles and content appearing in the resulting output. However, when generating a PDF, section titles from the fragment appear in the PDF but the contents of those sections does not.

**Comment by mojavelinux** [comment]
The problem you're facing is that the document reference for the nested blocks is still pointing to the temporary document. Asciidoctor PDF takes that document reference isn't account, which is why the nodes aren't appearing.

One way to solve this problem is to switch to using the APIs that are used for an AsciiDoc table cell. While there are some limitations to this approach, I recommend giving it a try:

```ruby
content = "=== Bar\n\nSome content\n\n=== Baz\n\nSome more content"
# when the parent option is set, the attributes option is ignored
# as a workaround, temporarily set an attribute on the document (the rest get inherited)
parent.document.set_attribute 'fragment', ''
fragment = Asciidoctor::Document.new content, parent: parent.document
fragment.blocks.each do |b|
  b.parent = parent
  parent << b
end
parent.document.delete_attribute 'fragment'
nil
```

The benefit of this approach is that the document reference of the temporary nodes shares all the same internal state as the parent.

If you wanted to stick with your original approach of using the top-level Asciidoctor API, then you have to end with reassigning the parent of all added nodes, which in turn sets the document reference:

```ruby
parent.find_by.each {|b| b.parent = b.parent }
```

This situation actually underscores the lack of an "import node" feature in the Asciidoctor API (something equivalent to [importNode](https://developer.mozilla.org/en-US/docs/Web/API/Document/importNode) in the DOM). See https://github.com/asciidoctor/asciidoctor/issues/2226.

**Comment by wilkinsona** [comment]
Thanks very much, @mojavelinux. As recommended, I gave your first approach a try. It worked fine for the example that I provided, but did not work if the content contained a table.

Updating the document reference by reassigning the parent worked fine for everything that I tried so I've [gone with that approach](https://github.com/spring-projects/spring-restdocs/commit/ba327f1e9af906987b1920d15eefcc7868729a2d). Thanks again.
