### ISSUE TITLE
Error in rendering table cell with literal column style when text contains '&' or '&&'

### ISSUE THREAD

**Issue by BrianEmberling** [asciidoctor/asciidoctor-pdf#816]
Running asciidoctor-pdf 1.5.0.alpha.15, using asciidoctor 1.5.5

I'm trying to have one column use the "literal" style.
This simple example with a table fails with the error message:

Failed to parse formatted text: D.i = S0.i + S1.i;
Â SCC = (S0.u31 == S1.u31 &&

However, if you delete the "&&" in the last line, it passes.  I don't see why that should matter.
(I'm trying to quote some code in a table cell).
Escaping the && doesn't help (but it shouldn't be necessary anyway).

```
= myHeader

[cols="d,d,l", options="header, autowidth"]
|===
| Opcode | Name | Description
| 1 | S_SUB_U32 |    D.u = S0.u - S1.u;
 SCC = (S1.u > S0.u ? 1 : 0).
| 2 | S_ADD_I32 | D.i = S0.i + S1.i;
 SCC = (S0.u31 == S1.u31 &&
|===
```

**Comment by JBR69** [comment]
Hi,

it works for me...
asciidoctor 1.5.5 / asciidoctor-pdf 1.5.0.alpha.15

![image](https://cloud.githubusercontent.com/assets/20417124/26554277/9664e580-448f-11e7-9e97-fedd6843e2ec.png)

Jérôme

**Comment by BrianEmberling** [comment]
that's really odd.  I just reinstalled ruby and all gems:
I'm running on windows (7)

- ruby 2.4.1.p111  ( I was using ruby 2.3 for the previous case)
            ruby 2.4.1p111 (2017-03-22 revision 58053) [i386-mingw32]
- asciidoctor 1.5.5
- asciidoctor 1.5.0.alpha.15

Command: asciidoctor-pdf  test.adoc -o test.pdf

I simplified the test case even more and still the error:
    Failed to parse formatted text: D = S1 &&

```
= myHeader

[cols="2,2l", options="autowidth"]
|===
| 0 | D = S1 &&
|===
```
The interesting this is the error goes away if one of 3 things change:
1. delete the "&&"
2. change column2 from "2l" to "2"
3. delete the: options="autowidth"

**Comment by mojavelinux** [comment]
Thanks for raising this issue. It does have to do with the autowidth option. When that option is set, Prawn attempts to calculate the width of the string in the cell. For literal cells, we have set the `inline_format` option to false. Unfortunately, Prawn doesn't check the value of this option...it only checks for the presence of the key. That's why it's trying to format the string (and failing). To fix this, we should not set the `inline_format` option at all for literal cells.

The warning is somewhat harmless. It still manages to calculate the width of the string from the fallback value (although the calculation ends up being slightly off).

**Comment by mojavelinux** [comment]
The fix is to simply remove the following line

https://github.com/asciidoctor/asciidoctor-pdf/blob/d5bea5e29ce11eae7d6da954d1ca15de714b39b5/lib/asciidoctor-pdf/converter.rb#L1598
