### ISSUE TITLE
PDF generation breaks "unbreakable" tables

### ISSUE THREAD

**Issue by owenh000** [asciidoctor/asciidoctor-pdf#819]
The `unbreakable` option does not seem to have any effect on PDF output. Is this not supported? Thank you!

```
[options="header,unbreakable"]
|===
|Category|Item

|Category 1
|Item 1
...
```

![screenshot](https://cloud.githubusercontent.com/assets/5339120/26743946/6ec3504e-47a9-11e7-88fb-88c6d0954c1f.png)

**Comment by bameda** [comment]
It happens to me too

**Comment by mojavelinux** [comment]
It's not currently supported.

**Comment by dalemartin** [comment]
I think this would be a good feature to have. Mercifully the header row is at least repeated when the table breaks across a page.

**Comment by mojavelinux** [comment]
There's really nothing we can do about this in Asciidoctor PDF. This is being done by prawn-table. The change would have to go there.

**Comment by graphitefriction** [comment]
Related to #2022

**Comment by graphitefriction** [comment]
In the upcoming release of Asciidoctor PDF 2.0, you will be able to prevent an orphaned table caption by assigning the option `breakable` to a table.

```
.Optional table caption/title
[%breakable]
|===
|Content |Content

|Content |Content
|===
```

Note that the table will still break if it flows from the current page to the next page. The `breakable` option only prevents the table caption (and ID, if one is assigned) from being orphaned. (We decided it was best if people choose to opt-in to this behavior due to the potential performance costs in some cases.)

Also, you'll be able to assign the `unbreakable` option to a table if you don't want it to break and flow to the next page when it doesn't fit on the current page.

```
.Optional table caption/title
[%unbreakable%header,cols="2*"]
|===
|Content
|Content

|Content
|Content
|===
```
