### ISSUE TITLE
Adobe Acrobat always open bookmarks and does not remember last position

### ISSUE THREAD

**Issue by rterekhov** [asciidoctor/asciidoctor-pdf#840]
When I open PDF documents generated with asciidoctor-pdf in Adobe Acrobat Reader it always opens bookmarks panel and shows the first page of the document. Adobe Acrobat does not remember my current position in document, the next time I open the same document. It works for other PDF documents that I have, but not for the PDF documents generated with asciidoctor-pdf.

**Comment by billybooth** [comment]
This is due to the PageMode set here:
https://github.com/asciidoctor/asciidoctor-pdf/blob/master/lib/asciidoctor-pdf/converter.rb#L2833

You can comment out that line to use the default PageMode, which is `UseNone` or specify your preference, using the values indicated in Adobe's Acrobat documentation:

> The PageMode key specifies how the document is to be displayed when opened. It can take
the following values:
>
>● UseNone — Open the document, displaying neither bookmarks nor thumbnail images.
>● UseOutlines — Open the document and display bookmarks.
>● UseThumbs — Open the document and display thumbnail images.
>● FullScreen — Open the document in full screen mode.
>
>If PageMode is not specified, the value defaults to UseNone.

I do not believe this is currently configurable in asccidoctor-pdf.

**Comment by mojavelinux** [comment]
I'd be open to making this a configuration option, much like `pdf-page-size` and `pdf-page-margin` (see https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#theme-related-document-attributes). Feel free to submit a PR.

**Comment by mojavelinux** [comment]
We have since introduced the pdf-page-mode attribute and theme key. However, the only value it accepts right now is fullscreen. I suppose we could build on that.

> and shows the first page of the document. 

According to the spec, the page mode does not control which page is opened by default. That's your reader doing that, I believe. My reader remembers the last location.

**Comment by mojavelinux** [comment]
We'll recognize the following values:

* outline
* none
* thumbs
* fullscreen
* fullscreen outline
* fullscreen none
* fullscreen thumbs

In the case of fullscreen, the second value is the mode after you drop out of fullscreen.

**Comment by mojavelinux** [comment]
> If PageMode is not specified, the value defaults to UseNone.

If the page mode is not specified, we default to /UseOutlines (since it's the more logical behavior).
