### ISSUE TITLE
How to display strikethrough inside code block

### ISSUE THREAD

**Issue by fatoni69** [asciidoctor/asciidoctor-pdf#843]
I want to display strikethrough on my code inside the code block.. not inline-code. How can I do it?
example:

```
----
hello text strikethrough
----
```

**Comment by mojavelinux** [comment]
You need to apply the quote subs to the block:

```
[subs=+quotes]
----
[.line-through]#hello text strikethrough#
----
```

If you want more control over the order of subs, you can provide an explicit list. But don't forget the specialchars substitution when working with verbatim content.

```
[subs="specialchars,quotes"]
----
[.line-through]#hello text strikethrough#
----
```

It's not possible to combine this feature with source highlighting in Asciidoctor PDF due to the order of operations. So you can either have inline formatting or source highlighting, but not both.

**Comment by mojavelinux** [comment]
See http://asciidoctor.org/docs/user-manual/#applying-substitutions for  more information.

**Comment by fatoni69** [comment]
oh ok.. it works, thanks :)
