### ISSUE TITLE
allow footer and header configuration by document attributes

### ISSUE THREAD

**Issue by maybeec** [asciidoctor/asciidoctor-pdf#849]
https://github.com/asciidoctor/asciidoctor-pdf/issues/89#issuecomment-107106388:
>For now, I decided to make this part of the theme rather than the document because I don't think this is content that belongs in the document. We could still consider allowing the document to contribute to what the theme sets via attributes, but let's deal with that in a follow-up issue.

Is there meanwhile any possibility to allow header and footer to be set by document attributes? The reason why is, that we want to provide a common styling to be slightly customized by the document creators. We did not find out how to inherit stylings like the default asciidoctor-pdf styling and just specify/override isolated styling attributes. Therefore, we would have needed to share the complete styling.yml if a minor change on header/footer is needed.

So why not providing the ability over document attributes to customize header/footer like the title-logo?
I would propose something like 

```asciidoc
:footer:
<any asciidoc code>
:footer:
```

for footer and header. This would enable to share stylings more effectively.

**Comment by maybeec** [comment]
Even a more generic solution would be to provide the ability to override single styling properties withing the asciidoc such that I can have full access to all styling attributes to override the default stylings if necessary.
I know the argument of asciidoc pollution, which raises as a hazard with this. However, I think it is much more convenient to use such mechanism for small styling changes than provide a complete new styling.yml.

**Comment by refaelsh** [comment]
+1 to what @maybeec is suggesting.

**Comment by mojavelinux** [comment]
There are some attributes you can control from the AsciiDoc document that influence the styling. These are listed here: https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#theme-related-document-attributes It includes title-logo-image, since that's something closely related to content. However, for anything not listed there, we decided to focus on making the theme easier to extend. See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#keys-extends.

It's also possible to pass the resolved pdf_theme as an option to the Asciidoctor API. So if you want to augment the theme in your own way, you now have the power to do that. You can see an example of this in the test suite here: https://github.com/asciidoctor/asciidoctor-pdf/blob/master/spec/spec_helper.rb#L260-L262

If none of these options work for you, please open a new issue describing where this fell short and we can revisit it.
