### ISSUE TITLE
PDF generated despite an error on an image

### ISSUE THREAD

**Issue by JBR69** [asciidoctor/asciidoctor-pdf#867]
Hi,

I have a problem with the alpah.15 version (but I don't know since which version this problem exists).
Previously when there was an error on an image, the generation of the PDF was interrupted.
Today, in the logs I can have this error
`
ErrorNotification.js:122 [node-error 8:33:59 AM] asciidoctor: ERROR: could not embed image: F:/Documentations/asciidoc/sources/fr/resources/images/EVO-AA/image052.png; PNG uses unsupported interlace method
`
but the PDF file is still generated.

Is this a desired evolution or a bug?
Where should I make changes so that the generation hangs in case of error?

Thank you.
Jérôme

**Comment by jlozadad** [comment]
running into the same issue.

**Comment by mojavelinux** [comment]
I strongly encourage you to use the gmagick integration documented here https://github.com/asciidoctor/asciidoctor-pdf#supporting-additional-image-file-formats when working with PNG images. Prawn only has rudimentary support for PNG by default.

> Where should I make changes so that the generation hangs in case of error?

The policy of the Asciidoctor processor is not halt because of a content error. Right now you have to check for warnings on stderr, but in the future we'll have a logging and document errors facility.

**Comment by JBR69** [comment]
Thank you for your answer but `prawn-gmagick` is limited to Linux and OSX and I'm using windows.

**Comment by mojavelinux** [comment]
In this case, it's really just a warning...and may not affect the image at all. Just verify that the image looks correct. If you want to make the warning go away, just reencode the image without interlace support, or reencode it to jpg.

**Comment by JBR69** [comment]
Yes this is what I am doing.
But my problem is that I want to halt the PDF generation.
We generate about 80 documents every night (with jenkins job) and we quickly know if an image is not good.
The solution I found (and that works) for the moment is to replace (in `inline_image_arranger.rb`)

```warn% (asciidoctor: ERROR: could not embed image: # {image_path}; # {e.message})```

by

```raise :: IOError,% (asciidoctor-pdf: ERROR: could not embed image: # {image_path}; # {e.message})```

Jérôme

**Comment by mojavelinux** [comment]
This traces back to https://github.com/asciidoctor/asciidoctor/issues/44.

It's Asciidoctor's policy not to throw errors on conversion of a document on a warning or error...because that puts a road block in the writing process. But once we collect errors and warnings (instead of just printing them), then we have the ability to provide gates that can control how to handle this condition. But I'm not going to make a change for this one issue when the discussion is much broader.

**Comment by mojavelinux** [comment]
What I encourage you to do right now is capture the stdout coming from Asciidoctor and fail the build if there are messages printed. There are several projects out there that provide a script for this.

**Comment by mojavelinux** [comment]
Asciidoctor PDF now uses the Asciidoctor logger. So if you want to fail on warnings, you can check if any warnings were logged and fail. The Maven plugin happens to have a hook for this.
