### ISSUE TITLE
Having Prawn option compress to be an optional parameter (to deal with file sizes of generated PDFs)

### ISSUE THREAD

**Issue by prasadus92** [asciidoctor/asciidoctor-pdf#872]
Currently, the Prawn options - `compress` and `optimize-objects` are disabled by default. Can we have these as optional parameters? 
I agree that there is an alternative way of using Ghostscript to optimize the file size but it's a burden to have it as a dependency.

https://github.com/asciidoctor/asciidoctor-pdf/blob/bb4727203fca94a24defd3aa36696e8fedcafd6d/lib/asciidoctor-pdf/converter.rb#L282

**Comment by mojavelinux** [comment]
The reason these flags are not enabled is because they corrupt the output document. The author of Prawn even recommends against using them, as far as I remember. ghostscript handles compressing and optimizing without errors and does a much better job at it.

There is a good alternative solution. [hexapdf](https://github.com/gettalong/hexapdf) can read in a PDF file and optimize and compress it probably even better than ghostscript. What we could do is document the steps that show how to do this. We just can't integrate it directly into Asciidoctor PDF because of license incompatibility. 

See https://github.com/gettalong/hexapdf/blob/master/examples/optimizing.rb

**Comment by jefftp** [comment]
@prasadus92 In line with what Dave said above, you can leverage hexapdf to optimize your PDFs from the command line pretty effortlessly. (requires ruby-io-console)

```
hexapdf optimize --compress-pages <in-file> <out-file>
```

Alternatively, if you just want to quickly and easily optimize your PDFs without page compression, I'd recommend QPDF. (requires zlib and libjpeg)

Both of these have fewer requirements than ghostscript and are easier to use for optimizing PDFs.

**Comment by prasadus92** [comment]
Thank you, Jeff and Dan. I currently am using Ghostscript, definitely I will take a look at hexapdf.
