### ISSUE TITLE
asciidoctor-pdf seems to hang in OS X

### ISSUE THREAD

**Issue by rlauriston** [asciidoctor/asciidoctor-pdf#881]
I waited a few minutes but nothing happens. The file's only 29K.
```
Roberts-13-inch-MacBook:asciidoc robert$ asciidoctor-pdf -v
Asciidoctor PDF 1.5.0.alpha.16 using Asciidoctor 1.5.6.1 [http://asciidoctor.org]
Runtime Environment (ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
Roberts-13-inch-MacBook:asciidoc robert$ asciidoctor-pdf app-mgmt.adoc
```
I installed on OS X 10.12.6 as follows, no errors:
```
\curl -#L https://get.rvm.io | bash -s stable --autolibs=3 --ruby
source /Users/robert/.rvm/scripts/rvm
gem install asciidoctor
gem install asciidoctor-pdf --pre
gem install rouge
gem install pygments.rb
gem install coderay
```
[app-mgmt.adoc.zip](https://github.com/asciidoctor/asciidoctor-pdf/files/1644360/app-mgmt.adoc.zip)

**Comment by rlauriston** [comment]
asciidoctor-pdf basic-example.adoc works fine.

**Comment by mojavelinux** [comment]
The problem is that your document is using `\r` for newlines. This is not supported by Asciidoctor. As a result, what Asciidoctor sees is one extremely long line of text. This very, very long line causes Prawn (the PDF generator) to choke trying to typeset the lines.

If you replace `\r` with `\n` or `\n\r`, then Asciidoctor PDF will be able to convert your document in no time at all.

(In the future, Asciidoctor may support `\r` as newlines, but suffice to say it doesn't work today).

**Comment by mojavelinux** [comment]
Btw, the example you provided hangs on Linux as well. So it's not specific to macOS.
