### ISSUE TITLE
Missing NAME section for man pages

### ISSUE THREAD

**Issue by gdamore** [asciidoctor/asciidoctor-pdf#882]
man pages should include the NAME chapter/section.  Currently that seems to be missing.

**Comment by gdamore** [comment]
Interestingly, running using the -d article backend seems to generate the right output.

**Comment by mojavelinux** [comment]
That's because article doctype parses the document differently, not as a manpage.

This is probably the same defect we had in the HTML converter. The name section is stored separately in the AST and needs to be handled accordingly. See https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/converter/html5.rb#L128
