### ISSUE TITLE
Prawn Icon v2.0.0 Update

### ISSUE THREAD

**Issue by berzley** [asciidoctor/asciidoctor-pdf#891]
[prawn-icon](https://github.com/jessedoyle/prawn-icon) has been updated to support Font Awesome 5 in the latest buid.

Asciidoctor PDF could possibly be upgraded to use prawn-icon v2.0.0 to utilize supported Font Awesome 5 icons.

**Comment by berzley** [comment]
I've got a branch and commit that has a possible solution: berzley@35b1fb1acfb8c57e124a07ea10758de933e99e3e

I didn't feel this was ready for a pull request, but still wanted to get it out there for eyes to pass over. prawn-icon dropped support for `fa-*` icons in v2.0.0 so that may cause a compatibility issue or two that I could have overlooked.

**Comment by jessedoyle** [comment]
Hey @berzley.

I just wanted to let you know that I've released `Prawn::Icon` 2.1.0 with a compatibility shim to assist users to move from FontAwesome 4 (see the [release](https://github.com/jessedoyle/prawn-icon/releases/tag/v2.1.0)).

The shim should allow instances of `fa-*` to be rewritten to their correct FontAwesome 5 counterpart (with a deprecation warning).

Also note that `Prawn::Icon` >= 2.0.0 drops the `octicon-*` font as well because [it is no longer TTF based](https://blog.github.com/2016-02-22-delivering-octicons-with-svg/).

If `asciidoctor-pdf` were to update to `prawn-icon` `2.1.0`, the only major impact will be the lack of Octicon fonts. I'd also recommend that any `fa-*` references should be rewritten to their FontAwesome 5 icons (though the included compatibility shim will perform the mapping for now).

I hope this helps!

**Comment by jessedoyle** [comment]
Hey @berzley - I opened up a PR that should update to the latest `prawn/icon` here: https://github.com/asciidoctor/asciidoctor-pdf/pull/939.

**Comment by mojavelinux** [comment]
PR is under review.
