### ISSUE TITLE
image in header 

### ISSUE THREAD

**Issue by gAmUssA** [asciidoctor/asciidoctor-pdf#899]
It's more the question than the issue.
is there a way to include an image in the header or footer. I couldn't find the answer in theming guide

**Comment by mcrotty** [comment]
Actually it can be done using a block image macro, try the following in a custom-theme.yml file
 
header:
  recto:
    right:
      content: 'image::./my_logo.png[width="50"]'

**Comment by va1entin** [comment]
@mcrotty The header just stays blank when I define that in my theme.

**Comment by mcrotty** [comment]
1. For others. Yes you are correct use one colon in the image macro.

2. image attributes are described in [images section](https://asciidoctor.org/docs/asciidoc-writers-guide/#images) of the Ascidoc Writers guide. You can use the "width=" or "height=" syntax to avoid setting both width and height.  Normally, you want to size the image and have the other dimension respect the image ratio (set height or width but not both). 

3. You can import the image as is but it defaults to the available page width.   In header and footers that is the column width of the header/footer "table" position (left, right or center). 

3. Cant comment on the specific issue without seeing the full yaml.  Try checking the yaml formatting. If the image cannot be found/loaded you should see a warning.  Or to debug just place some text instead of the image.

**Comment by mojavelinux** [comment]
It's now possible to control the size of the image in the running content using the pdfwidth or fit attributes. See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#images-1 for details.

**Comment by mojavelinux** [comment]
If you have other questions, feel free to reopen or file another issue.
