### ISSUE TITLE
PDF Indexes - do not hyperlink

### ISSUE THREAD

**Issue by NormanDunbar** [asciidoctor/asciidoctor-pdf#930]
Is it at all possible to have the entries in an index (pdf especially) to hyperlink to the page? Similar to the TOC?

Not a huge problem on a printed version, I admit, but nice when viewing the pdf "on line".

Cheers,
Norm.

**Comment by NormanDunbar** [comment]
Afternoon @mojavelinux . Thanks for the link, yes indeed that dpdf does have hyperlinks from the page numbers in the index. Interesting.

I've attached a sourec file and the coresponding pdf - norman_930.zip (assuming GitHub allows zip files) which shows my non-hyperlinked index entries.

The pdf was created simply using `ascidoctor-pdf Indexing.adoc`.

I'm most likely doing something incorrectly, it happens. ;o)

[norman_930.zip](https://github.com/asciidoctor/asciidoctor-pdf/files/2468812/norman_930.zip)

Cheers,
Norm.

**Comment by mojavelinux** [comment]
The line causing the problem is this one:

```
:media: prepress
```

You're asking Asciidoctor PDF to make a document for print (and specifically prepress). A print/prepress document does not have any hyperlinks. So Asciidoctor PDF is doing what you're asking it to do.

Usually, you want to pass this attribute to the processor only when you're making it for print/prepress so it's only added when you need it.

```
asciidoctor-pdf -a media=prepress document.adoc
```

**Comment by NormanDunbar** [comment]
Thanks again @mojavelinux . 

I shall close this issue now. 
It's a PICNIC. (Problem In Chair Not In Computer!)

Cheers,
Norm.

**Comment by mojavelinux** [comment]
hahahaha. That's both great to hear and a nice joke ;)
