### ISSUE TITLE
Very very slow conversion of a big listing or literal block

### ISSUE THREAD

**Issue by sytzek** [asciidoctor/asciidoctor-pdf#941]
Suppose I have a listing block of 10000 lines in asciidoc

```
----
line 1
line 2
...
line 10000
----
```
 
Converting this to PDF takes 20 minutes on my machine.
When I prepend every line with a space (marking every line as a literal paragraph) it takes about 20 seconds. That makes it less bad, but I loose the indentation because its a literal paragraph in stead of source listing.

I know a human author would not quickly write this kind of document, but I have creative users that dump the content of a generated file into the document...

**Comment by mojavelinux** [comment]
This is just a limitation you have to keep in mind when using this converter. When making a PDF, it's necessary to create PDF objects for every single line. On top of that, the converter is trying to figure out where to place these lines onto the page. So it just takes time when you feed it very large documents.

**Comment by mojavelinux** [comment]
This issue was addressed in part by the fix for #2004. The converter now does the minimum amount of work it has to do to position the block and draw its border and background.

On my machine, it takes 12s to render a PDF with the sample you provided. It takes 6s to render it once in the scratch document to determine its extent, then another 6s to render it in the primary document atop its border and background. That's the best we can do with this converter.
