### ISSUE TITLE
Problem with the inclusion of dynamically generated PNG images in PDF generator

### ISSUE THREAD

**Issue by jdesbonnet** [asciidoctor/asciidoctor-pdf#947]
I've got an problem with dynamically generated images in PDF documents. I have two charts side-by-side in a one row, two column table like so:

```
|===
| P | K
| image:http://localhost:8080/chart/nmp/SoilIndexBarP/1[640,240]
| image:http://localhost:8080/chart/nmp/SoilIndexBarK/1[640,240]
|===
```

But the first image never renders. I just get text "[640,240]". And I see this error in the logs:

```
asciidoctor: WARNING: could not embed image: /tmp/image-20181019-7309-y6masx; No such file or directory @ rb_sysopen - /tmp/image-20181019-7309-y6masx
```

However this seems to happen only the first time that image is used in the document. Subsequent references to the same URL seem to work ok. So I can work around the problem by first rendering a 0x0 pixel version of the image. But it does cause unwanted vertical white space.

```
image:http://localhost:8080/chart/nmp/SoilIndexBarP/1[0,0]
image:http://localhost:8080/chart/nmp/SoilIndexBarK/1[0,0]

|===
| P | K
| image:http://localhost:8080/chart/nmp/SoilIndexBarP/1[640,240]
| image:http://localhost:8080/chart/nmp/SoilIndexBarK/1[640,240]
|===
```

**Comment by jdesbonnet** [comment]
I should have added I'm running Ubuntu 18.04 on amd64 arch.

Asciidoctor PDF 1.5.0.alpha.16 using Asciidoctor 1.5.5 [http://asciidoctor.org]
Runtime Environment (ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)

**Comment by mojavelinux** [comment]
Thanks for reporting. The problem is that the behavior of Tempfile is incompatible with how we are using it. The temporary file gets deleted when the object is finalized, but we need it to stick around longer. Fortunately, a new method has been added on Tempfile that generates a temporary file but does not attach it to the finalizer. I switched to that method and implemented it for Ruby < 2.1.0.

**Comment by mojavelinux** [comment]
FYI, you are writing the image macro incorrectly. The width and height are the second and third positional attribute, respectively. It should be:

```
image:http://localhost:8080/chart/nmp/SoilIndexBarP/1[,640,240]
```

or

```
image:http://localhost:8080/chart/nmp/SoilIndexBarP/1[Alt Text Here,640,240]
```

**Comment by jdesbonnet** [comment]
Thanks for the fast response and fix. I'll try out the patch later in the week. Joe.

**Comment by mojavelinux** [comment]
Great! I look forward to hearing the result.

It's amazing we got this far and didn't realize how problematic that logic was. The documentation for Tempfile is super unclear. It wasn't until I read an article about Tempfile.create that I even realized Tempfile.new had the behavior it did. But I'm grateful the method now exists because it's really exactly what we want here.
