### ISSUE TITLE
Support Hiding Link URLs

### ISSUE THREAD

**Issue by znerd** [asciidoctor/asciidoctor-pdf#951]
Please add an option to support hiding of link URLs in Asciidoctor PDF.

Sample case:
```
http://google.com/[Google].
```

Current output from Asciidoctor PDF:
```
Google [http://google.com/].
```

With the option enabled, the output would be merely:
```
Google.
```

Note: in both cases, the text should still be clickable (depending on the PDF reader software).

**Comment by znerd** [comment]
The situation is: I would like to use `media-prepress` (it looks great), but I would only like to disable the printing of link URLs. Would that be possible?

**Comment by mojavelinux** [comment]
Is your intention to print the document? Meaning, do you want the links hidden because in print form you simply want links to appear as normal text?

**Comment by znerd** [comment]
My intention is twofold:

1. share the document in digital form, where the links are clickable, and
2. allow the document to be printed, where the links are (obviously) not clickable.

Note: In the future, when Asciidoctor PDF can supports printing links as footnotes or endnotes, I would prefer that instead. That would be the optimal solution in my case.

**Comment by znerd** [comment]
I don't want to use `media=screen` and the reason is that I want to distribute *one PDF file* and it should look great. Then people can see it on their screens, and click the links if they want to. Then they may decide to print that document.

So my aim is to produce a single PDF, that will be slightly more functional on screen (clickable links) than it is when printed.

> In this case, I could see having a setting that disables the printing of the URI separately.

That would be exactly what I'm looking for.

> The DocBook toolchain has something similar called "ulink.show=0".

Indeed, I found that, but then found it (obviously) doesn't apply to the Asciidoctor PDF toolchain.

> Perhaps we can have something like show-link-uri! or an explicit hide-link-uri. (I think I prefer the latter).

To be honest I have no idea what's better or more consistent. I'll gladly use anything that is offered.

**Comment by mojavelinux** [comment]
My proposal still wouldn't cover what you are after. Because if you set media=prepress with `hide-link-uri`, then the link won't be a link at all.

media=prepress is intentionally not designed for screen, so it really shouldn't be used for that purpose. It's designed for a printing a bound book. So I still argue that what you want is media=screen. A document for screen can still be printed, of course, but it also works when on screen.

The media=prepress is adding logic for printing recto/verso pages, which makes very little sense for on screen viewing.

Btw, the reason that the URI shows separately for media=prepress (or media=print) is because users specifically **did not want** the text to be a link or to be a different color. So if we make it a link, then we would undo that enhancement. But since you want just a regular link, then that's what media=screen gives you.

**Comment by mojavelinux** [comment]
(So I'm curious why media=screen is not sufficient for your needs).

**Comment by znerd** [comment]
In my experience, users/readers expect PDFs to look good on screen and be nicely printable.

I have tried `media=screen`, but it would not print every chapter on an odd page, which would be great when printing. That's why I switched to `media=prepress`.

And in my view nicely printable means that there are no link URIs scattered through the text all over the place. So for me, `media=prepress` is perfect, except for the printed links. 

Perhaps I should approach it the other way around, and go for `media=screen` and then somehow configure Asciidoctor PDF to start each section on an odd page?

Or perhaps another intermediate solution would be to add an option to print link URIs in footnotes, and then hide them, pending actual support for such footnotes?

**Comment by znerd** [comment]
> Assuming a single feed printer, all you would be doing is inserting blank pages.

Double-sided printing is a common feature nowadays. Even my home printer (less than EUR 100) supports it. So while I would not call the result is a “book” per se, perhaps “whitepaper” would be a more appropriate term…

The thing is, what Asciidoctor PDF currently provides is already great. It's only the links that look a bit messy to me. But it's not a showstopper in any way.

From my POV, if I would only get an option to hide the spelled-out URIs, without losing anything else (e.g. clickable links), that would be optimal.

**Comment by mojavelinux** [comment]
> Double-sided printing is a common feature nowadays.

Ah, okay, Now I see what you're getting at. That makes sense. (While my printer can't do this, I know that many can).

The hiding of the URI makes complete sense to me. What still doesn't make sense is how to hide the URI and still have the link be clickable on screen. Up to this point, we have treated these two uses cases a mutually exclusive. You either have a clickable link for screen, or the link is moved to the side (and, in your case, not shown). And the reason the text is not clickable in prepress is because users don't want the text to look different on paper (because it would be meaningless).

While it's easy to say that it's just this one feature, we have to understand how to express this semantically since it's never just one feature. What media type is this? It has the layout of prepress, but it's designed for screen. I'd be happy with something like screenpress. It's a little funky, but gets the point across. It means it's optimized for screen first, but prints a lot like prepress.

**Comment by znerd** [comment]
I'm not sure a new media type is the way to go, since I just don't have any expertise in this area. It does sound like it make the feature into something bigger than I thought it would have to be.

Taking a bit more of a helicopter view, this is what I can see as useful cases for producing a PDF from AsciiDoc content:

1. Primarily focused on **on-screen viewing**.
No recto/verso, links are clickable, URIs are not printed.
— This seems covered by `media=screen`.
2. Primarily focused on 2-sided printing, but can be used on-screen, **inline URIs**.
Recto/verso, links are clickable, URIs are inserted inline.
— This seems covered by `media=prepress`.
3. Primarily focused on 2-sided printing, but can be used on-screen, **hide URIs**.
Recto/verso, links are clickable, URIs are completely hidden.
— This is currently not supported in Asciidoctor PDF, but may be easy to support with an option to hide the inline URIs.
4. Primarily focused on 2-sided printing, but can be used on-screen, **print URIs outside context**.
Recto/verso, links are clickable, URIs go into footnotes or endnotes.
— This is currently not supported in Asciidoctor PDF, and is not expected to be supported anytime soon.

Currently I'm using option 2, while option 3 would be even better, and option 4 being the best possible.

Again, happy to use any approach you can offer…

**Comment by mojavelinux** [comment]
> Primarily focused on 2-sided printing, but can be used on-screen, inline URIs.
Recto/verso, links are clickable, URIs are inserted inline.
> — This seems covered by media=prepress.

This is where it's clear we need something new. prepress is not designed for screen and it could continue to diverge from screen. If we want recto/verso and screen, that's a new media type.

**Comment by espositoandrea** [comment]
Hi. I was searching for a method to hide links from the prepress PDF and I stumbled upon this issue.

I'd like to show the links in text (so that the output looks like this: "Visit page [https://example.com]"), but not show it when I put the whole link (so that the output looks like this: "Visit https://example.com/"). Now this is exactly what happens, but when I insert an email, the full URL is shown (with the `mailto` protocol). Is there a way I can hide it from the output without touching the current behaviour in the other cases?

**Comment by bsoyka** [comment]
Came across this and I would also like this feature for pretty much the same reason.

In my case, I'm generating two PDFs from the same source: one for publishing online (screen layout) and one for publishing a paperback copy (prepress layout). The screen layout version is great, but there just needs to be an option to *not* add the link URIs in the prepress layout. Basically, @mojavelinux's third case [here](https://github.com/asciidoctor/asciidoctor-pdf/issues/951#issuecomment-433847376).

This has been open for over 3 years and seems fairly simple in concept, although I'm not personally familiar with Ruby. Are there any additional updates here?

**Comment by mojavelinux** [comment]
If someone is willing to implement it, I'm willing to review it. There are thousands of open issues in this organization and not nearly as many days in the year, so it's very typical for issues to remain open for several years. That's just the nature of OSS. When someone comes forward to implement it, then it will jump the queue and have a chance to be resolved.

**Comment by bsoyka** [comment]
Totally got it, I'm pretty familiar with open-source. It just seems like a simple fix, so I wanted to ask if there was some other reason for the lack of activity on this one.

**Comment by mojavelinux** [comment]
In reading the comments again, I can't see where there is an agreement on what to actually implement. If there was a more clear proposal, then it's more likely to be implemented.

**Comment by bsoyka** [comment]
I may be a bit off in reading these comments, but it seems like a `hide-link-uri` flag would work fine. Wherever the converter is adding text next to links, add a conditional to make sure the flag isn't set. It seems it'd be that simple because in the current version, even with the text being added next to the links, the original links are still clickable, showing clickable links and URI text aren't mutually exclusive.

Again though, I have no experience with Ruby and it definitely could be more complex than that.

**Comment by mojavelinux** [comment]
I checked the code and it turns out, this has already been implemented.

```
asciidoctor-pdf -a show-link-uri! -a media=prepress document.adoc
```

It's only implemented in the main branch (the upcoming 2.0.0 release). If there is a demand, I could backport it to 1.6.x.

**Comment by mojavelinux** [comment]
Backported and released.

**Comment by mojavelinux** [comment]
@bsoyka Let me know if that works for you.

**Comment by bsoyka** [comment]
Got it to work with just a switch to the `main` git branch for installing, thanks for the backport though, much easier!

**Comment by mojavelinux** [comment]
That's great to  hear! Thanks for following up. If you're already using main, I encourage you to stick with it. That's the future, and hopefully one that's not too distant. ;)
