### ISSUE TITLE
asciidoctor-pdf failed to parse a paragraph with predefined attribute for character replacement

### ISSUE THREAD

**Issue by chuanhua** [asciidoctor/asciidoctor-pdf#954]
I got the failed parse error on the following paragraphs with "predefined attribute". The html is rendered fine with asciidoctor, but the pdf rendering is wrong with asciidoctor-pdf.

---------------------------

A fixed parameter of the CLIC (`CLICINTBITS`) is how many total bits
are present in the `clicintcfg` registers , with 2 {lt}=
`CLICINTBITS` {lt}= 8.  The implemented bits are kept left-justified
in the most-significant bits of each 8-bit `clicintcfg[__i__]`
register, with the lower unimplemented bits treated as hardwired to 1.
These configuration bits are interpreted as mode, level, and
priority depend on the setting of the `cliccfg` register as
described below.

If the `nmbits + nlbits` {gt} `CLICINTBITS`, then the lower bits of
the 8-bit interrupt level are assumed to be all 1s.  If `nlbits` {lt}
8, then the lower bits of the 8-bit interrupt level are assumed to be
all 1s.  The following table shows how levels are encoded in either of
these two cases.

In M/S/U harts, if `cliccfg.nmbits`{lt} 2 then all interrupts are
either M-mode or S-mode, and all are inaccessible to U-mode.

**Comment by mojavelinux** [comment]
This is not the correct use of the `lt` attribute. That attribute is only to be used when you need to reference the raw, unescaped character, which is usually never.

AsciiDoc already escaped XML special characters by default. So there's nothing special you need to do to escape them. You just need to escape the arrow:

```
with 2 \<= CLICINTBITS \<= 8
```

You could also write it as:

```
with 2 &lt;= CLICINTBITS &lt;= 8
```

The only reason this works when converting to HTML is because the browser is being extremely forgiving. The source generated from your markup is still technically incorrect.

**Comment by chuanhua** [comment]
Thanks for the answer. I understand it now.
