### ISSUE TITLE
Image is included doubly 

### ISSUE THREAD

**Issue by MorinoKuma3da** [asciidoctor/asciidoctor-pdf#958]
I would like to include a image, but doubly.

In preview on VScode, it is correctly as follows. 
![preview](https://user-images.githubusercontent.com/45023054/48456365-27cb1780-e802-11e8-9e23-eecad518ccf7.png)

But, I got a created PDF as follows.
![pdf](https://user-images.githubusercontent.com/45023054/48456370-2e598f00-e802-11e8-96b8-c72d9ee76bac.png)

Please advise me.

**Comment by MorinoKuma3da** [comment]
Hi, mojavelinux,
Thank you for trying to reproduce. And Thanks to your advice, I could fixed this problem to use double colon! 

Would you still like me to provide a sample project that demonstrates this problem?

**Comment by mojavelinux** [comment]
I'm glad to hear the switch to a block image got you around the problem.

Yes, I would still be interested in a project and the details how you are running Asciidoctor PDF so I can figure out what's going wrong.

**Comment by mojavelinux** [comment]
As it turns out, the bug is somewhere in asciidoctor-pdf-cjk. If I disable that extension, it works fine.

**Comment by mojavelinux** [comment]
I think the problem may be that the extension is manipulating the placeholder text, thus confusion Asciidoctor PDF into rendering the image twice.

**Comment by mojavelinux** [comment]
You are correct that it only happens when using the IPA font. These are the two conditions that must be true:

* the theme is using the IPA font
* there is a zero-width space in the alt text

It looks like somewhere deep inside of Prawn the fragment that holds the image is being duplicated in this circumstance. I don't exactly know why. But we can easily workaround this issue by stripping zero-width space from the alt text of the image.
