### ISSUE TITLE
Document title theming

### ISSUE THREAD

**Issue by ogmios-voice** [asciidoctor/asciidoctor-pdf#988]
As a follow up on issues #105 and #135 we should be able to theme the document **title section** in a consistent way while also supporting the requirements of the different document types (i.e. separate title page vs. title section followed by content).

The first question is what should include the **title section**?

* In case of a `book` it is composed of the `logo` (image), `title`, `subtitle`, `authors`, and `revision`.
* In case of an `article` (according to #975) it includes only the `title`.

**Comment by habamax** [comment]
I believe for the article it should include everything but logo (`title`, `subtitle`, `authors` and `revision`)

```
    				 Title
    				Subtitle
    				 Autors
    				Revision

    				 Title
    				Subtitle
    	                Autors           Revision

```

**Comment by habamax** [comment]
And actually, as of now #105 renders Title and Subtitle the same way as for HTML backend: `Title: Subtitle`

**Comment by ogmios-voice** [comment]
Based on comment: https://github.com/asciidoctor/asciidoctor-pdf/issues/105#issuecomment-450627928
I'm suggesting the extension of the theme config with a **new** root level **section** named e.g. `title_block` that could include the same values as the `title_page` section with the exception of the `logo`.

1. **Articles** will use this new `title_block` to theme the `title`, `subtitle`, `authors`, and `revision `fields.
2. **Books** will use the already existing `title_page` configuration.
3. All `title_page` configuration values will **fall back** to the values defined under `title_block`.
4. All `title_block` configuration values will **fall back** to the current fallback values of `title_page`.

What do you think?

**Comment by mojavelinux** [comment]
As I stated in https://github.com/asciidoctor/asciidoctor-pdf/issues/66#issuecomment-1128562591, we've decided to focus on a programmatic solution to this need. Refer to that comment for the reasoning.

If someone would like to come forward with a proposal to change the built-in `ink_title_page` method to look for additional keys, I won't rule it out. However, I think you'll quickly find that no matter how many keys we add, it's always going to feel constrained trying to design through configuration (short of recreating CSS). That's why I think a more powerful approach is to make the converter easier to extend, which is what we've done.

If you think it would be easier if we made an "ink" method for the article title, I'm open to considering that. However, I think you'll find that you can already capture that hook by checking the `opts[:role] == :doctitle` in the `ink_general_heading` method.

```rb
def ink_general_heading doc, title, opts
  return super unless opts[:role] == :doctitle
  theme_font :doctitle do
    ink_prose title, align: :center
  end
  margin_bottom theme.heading_doctitle_margin_bottom
end
```

Since I don't see any clear action right now, I'm going to close this issue as covered by existing enhancements in Asciidoctor PDF 2.0. If you still see room for improvement, please open a new issue that builds on current functionality.
