### ISSUE TITLE
Extra space between counter2 macro and content

### ISSUE THREAD

**Issue by znerd** [asciidoctor/asciidoctor-pdf#989]
**Steps to reproduce:**

1. Have an AsciiDoc file with this content ([test.adoc.txt](https://github.com/asciidoctor/asciidoctor-pdf/files/2724087/test.adoc.txt)):
```
== Heading 1
IMPORTANT: This is the first guideline, without a number.

== Heading 2
{counter2:guideline}

IMPORTANT: And this is the second guideline, with a number: {guideline}.
```
2. Convert AsciiDoc to PDF using `asciidoctor-pdf`.

**Expected results:**
1. Small amount of space between first heading and admonition block.
2. Equally small amount of space between second heading and admonition block.

**Actual results:**
1. OK: Small amount of space between first heading and admonition block.
2. NOK: Larger amount of space between second heading and admonition block.

**Extra information:**
```
$ asciidoctor-pdf --version           
Asciidoctor PDF 1.5.0.alpha.16 using Asciidoctor 1.5.7.1 [https://asciidoctor.org]
Runtime Environment (ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

Here's a screenshot from the PDF:
![screenshot 2019-01-03 15 29 25](https://user-images.githubusercontent.com/117866/50642785-855f2300-0f6c-11e9-8bdc-40445ee89ee8.png)

**Comment by mojavelinux** [comment]
The scenario you're describing is exactly by design. Attribute references are resolved as tokens once paragraphs have been partitioned. Since the attribute reference stands on its own, it gets a dedicated paragraph. Asciidoctor doesn't come behind and look for blank paragraphs after the text has been substituted. 

If you want to avoid the blank paragraph, you need to attach the counter declaration to an existing paragraph.

```
== Heading 2

{counter2:guideline}
IMPORTANT: And this is the second guideline, with a number: {guideline}.
```

Other trick is to tuck the counter inside an attribute entry:

```
== Heading 2

:guideline: {counter2:guideline}

IMPORTANT: And this is the second guideline, with a number: {guideline}.
```

Personally, I like the second solution best because it's very clear what's happening.

**Comment by znerd** [comment]
First option: when I do this:

```
{counter2:guideline}
IMPORTANT: And this is the second guideline, with a number: {guideline}.
```

Then the rendering messes up. At least in the AsciiDoc plugin for IntelliJ IDEA. Then `IMPORTANT:` is suddenly just considered regular text, and no admonition block is rendered anymore.

Second option: when I do this:

```
== Heading 2

:guideline: {counter:guideline}

IMPORTANT: And this is the second guideline, with a number: {guideline}.
```

…it does not bump the number anymore. So while I agree that the syntax is quite nice, it's not working in my situation.

Thirdly, when using `{counter}` instead of `{counter2}` I get hit by the bug that causes counters to be increased twice when rendering as a PDF.

But I found a fourth option, which is to change the syntax of the admonition block:

```
== Heading 2
{counter2:guideline}
[IMPORTANT]
====
And this is the second guideline, with a number: {guideline}.
====
```

Thanks again for the support @mojavelinux !

**Comment by mojavelinux** [comment]
Glad to help.

> First option: when I do this:

Ah, you're correct. That's because it conflicts with the admonition shorthand. Instead, you can write it like this:

```
[IMPORTANT]
{counter2:guideline}
And this is the second guideline, with a number: {guideline}.
```

> Second option: it does not bump the number anymore.

This should definitely work. Perhaps I'm not seeing the whole document or understanding which environment you are using. But this is the preferred solution if you have to define it on a separate line.

> Thirdly, when using {counter} instead of {counter2} I get hit by the bug that causes counters to be increased twice when rendering as a PDF.

This is just a problem with counters in general...and now I see why you want to define it outside the admonition block. Admonition blocks get rendered twice in Asciidoctor PDF. That's why the counter double increases.

I still believe this will work:

```
== Heading 1
:guideline: {counter:guideline}

IMPORTANT: And this is the first guideline, with a number: {guideline}.

== Heading 2
:guideline: {counter:guideline}

IMPORTANT: And this is the second guideline, with a number: {guideline}.

== Heading 3
:guideline: {counter:guideline}

IMPORTANT: And this is the third guideline, with a number: {guideline}.
```
