### ISSUE TITLE
Table caption not moved to next page when table is (due to available space)

### ISSUE THREAD

**Issue by PaulLieverse-TomTom** [asciidoctor/asciidoctor-pdf#993]
It seems that in case a table is being moved to next page when no longer fitting on current page, that the caption is not moved along with it, resulting in the caption at the bottom at one page, and the table at the top of the next.

This can be easily reproduced with document such as
```
= Titile

== Section
01

02

... // 03, 04, etc... just enough to fill the page. (24 seems to do the job with default theme)

24

.Table caption
|===
| Multi +
line +
cell +
that +
doesn't fit on page anymore
|===
```

Observed with asciidoctor-pdf 1.5.0.alpha.16

**Comment by mojavelinux** [comment]
Due to how Asciidoctor PDF is designed (and the design of the underlying PDF library), it's too costly (in processing time and memory) to support keep together semantics for table captions. The recommended workaround is to insert a manual page break above the table caption.

**Comment by graphitefriction** [comment]
Related to #2022

**Comment by graphitefriction** [comment]
In the upcoming release of Asciidoctor PDF 2.0, you will be able to prevent an orphaned table caption by assigning the option `breakable` to a table.

```
.Optional table caption/title
[%breakable]
|===
|Content |Content

|Content |Content
|===
```

Note that the table will still break if it flows from the current page to the next page. The `breakable` option only prevents the table caption (and ID, if one is assigned) from being orphaned. (We decided it was best if people choose to opt-in to this behavior due to the potential performance costs in some cases.)

Also, you'll be able to assign the `unbreakable` option to a table if you don't want it to break and flow to the next page when it doesn't fit on the current page.

```
.Optional table caption/title
[%unbreakable%header,cols="2*"]
|===
|Content
|Content

|Content
|Content
|===
```
