### ISSUE TITLE
side margins for running content should be configurable

### ISSUE THREAD

**Issue by mkvonarx** [asciidoctor/asciidoctor-pdf#994]
Currently, the header/footer border always uses the page_margin for it's left/right position.

When changing the left/right padding of the header/footer, the header/footer border should use these instead of the page_margin to calculate the left/right position of the header/footer border lines.

**Comment by beatchristen** [comment]
I had a similar issue in the other direction: border should extend all the way to the edge of the page.
My suggested fix is in https://github.com/systarch/asciidoctor-pdf/tree/refactor-header-footer.

The integration test needs some cleaning first before I will submit a PR.

**Comment by mojavelinux** [comment]
> I had a similar issue in the other direction: border should extend all the way to the edge of the page.

If you set a background color (even if white), both the background and border extend to the edge of the page. I prefer this strategy. One modification we could consider is to use this logic even if the background color is set to transparent.

> Currently, the header/footer border always uses the page_margin for it's left/right position.

That's the starting position. You can use negative values to pull the content outwards. However, I noticed that the border and background color don't honor the negative values, but I'm not sure what the right behavior would be.

What we probably need is a running content margin. Right now the margin and padding are coupled. That's the change I would focus on making.

**Comment by mojavelinux** [comment]
> What we probably need is a running content margin

By default this would match the page margin. If we were to allow this property to be set, I think it would solve both issues.

**Comment by mojavelinux** [comment]
I'll update the issue accordingly.

**Comment by mojavelinux** [comment]
The tricky part about this issue is that the page side margin can differ by page. When media=prepress, it can differ for recto and verso pages. When the page layout is changed, it can differ for that page. So we'll need some way to be able to refer to that value with a keyword.

Here's what I propose:

* The padding is computed relative to the margin (as one would expect).
* By default, the margin is `[0, initial]`, where `initial` represents the current side margin of the page on either side.
* The content can be aligned with the content of the page using a value of `auto`. So if the margin is 0, the padding can be set to `[0, auto]` to align the running content with the page content column.
* Setting the background color and image will no longer implicitly set the side margin to 0.

For example, f you want the border to span the width of the page, but the content to be restricted to the width of the page content, use:

```
footer:
  border_width: 0.25
  border_color: dddddd
  margin: 0
  padding: [3, auto]
  ...
```

The `auto` keyword will assign a padding that's the difference of the page side margin and the running content side margin so that the content aligns with the page content.

To give another example, you can allow the border to extend on one side:

```
footer:
  border_width: 0.25
  border_color: dddddd
  padding: [3, auto]
  recto:
    margin: [0, initial, 0, 0]
  ...
```

**Comment by mojavelinux** [comment]
I really wrestled over this one, but I think I finally came up with something that I like.

By default, the running content inherits its side margins from the page. In other words, the running content fits in the same column as the main content. Thus, the implicit value is as follows:

```
footer:
  margin: [0, inherit]
```

(inherit picks up the appropriate recto/verso page margin value).

To break it out of this box, you can set the margin explicitly in the theme:

```
footer:
  margin: 0
```

While the running content area now stretches across the whole periphery, so does the content inside of it. If that's your intention, you can stop there. But if you want to stretch the area only to draw a background or border, but keep the content constrained to the content width of the page, you'll need another property. That's where the content margin comes in.

The content margin allows you to control the margin of the content independent of the margin of the running content box. Here's how we might draw a background across the whole periphery while keeping the content lined up with the main content:

```
footer:
  margin: 0
  background-color: #cccccc
  content-margin: [0, inherit]
```

That configuration emulates what happens currently when you set the background image. (That implicit behavior is being removed).

NOTE: The padding behaves as it always has.

You can, of course, use fixed values instead of the keyword "inherit". The inherit keyword just gives you that option to follow the changing margins on recto/verso pages. Speaking of which, you can also override the margin and content-margin per side (i.e., recto or verso).

The inherit keyword is smart in that it will not compound if you use it for both keys:

```
footer:
  margin: [0, inherit]
  content-margin: [0, inherit]
```

In this case, the content-margin has no affect.
