### ISSUE TITLE
Pdf source block format issue

### ISSUE THREAD

**Issue by aup-1** [asciidoctor/asciidoctor-pdf#999]
The following source block  in pdf is broken. It looks like one extra column is getting inserted.
What do I need to do to preserve the format?
Thanks for looking into this.

```
----
┌─────────────┬────────────────────────────────────────────────────┐
│   Subject   │                       admin                        │
├─────────────┼────────────────────────────────────────────────────┤
│    Issued By│abcdefsd-server-ebeb90da-761b-4f14-b9ec-30410499d2b8│
│    Issued At│2016-10-04T17:22:52.041Z                            │
│Expires After│2016-10-05T05:22:52.041Z                            │
│        Roles│ebeb90da-761b-4f14-b9ec-30410499d2b8                │
└─────────────┴────────────────────────────────────────────────────┘
----
```

in PDF this looks like 

with autofit: 
![image](https://user-images.githubusercontent.com/9544135/51762339-70723d00-209d-11e9-8cd0-e6143f50181f.png)

**Comment by mojavelinux** [comment]
autofit has a minimum font limit, which it appears you're hitting. You need to adjust the base.font_size_min setting in the theme file.

https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#key-prefix-base

**Comment by mojavelinux** [comment]
To explain further, it's not that an extra column is being introduced. Asciidoctor PDF doesn't modify your source. It's just that it doesn't fit on the line, so it's wrapping.

**Comment by vavrfam** [comment]
Thanks for the quick reply.
With base.font_size_min its little better, but even with the lowest setting (`font_size_min: $base_font_size * 0.1` ), table formatting is still is still broken.....


![image](https://user-images.githubusercontent.com/9544135/51769312-c7cdd880-20b0-11e9-8c86-c7af6cc4760e.png)

**Comment by mojavelinux** [comment]
I see more clearly what's going on now. At first I didn't notice the use of the box drawing glyphs. These glyphs don't have the same fixed width as other characters, and sometimes the font reports the wrong width, so the computation for the text placement gets messed up. If you notice, it's not an extra column. Rather, the column divider is misaligned.

If I remember correctly, this problem is deep within Prawn and outside of the control of Asciidoctor PDF. I have no yet been able to figure out how to solve it.

I would recommend avoiding the use of box drawing characters in verbatim blocks in Asciidoctor PDF. I would recommend instead using an actual table.

If someone can figure out how to support them properly, I welcome a patch.

**Comment by mojavelinux** [comment]
I tried to hack the font to reduce the width of the box drawing diagrams. However, my attempts to do so failed.

I still think this is a Prawn issue (or perhaps ttfunk). It should support double-wide characters, which is what box diagram glyphs are.

**Comment by graphitefriction** [comment]
This is documented as a known limitation (https://docs.asciidoctor.org/pdf-converter/latest/features/#limitations).
